/* ttFGPostHist.i - rstark - 6.27.2022 */

DEFINE TEMP-TABLE ttFGPostHist NO-UNDO
    {AOA/tempTable/ttFields.i}
    FIELD dmiID         AS INTEGER   FORMAT ">>9"                LABEL "DMI ID"
    FIELD transDate     AS DATE      FORMAT "99/99/9999"         LABEL "Date"       
    FIELD itemNo        AS CHARACTER FORMAT "x(15)"              LABEL "Item"       
    FIELD itemName      AS CHARACTER FORMAT "x(30)"              LABEL "Description"
    FIELD v-fg-qty      AS INTEGER   FORMAT "->>>,>>>,>>9"       LABEL "Total QTY"
    FIELD v-fg-cost     AS DECIMAL   FORMAT "->>>,>>>,>>9.99"    LABEL "Total Cost"
    FIELD v-fg-value    AS DECIMAL   FORMAT "->>>,>>>,>>9.99"    LABEL "Tot Sell Val"
    FIELD m-code        AS CHARACTER FORMAT "x(6)"               LABEL "Machine"
    FIELD jobNo         AS CHARACTER FORMAT "x(9)"               LABEL "Job"
    FIELD jobNo2        AS INTEGER   FORMAT ">>9"                LABEL "Run"
    FIELD frm           AS INTEGER   FORMAT ">>9"                LABEL "Form"
    FIELD poNo          AS CHARACTER FORMAT "x(9)"               LABEL "PO"         
    FIELD vendorNo      AS CHARACTER FORMAT "x(8)"               LABEL "Vendor"     
    FIELD v-tran-type   AS CHARACTER FORMAT "x"                  LABEL "Transaction Type"
    FIELD v-tag         AS CHARACTER FORMAT "x(9)"               LABEL "Tag"
    FIELD v-cases       AS INTEGER   FORMAT "->>>,>>9"           LABEL "Units"
    FIELD v-qty-case    AS INTEGER   FORMAT ">>>,>>9"            LABEL "Count"
    FIELD bin           AS CHARACTER FORMAT "x(8)"               LABEL "Bin"          
    FIELD lv-cost-uom   AS CHARACTER FORMAT "x(3)"               LABEL "CUOM"
    FIELD v-rfid#       AS CHARACTER FORMAT "x(10)"              LABEL "RFID"
    FIELD partNo        AS CHARACTER FORMAT "x(12)"              LABEL "Customer Part"
    FIELD dieNo         AS CHARACTER FORMAT "x(15)"              LABEL "Die"          
    FIELD v-numUp       AS INTEGER   FORMAT ">>9"                LABEL "UP"
    FIELD cadNo         AS CHARACTER FORMAT "x(12)"              LABEL "CAD"          
    FIELD plateNo       AS CHARACTER FORMAT "x(12)"              LABEL "Plate"        
    FIELD v-numColors   AS INTEGER   FORMAT ">9"                 LABEL "Num of Colors"
    FIELD v-SheetSize   AS CHARACTER FORMAT "x(15)"              LABEL "Sheet Size"
    FIELD v-Caliper     AS CHARACTER FORMAT "x(7)"               LABEL "Caliper"
    FIELD user-id       AS CHARACTER FORMAT "x(10)"              LABEL "User ID"      
    FIELD loc           AS CHARACTER FORMAT "x(5)"               LABEL "Whse"
    FIELD wt-h          AS DECIMAL   FORMAT ">>,>>9.99"          LABEL "WT/100"
    FIELD rec-time      AS CHARACTER FORMAT "x(5)"               LABEL "Rec Time"
    FIELD postDate      AS DATE      FORMAT "99/99/9999"         LABEL "Posted"       
    FIELD ProdCat       AS CHARACTER FORMAT "x(5)"               LABEL "Catgy"        
    FIELD unt-cst       AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Unit Cost"
    FIELD unt-sel       AS DECIMAL   FORMAT "->>,>>>,>>9.99<<<<" LABEL "Unit Sell"
    FIELD suom          AS CHARACTER FORMAT "x(5)"               LABEL "SUOM"
    FIELD prom-date     AS DATE      FORMAT "99/99/9999"         LABEL "Promise Date"
    FIELD due-date      AS DATE      FORMAT "99/99/9999"         LABEL "Ord Due Date"
    FIELD job-start     AS DATE      FORMAT "99/99/9999"         LABEL "Start Date"
    FIELD shipto        AS CHARACTER FORMAT "x(8)"               LABEL "Ship To"             
    FIELD shipname      AS CHARACTER FORMAT "x(30)"              LABEL "Ship To Name"        
    FIELD order-no      AS INTEGER   FORMAT ">>>>>>9"            LABEL "Order"
    FIELD bef-qty       AS INTEGER   FORMAT "->>>>>>>>9"         LABEL "Before Qty"
    FIELD bin-qty       AS INTEGER   FORMAT "->>>>>>>>9"         LABEL "Bin Change"
    FIELD bol-no        AS INTEGER   FORMAT ">>>>>>9"            LABEL "BOL"
    FIELD Reason        AS CHARACTER FORMAT "x(30)"              LABEL "Reason"            
    FIELD Reason-cd     AS CHARACTER FORMAT "x(2)"               LABEL "Reason Code"       
    FIELD Reason-dscr   AS CHARACTER FORMAT "x(25)"              LABEL "Reason Description"
    FIELD custName      AS CHARACTER FORMAT "x(30)"              LABEL "Customer Name"
    FIELD item-mat-cost AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Item Mat Cost"
    FIELD item-dl-cost  AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Item DL Cost"
    FIELD item-voh-cost AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Item VOH Cost"
    FIELD item-foh-cost AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Item FOH Cost"
    FIELD bin-mat-cost  AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Bin Mat Cost"
    FIELD bin-dl-cost   AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Bin DL Cost"
    FIELD bin-voh-cost  AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Bin VOH Cost"
    FIELD bin-foh-cost  AS DECIMAL   FORMAT "->>>,>>>,>>9.99<<"  LABEL "Bin FOH Cost"
    FIELD weightPerEA   AS DECIMAL   FORMAT "->>>9.9<<<"         LABEL "Weight/Each"
    FIELD qtyInLbs      AS DECIMAL   FORMAT "->>>9.9<<<"         LABEL "Qty in LBS" 
    FIELD qtyInTons     AS DECIMAL   FORMAT "->>>9.9<<<"         LABEL "Qty in Tons"
    FIELD matCost       AS DECIMAL   FORMAT "->>>,>>9.9<<<<"     LABEL "Mat Cost"   
    FIELD prodCost      AS DECIMAL   FORMAT "->>>,>>9.9<<<<"     LABEL "Prod Cost"  
    .
DEFINE TEMP-TABLE ttCostByMachine NO-UNDO
    FIELD dmiID       AS INTEGER   FORMAT ">>9"            LABEL "DMI ID"
    FIELD m-code      AS CHARACTER FORMAT "x(6)"           LABEL "Machine"
    FIELD itemNo      AS CHARACTER FORMAT "x(15)"          LABEL "Item"       
    FIELD itemName    AS CHARACTER FORMAT "x(30)"          LABEL "Description"
    FIELD uom         AS CHARACTER FORMAT "x(5)"           LABEL "UOM"
    FIELD weightPerEA AS DECIMAL   FORMAT "->>>,>>9.9<<<"  LABEL "Weight/Each"
    FIELD qtyInLbs    AS DECIMAL   FORMAT "->>>,>>9.9<<<"  LABEL "Qty" 
    FIELD qtyInTons   AS DECIMAL   FORMAT "->>>,>>9.9<<<"  LABEL "Tons"
    FIELD matCost     AS DECIMAL   FORMAT "->>>,>>9.9<<<<" LABEL "Mat Cost"   
    FIELD prodCost    AS DECIMAL   FORMAT "->>>,>>9.9<<<<" LABEL "Prod Cost"  
    .
DEFINE TEMP-TABLE tt-report NO-UNDO LIKE report
    FIELD rec-id2 AS RECID
    FIELD rptDate AS DATE
    INDEX rec-id2 rec-id2
    .
