/* mfpersist.p */

&SCOPED-DEFINE params ~
DEFINE INPUT  PARAMETER ipMFid AS CHARACTER NO-UNDO. ~
DEFINE INPUT  PARAMETER ipMFvalue AS CHARACTER NO-UNDO. ~
DEFINE INPUT  PARAMETER ipMFreckey AS CHARACTER NO-UNDO. ~
DEFINE OUTPUT PARAMETER opParam AS CHARACTER NO-UNDO. ~
DEFINE OUTPUT PARAMETER opInit AS CHARACTER NO-UNDO.

PROCEDURE mftest1:
  {&params}
  ASSIGN
    opParam = 'Opt 1,Opt 2'
    opInit = 'Opt 2'.
END PROCEDURE.

PROCEDURE mftest2:
END PROCEDURE.

PROCEDURE mftest3:
END PROCEDURE.
