/* est-pf.p - generated 12/09/2005 - 15:42:44 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_est-pf1 NO-UNDO LIKE est-pf.
DEFINE WORK-TABLE ttbl_est-pf2 NO-UNDO LIKE est-pf.

CREATE ttbl_est-pf1.
IMPORT STREAM s_audit_file ttbl_est-pf1.
CREATE ttbl_est-pf2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_est-pf2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_est-pf1.company NE ttbl_est-pf2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_est-pf1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.company NE ttbl_est-pf2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_est-pf2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.e-num NE ttbl_est-pf2.e-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Est.#: " AT 3 ttbl_est-pf1.e-num FORMAT ">>>>>9" " (e-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.e-num NE ttbl_est-pf2.e-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Est.#: " AT 3 ttbl_est-pf2.e-num FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.eqty NE ttbl_est-pf2.eqty OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Qty: " AT 3 ttbl_est-pf1.eqty FORMAT "->>,>>9.99" " (eqty)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.eqty NE ttbl_est-pf2.eqty THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Qty: " AT 3 ttbl_est-pf2.eqty FORMAT "->>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.est-no NE ttbl_est-pf2.est-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 3 ttbl_est-pf1.est-no " (est-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.est-no NE ttbl_est-pf2.est-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 3 ttbl_est-pf2.est-no.
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.fountains NE ttbl_est-pf2.fountains OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Fountain Changes: " AT 3 ttbl_est-pf1.fountains FORMAT "->,>>>,>>9" " (fountains)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.fountains NE ttbl_est-pf2.fountains THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Fountain Changes: " AT 3 ttbl_est-pf2.fountains FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.machine# NE ttbl_est-pf2.machine# OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Machine#: " AT 3 ttbl_est-pf1.machine# FORMAT "->,>>>,>>9" " (machine#)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.machine# NE ttbl_est-pf2.machine# THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Machine#: " AT 3 ttbl_est-pf2.machine# FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.plates NE ttbl_est-pf2.plates OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Plate Changes: " AT 3 ttbl_est-pf1.plates FORMAT "->,>>>,>>9" " (plates)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.plates NE ttbl_est-pf2.plates THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Plate Changes: " AT 3 ttbl_est-pf2.plates FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-pf1.seq# NE ttbl_est-pf2.seq# OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Sequence#: " AT 3 ttbl_est-pf1.seq# FORMAT "->,>>>,>>9" " (seq#)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-pf1.seq# NE ttbl_est-pf2.seq# THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Sequence#: " AT 3 ttbl_est-pf2.seq# FORMAT "->,>>>,>>9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf2.est-no " (est-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf1.est-no " (est-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Qty: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf2.eqty FORMAT "->>,>>9.99" " (eqty)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf1.eqty FORMAT "->>,>>9.99" " (eqty)".
  PUT STREAM s-audit-rpt UNFORMATTED "Machine#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf2.machine# FORMAT "->,>>>,>>9" " (machine#)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf1.machine# FORMAT "->,>>>,>>9" " (machine#)".
  PUT STREAM s-audit-rpt UNFORMATTED "Sequence#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf2.seq# FORMAT "->,>>>,>>9" " (seq#)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-pf1.seq# FORMAT "->,>>>,>>9" " (seq#)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
