/* mach-calendar.p - generated 12/09/2005 - 15:42:48 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_mach-calendar1 NO-UNDO LIKE mach-calendar.
DEFINE WORK-TABLE ttbl_mach-calendar2 NO-UNDO LIKE mach-calendar.

CREATE ttbl_mach-calendar1.
IMPORT STREAM s_audit_file ttbl_mach-calendar1.
CREATE ttbl_mach-calendar2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_mach-calendar2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_mach-calendar1.company NE ttbl_mach-calendar2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_mach-calendar1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.company NE ttbl_mach-calendar2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_mach-calendar2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.day NE ttbl_mach-calendar2.day OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Day: " AT 3 ttbl_mach-calendar1.day FORMAT ">9" " (day)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.day NE ttbl_mach-calendar2.day THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Day: " AT 3 ttbl_mach-calendar2.day FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.end-time NE ttbl_mach-calendar2.end-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "End Time: " AT 3 ttbl_mach-calendar1.end-time FORMAT "->,>>>,>>9" " (end-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.end-time NE ttbl_mach-calendar2.end-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "End Time: " AT 3 ttbl_mach-calendar2.end-time FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.is-run NE ttbl_mach-calendar2.is-run OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Run?: " AT 3 ttbl_mach-calendar1.is-run FORMAT "yes/no" " (is-run)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.is-run NE ttbl_mach-calendar2.is-run THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Run?: " AT 3 ttbl_mach-calendar2.is-run FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.m-code NE ttbl_mach-calendar2.m-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Machine Code: " AT 3 ttbl_mach-calendar1.m-code " (m-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.m-code NE ttbl_mach-calendar2.m-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Machine Code: " AT 3 ttbl_mach-calendar2.m-code.
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.m-date NE ttbl_mach-calendar2.m-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 3 ttbl_mach-calendar1.m-date FORMAT "99/99/9999" " (m-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.m-date NE ttbl_mach-calendar2.m-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 3 ttbl_mach-calendar2.m-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.mon NE ttbl_mach-calendar2.mon OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Month: " AT 3 ttbl_mach-calendar1.mon FORMAT ">9" " (mon)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.mon NE ttbl_mach-calendar2.mon THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Month: " AT 3 ttbl_mach-calendar2.mon FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.seq NE ttbl_mach-calendar2.seq OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Seq#: " AT 3 ttbl_mach-calendar1.seq FORMAT ">>>,>>9" " (seq)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.seq NE ttbl_mach-calendar2.seq THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Seq#: " AT 3 ttbl_mach-calendar2.seq FORMAT ">>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.shift NE ttbl_mach-calendar2.shift OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shift: " AT 3 ttbl_mach-calendar1.shift FORMAT ">9" " (shift)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.shift NE ttbl_mach-calendar2.shift THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shift: " AT 3 ttbl_mach-calendar2.shift FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.start-time NE ttbl_mach-calendar2.start-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Start Time: " AT 3 ttbl_mach-calendar1.start-time FORMAT "->,>>>,>>9" " (start-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.start-time NE ttbl_mach-calendar2.start-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Start Time: " AT 3 ttbl_mach-calendar2.start-time FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.wk NE ttbl_mach-calendar2.wk OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Week: " AT 3 ttbl_mach-calendar1.wk FORMAT ">9" " (wk)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.wk NE ttbl_mach-calendar2.wk THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Week: " AT 3 ttbl_mach-calendar2.wk FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.work-hour NE ttbl_mach-calendar2.work-hour OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Daily Work Hour: " AT 3 ttbl_mach-calendar1.work-hour FORMAT "->,>>>,>>9" " (work-hour)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.work-hour NE ttbl_mach-calendar2.work-hour THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Daily Work Hour: " AT 3 ttbl_mach-calendar2.work-hour FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mach-calendar1.yr NE ttbl_mach-calendar2.yr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Year: " AT 3 ttbl_mach-calendar1.yr FORMAT "9999" " (yr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mach-calendar1.yr NE ttbl_mach-calendar2.yr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Year: " AT 3 ttbl_mach-calendar2.yr FORMAT "9999".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Machine Code: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar2.m-code " (m-code)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar1.m-code " (m-code)".
  PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar2.m-date FORMAT "99/99/9999" " (m-date)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar1.m-date FORMAT "99/99/9999" " (m-date)".
  PUT STREAM s-audit-rpt UNFORMATTED "Seq#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar2.seq FORMAT ">>>,>>9" " (seq)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mach-calendar1.seq FORMAT ">>>,>>9" " (seq)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
