/* findindx.i */

&IF "{&DBFIELD{1}}" NE "" &THEN
&Scoped-define WHEREFIND {&DBFIELD{1}} {&SET{&FINDTYPE}{&DATAYP{1}}}
WHEN "{1}" THEN
DO:
  FIND {&FINDTYPE} {&FIRST-EXTERNAL-TABLE} NO-LOCK
      WHERE {&WHEREFIND}
      &IF "{&WHERE-STATEMENT}" NE "" &THEN
        AND {&WHERE-STATEMENT}
      &ENDIF
      NO-ERROR.
  IF NOT AVAILABLE {&FIRST-EXTERNAL-TABLE} THEN
  RETURN "EMPTY".
END.
&ENDIF

