/* EDSHTran.p - generated 12/09/2005 - 15:42:43 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_EDSHTran1 NO-UNDO LIKE EDSHTran.
DEFINE WORK-TABLE ttbl_EDSHTran2 NO-UNDO LIKE EDSHTran.

CREATE ttbl_EDSHTran1.
IMPORT STREAM s_audit_file ttbl_EDSHTran1.
CREATE ttbl_EDSHTran2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_EDSHTran2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_EDSHTran1.BOL-Adddate NE ttbl_EDSHTran2.BOL-Adddate OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.BOL-Adddate FORMAT "99/99/9999" " (BOL-Adddate)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.BOL-Adddate NE ttbl_EDSHTran2.BOL-Adddate THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.BOL-Adddate FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.BOL-Addtime NE ttbl_EDSHTran2.BOL-Addtime OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.BOL-Addtime FORMAT ">>>>9" " (BOL-Addtime)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.BOL-Addtime NE ttbl_EDSHTran2.BOL-Addtime THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.BOL-Addtime FORMAT ">>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.BOL-No NE ttbl_EDSHTran2.BOL-No OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.BOL-No " (BOL-No)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.BOL-No NE ttbl_EDSHTran2.BOL-No THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.BOL-No.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Carrier NE ttbl_EDSHTran2.Carrier OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Carrier " (Carrier)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Carrier NE ttbl_EDSHTran2.Carrier THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Carrier.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Carrier-code NE ttbl_EDSHTran2.Carrier-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Carrier-code " (Carrier-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Carrier-code NE ttbl_EDSHTran2.Carrier-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Carrier-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Del-date NE ttbl_EDSHTran2.Del-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Del-date FORMAT "99/99/9999" " (Del-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Del-date NE ttbl_EDSHTran2.Del-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Del-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Del-date-qual NE ttbl_EDSHTran2.Del-date-qual OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Del-date-qual " (Del-date-qual)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Del-date-qual NE ttbl_EDSHTran2.Del-date-qual THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Del-date-qual.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Equipment-code NE ttbl_EDSHTran2.Equipment-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Equipment-code " (Equipment-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Equipment-code NE ttbl_EDSHTran2.Equipment-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Equipment-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Equipment-initial NE ttbl_EDSHTran2.Equipment-initial OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Equipment-initial " (Equipment-initial)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Equipment-initial NE ttbl_EDSHTran2.Equipment-initial THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Equipment-initial.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Lines NE ttbl_EDSHTran2.Lines OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Lines FORMAT ">>9" " (Lines)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Lines NE ttbl_EDSHTran2.Lines THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Lines FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Package-Code NE ttbl_EDSHTran2.Package-Code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Package-Code " (Package-Code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Package-Code NE ttbl_EDSHTran2.Package-Code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Package-Code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Partner NE ttbl_EDSHTran2.Partner OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Partner " (Partner)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Partner NE ttbl_EDSHTran2.Partner THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Partner.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Pro-Number NE ttbl_EDSHTran2.Pro-Number OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Pro-Number " (Pro-Number)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Pro-Number NE ttbl_EDSHTran2.Pro-Number THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Pro-Number.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Purpose-code NE ttbl_EDSHTran2.Purpose-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Purpose: " AT 3 ttbl_EDSHTran1.Purpose-code " (Purpose-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Purpose-code NE ttbl_EDSHTran2.Purpose-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Purpose: " AT 3 ttbl_EDSHTran2.Purpose-code.
  END.
END.
DO i = 1 TO 4:
IF NOT v_field_changed OR ttbl_EDSHTran1.Routing[i] NE ttbl_EDSHTran2.Routing[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_EDSHTran1.Routing[i] " (Routing[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Routing[i] NE ttbl_EDSHTran2.Routing[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_EDSHTran2.Routing[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Seq NE ttbl_EDSHTran2.Seq OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Seq FORMAT ">>>>>>9" " (Seq)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Seq NE ttbl_EDSHTran2.Seq THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Seq FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Sf-code NE ttbl_EDSHTran2.Sf-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Sf-code " (Sf-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Sf-code NE ttbl_EDSHTran2.Sf-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Sf-code.
  END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-address[i] NE ttbl_EDSHTran2.Ship-address[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Address[" AT 3 i "]: " ttbl_EDSHTran1.Ship-address[i] " (Ship-address[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-address[i] NE ttbl_EDSHTran2.Ship-address[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Address[" AT 3 i "]: " ttbl_EDSHTran2.Ship-address[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-city NE ttbl_EDSHTran2.Ship-city OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "City: " AT 3 ttbl_EDSHTran1.Ship-city " (Ship-city)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-city NE ttbl_EDSHTran2.Ship-city THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "City: " AT 3 ttbl_EDSHTran2.Ship-city.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-country NE ttbl_EDSHTran2.Ship-country OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Country: " AT 3 ttbl_EDSHTran1.Ship-country " (Ship-country)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-country NE ttbl_EDSHTran2.Ship-country THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Country: " AT 3 ttbl_EDSHTran2.Ship-country.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-Date NE ttbl_EDSHTran2.Ship-Date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-Date FORMAT "99/99/9999" " (Ship-Date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-Date NE ttbl_EDSHTran2.Ship-Date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-Date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-date-code NE ttbl_EDSHTran2.Ship-date-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-date-code " (Ship-date-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-date-code NE ttbl_EDSHTran2.Ship-date-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-date-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-loc-code NE ttbl_EDSHTran2.Ship-loc-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-loc-code " (Ship-loc-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-loc-code NE ttbl_EDSHTran2.Ship-loc-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-loc-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-method-code NE ttbl_EDSHTran2.Ship-method-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-method-code " (Ship-method-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-method-code NE ttbl_EDSHTran2.Ship-method-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-method-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-name NE ttbl_EDSHTran2.Ship-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-name " (Ship-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-name NE ttbl_EDSHTran2.Ship-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-name.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-pay-code NE ttbl_EDSHTran2.Ship-pay-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-pay-code " (Ship-pay-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-pay-code NE ttbl_EDSHTran2.Ship-pay-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-pay-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-st NE ttbl_EDSHTran2.Ship-st OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "St: " AT 3 ttbl_EDSHTran1.Ship-st " (Ship-st)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-st NE ttbl_EDSHTran2.Ship-st THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "St: " AT 3 ttbl_EDSHTran2.Ship-st.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-Stat NE ttbl_EDSHTran2.Ship-Stat OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-Stat " (Ship-Stat)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-Stat NE ttbl_EDSHTran2.Ship-Stat THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-Stat.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-time NE ttbl_EDSHTran2.Ship-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-time FORMAT "9999" " (Ship-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-time NE ttbl_EDSHTran2.Ship-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-time FORMAT "9999".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-time-zone NE ttbl_EDSHTran2.Ship-time-zone OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Ship-time-zone " (Ship-time-zone)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-time-zone NE ttbl_EDSHTran2.Ship-time-zone THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Ship-time-zone.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Ship-zip NE ttbl_EDSHTran2.Ship-zip OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Zip-code: " AT 3 ttbl_EDSHTran1.Ship-zip " (Ship-zip)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Ship-zip NE ttbl_EDSHTran2.Ship-zip THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Zip-code: " AT 3 ttbl_EDSHTran2.Ship-zip.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.St-code NE ttbl_EDSHTran2.St-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.St-code " (St-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.St-code NE ttbl_EDSHTran2.St-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.St-code.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Tot-cartons NE ttbl_EDSHTran2.Tot-cartons OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Tot-cartons FORMAT "->>>>>>9" " (Tot-cartons)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Tot-cartons NE ttbl_EDSHTran2.Tot-cartons THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Tot-cartons FORMAT "->>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Tot-volume NE ttbl_EDSHTran2.Tot-volume OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Tot-volume FORMAT "->>>>>>9" " (Tot-volume)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Tot-volume NE ttbl_EDSHTran2.Tot-volume THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Tot-volume FORMAT "->>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Tot-wght NE ttbl_EDSHTran2.Tot-wght OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Tot-wght FORMAT ">>>>>>>9" " (Tot-wght)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Tot-wght NE ttbl_EDSHTran2.Tot-wght THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Tot-wght FORMAT ">>>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Trailer-Number NE ttbl_EDSHTran2.Trailer-Number OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Trailer-Number " (Trailer-Number)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Trailer-Number NE ttbl_EDSHTran2.Trailer-Number THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Trailer-Number.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Transit-time NE ttbl_EDSHTran2.Transit-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Transit-time FORMAT "9999" " (Transit-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Transit-time NE ttbl_EDSHTran2.Transit-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Transit-time FORMAT "9999".
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Transit-time-qual NE ttbl_EDSHTran2.Transit-time-qual OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Transit-time-qual " (Transit-time-qual)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Transit-time-qual NE ttbl_EDSHTran2.Transit-time-qual THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Transit-time-qual.
  END.
END.
IF NOT v_field_changed OR ttbl_EDSHTran1.Vn-code NE ttbl_EDSHTran2.Vn-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran1.Vn-code " (Vn-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_EDSHTran1.Vn-code NE ttbl_EDSHTran2.Vn-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_EDSHTran2.Vn-code.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_EDSHTran2.Partner " (Partner)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_EDSHTran1.Partner " (Partner)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_EDSHTran2.Seq FORMAT ">>>>>>9" " (Seq)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_EDSHTran1.Seq FORMAT ">>>>>>9" " (Seq)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
