/* usercomp.p - generated 12/09/2005 - 15:42:55 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_usercomp1 NO-UNDO LIKE usercomp.
DEFINE WORK-TABLE ttbl_usercomp2 NO-UNDO LIKE usercomp.

CREATE ttbl_usercomp1.
IMPORT STREAM s_audit_file ttbl_usercomp1.
CREATE ttbl_usercomp2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_usercomp2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_usercomp1.company NE ttbl_usercomp2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_usercomp1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_usercomp1.company NE ttbl_usercomp2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_usercomp2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_usercomp1.company_default NE ttbl_usercomp2.company_default OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company Default: " AT 3 ttbl_usercomp1.company_default FORMAT "yes/no" " (company_default)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_usercomp1.company_default NE ttbl_usercomp2.company_default THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company Default: " AT 3 ttbl_usercomp2.company_default FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_usercomp1.loc NE ttbl_usercomp2.loc OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Location: " AT 3 ttbl_usercomp1.loc " (loc)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_usercomp1.loc NE ttbl_usercomp2.loc THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Location: " AT 3 ttbl_usercomp2.loc.
  END.
END.
IF NOT v_field_changed OR ttbl_usercomp1.loc_default NE ttbl_usercomp2.loc_default OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Location Default: " AT 3 ttbl_usercomp1.loc_default FORMAT "yes/no" " (loc_default)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_usercomp1.loc_default NE ttbl_usercomp2.loc_default THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Location Default: " AT 3 ttbl_usercomp2.loc_default FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_usercomp1.user_id NE ttbl_usercomp2.user_id OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 3 ttbl_usercomp1.user_id " (user_id)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_usercomp1.user_id NE ttbl_usercomp2.user_id THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 3 ttbl_usercomp2.user_id.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_usercomp2.user_id " (user_id)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_usercomp1.user_id " (user_id)".
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_usercomp2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_usercomp1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Location: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_usercomp2.loc " (loc)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_usercomp1.loc " (loc)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
