/* po-ord.p - generated 12/09/2005 - 15:42:51 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_po-ord1 NO-UNDO LIKE po-ord.
DEFINE WORK-TABLE ttbl_po-ord2 NO-UNDO LIKE po-ord.

CREATE ttbl_po-ord1.
IMPORT STREAM s_audit_file ttbl_po-ord1.
CREATE ttbl_po-ord2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_po-ord2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_po-ord1.acknowledge NE ttbl_po-ord2.acknowledge OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Acknowledgement: " AT 3 ttbl_po-ord1.acknowledge FORMAT "yes/no" " (acknowledge)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.acknowledge NE ttbl_po-ord2.acknowledge THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Acknowledgement: " AT 3 ttbl_po-ord2.acknowledge FORMAT "yes/no".
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_po-ord1.addr[i] NE ttbl_po-ord2.addr[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Ship To Address[" AT 3 i "]: " ttbl_po-ord1.addr[i] " (addr[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.addr[i] NE ttbl_po-ord2.addr[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Ship To Address[" AT 3 i "]: " ttbl_po-ord2.addr[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.bill-to NE ttbl_po-ord2.bill-to OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bill to: " AT 3 ttbl_po-ord1.bill-to " (bill-to)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.bill-to NE ttbl_po-ord2.bill-to THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bill to: " AT 3 ttbl_po-ord2.bill-to.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.buyer NE ttbl_po-ord2.buyer OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Buyer: " AT 3 ttbl_po-ord1.buyer " (buyer)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.buyer NE ttbl_po-ord2.buyer THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Buyer: " AT 3 ttbl_po-ord2.buyer.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.carrier NE ttbl_po-ord2.carrier OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shipping Carrier: " AT 3 ttbl_po-ord1.carrier " (carrier)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.carrier NE ttbl_po-ord2.carrier THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shipping Carrier: " AT 3 ttbl_po-ord2.carrier.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.city NE ttbl_po-ord2.city OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "City: " AT 3 ttbl_po-ord1.city " (city)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.city NE ttbl_po-ord2.city THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "City: " AT 3 ttbl_po-ord2.city.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.company NE ttbl_po-ord2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_po-ord1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.company NE ttbl_po-ord2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_po-ord2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.contact NE ttbl_po-ord2.contact OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Contact: " AT 3 ttbl_po-ord1.contact " (contact)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.contact NE ttbl_po-ord2.contact THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Contact: " AT 3 ttbl_po-ord2.contact.
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_po-ord1.curr-code[i] NE ttbl_po-ord2.curr-code[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Currency Code[" AT 3 i "]: " ttbl_po-ord1.curr-code[i] " (curr-code[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.curr-code[i] NE ttbl_po-ord2.curr-code[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Currency Code[" AT 3 i "]: " ttbl_po-ord2.curr-code[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.cust-no NE ttbl_po-ord2.cust-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Customer Number: " AT 3 ttbl_po-ord1.cust-no " (cust-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.cust-no NE ttbl_po-ord2.cust-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Customer Number: " AT 3 ttbl_po-ord2.cust-no.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.deleted NE ttbl_po-ord2.deleted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Deleted?: " AT 3 ttbl_po-ord1.deleted FORMAT "Y/N" " (deleted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.deleted NE ttbl_po-ord2.deleted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Deleted?: " AT 3 ttbl_po-ord2.deleted FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.due-date NE ttbl_po-ord2.due-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Required Date: " AT 3 ttbl_po-ord1.due-date FORMAT "99/99/9999" " (due-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.due-date NE ttbl_po-ord2.due-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Required Date: " AT 3 ttbl_po-ord2.due-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ex-rate NE ttbl_po-ord2.ex-rate OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_po-ord1.ex-rate FORMAT "->>,>>9.99<<<<<" " (ex-rate)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ex-rate NE ttbl_po-ord2.ex-rate THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_po-ord2.ex-rate FORMAT "->>,>>9.99<<<<<".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.fob-code NE ttbl_po-ord2.fob-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "FOB Origin/Dest: " AT 3 ttbl_po-ord1.fob-code " (fob-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.fob-code NE ttbl_po-ord2.fob-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "FOB Origin/Dest: " AT 3 ttbl_po-ord2.fob-code.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.frt-pay NE ttbl_po-ord2.frt-pay OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Freight Payment: " AT 3 ttbl_po-ord1.frt-pay " (frt-pay)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.frt-pay NE ttbl_po-ord2.frt-pay THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Freight Payment: " AT 3 ttbl_po-ord2.frt-pay.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.last-ship-date NE ttbl_po-ord2.last-ship-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Last Ship Date: " AT 3 ttbl_po-ord1.last-ship-date FORMAT "99/99/9999" " (last-ship-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.last-ship-date NE ttbl_po-ord2.last-ship-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Last Ship Date: " AT 3 ttbl_po-ord2.last-ship-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.loc NE ttbl_po-ord2.loc OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Whse: " AT 3 ttbl_po-ord1.loc " (loc)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.loc NE ttbl_po-ord2.loc THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Whse: " AT 3 ttbl_po-ord2.loc.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.opened NE ttbl_po-ord2.opened OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_po-ord1.opened FORMAT "Open/Closed" " (opened)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.opened NE ttbl_po-ord2.opened THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_po-ord2.opened FORMAT "Open/Closed".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.over-pct NE ttbl_po-ord2.over-pct OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Overrun %: " AT 3 ttbl_po-ord1.over-pct FORMAT ">>9.99%" " (over-pct)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.over-pct NE ttbl_po-ord2.over-pct THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Overrun %: " AT 3 ttbl_po-ord2.over-pct FORMAT ">>9.99%".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.po-change-date NE ttbl_po-ord2.po-change-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Date Changed: " AT 3 ttbl_po-ord1.po-change-date FORMAT "99/99/9999" " (po-change-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.po-change-date NE ttbl_po-ord2.po-change-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Date Changed: " AT 3 ttbl_po-ord2.po-change-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.po-date NE ttbl_po-ord2.po-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "PO Date: " AT 3 ttbl_po-ord1.po-date FORMAT "99/99/9999" " (po-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.po-date NE ttbl_po-ord2.po-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "PO Date: " AT 3 ttbl_po-ord2.po-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.po-no NE ttbl_po-ord2.po-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "PO Number: " AT 3 ttbl_po-ord1.po-no FORMAT ">>>>>9" " (po-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.po-no NE ttbl_po-ord2.po-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "PO Number: " AT 3 ttbl_po-ord2.po-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.printed NE ttbl_po-ord2.printed OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Printed?: " AT 3 ttbl_po-ord1.printed FORMAT "Y/N" " (printed)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.printed NE ttbl_po-ord2.printed THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Printed?: " AT 3 ttbl_po-ord2.printed FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.received NE ttbl_po-ord2.received OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Received: " AT 3 ttbl_po-ord1.received FORMAT "y/n" " (received)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.received NE ttbl_po-ord2.received THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Received: " AT 3 ttbl_po-ord2.received FORMAT "y/n".
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_po-ord1.ship-addr[i] NE ttbl_po-ord2.ship-addr[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shipping Address[" AT 3 i "]: " ttbl_po-ord1.ship-addr[i] " (ship-addr[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-addr[i] NE ttbl_po-ord2.ship-addr[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shipping Address[" AT 3 i "]: " ttbl_po-ord2.ship-addr[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ship-city NE ttbl_po-ord2.ship-city OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shipping City: " AT 3 ttbl_po-ord1.ship-city " (ship-city)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-city NE ttbl_po-ord2.ship-city THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shipping City: " AT 3 ttbl_po-ord2.ship-city.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ship-id NE ttbl_po-ord2.ship-id OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Ship To: " AT 3 ttbl_po-ord1.ship-id " (ship-id)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-id NE ttbl_po-ord2.ship-id THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Ship To: " AT 3 ttbl_po-ord2.ship-id.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ship-name NE ttbl_po-ord2.ship-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shipping Name: " AT 3 ttbl_po-ord1.ship-name " (ship-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-name NE ttbl_po-ord2.ship-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shipping Name: " AT 3 ttbl_po-ord2.ship-name.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ship-no NE ttbl_po-ord2.ship-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Ship To Number: " AT 3 ttbl_po-ord1.ship-no FORMAT ">>9" " (ship-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-no NE ttbl_po-ord2.ship-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Ship To Number: " AT 3 ttbl_po-ord2.ship-no FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ship-state NE ttbl_po-ord2.ship-state OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shipping State: " AT 3 ttbl_po-ord1.ship-state " (ship-state)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-state NE ttbl_po-ord2.ship-state THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shipping State: " AT 3 ttbl_po-ord2.ship-state.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.ship-zip NE ttbl_po-ord2.ship-zip OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shipping Zip: " AT 3 ttbl_po-ord1.ship-zip " (ship-zip)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.ship-zip NE ttbl_po-ord2.ship-zip THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shipping Zip: " AT 3 ttbl_po-ord2.ship-zip.
  END.
END.
DO i = 1 TO 4:
IF NOT v_field_changed OR ttbl_po-ord1.spec-i[i] NE ttbl_po-ord2.spec-i[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Special Instructions[" AT 3 i "]: " ttbl_po-ord1.spec-i[i] " (spec-i[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.spec-i[i] NE ttbl_po-ord2.spec-i[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Special Instructions[" AT 3 i "]: " ttbl_po-ord2.spec-i[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.stat NE ttbl_po-ord2.stat OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Status: " AT 3 ttbl_po-ord1.stat " (stat)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.stat NE ttbl_po-ord2.stat THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Status: " AT 3 ttbl_po-ord2.stat.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.state NE ttbl_po-ord2.state OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "State: " AT 3 ttbl_po-ord1.state " (state)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.state NE ttbl_po-ord2.state THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "State: " AT 3 ttbl_po-ord2.state.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.t-cost NE ttbl_po-ord2.t-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Total Cost: " AT 3 ttbl_po-ord1.t-cost FORMAT "->,>>>,>>9.99<<" " (t-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.t-cost NE ttbl_po-ord2.t-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Total Cost: " AT 3 ttbl_po-ord2.t-cost FORMAT "->,>>>,>>9.99<<".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.t-freight NE ttbl_po-ord2.t-freight OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Total Freight: " AT 3 ttbl_po-ord1.t-freight FORMAT "->>,>>9.99" " (t-freight)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.t-freight NE ttbl_po-ord2.t-freight THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Total Freight: " AT 3 ttbl_po-ord2.t-freight FORMAT "->>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.tax NE ttbl_po-ord2.tax OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Tax: " AT 3 ttbl_po-ord1.tax FORMAT "->,>>9.99" " (tax)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.tax NE ttbl_po-ord2.tax THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Tax: " AT 3 ttbl_po-ord2.tax FORMAT "->,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.tax-gr NE ttbl_po-ord2.tax-gr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Sales Tax Group: " AT 3 ttbl_po-ord1.tax-gr " (tax-gr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.tax-gr NE ttbl_po-ord2.tax-gr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Sales Tax Group: " AT 3 ttbl_po-ord2.tax-gr.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.tax-id NE ttbl_po-ord2.tax-id OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Tax Exempt No.: " AT 3 ttbl_po-ord1.tax-id " (tax-id)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.tax-id NE ttbl_po-ord2.tax-id THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Tax Exempt No.: " AT 3 ttbl_po-ord2.tax-id.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.terms NE ttbl_po-ord2.terms OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Payment Terms: " AT 3 ttbl_po-ord1.terms " (terms)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.terms NE ttbl_po-ord2.terms THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Payment Terms: " AT 3 ttbl_po-ord2.terms.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.type NE ttbl_po-ord2.type OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 3 ttbl_po-ord1.type " (type)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.type NE ttbl_po-ord2.type THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 3 ttbl_po-ord2.type.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.under-pct NE ttbl_po-ord2.under-pct OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Underrun %: " AT 3 ttbl_po-ord1.under-pct FORMAT ">>9.99%" " (under-pct)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.under-pct NE ttbl_po-ord2.under-pct THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Underrun %: " AT 3 ttbl_po-ord2.under-pct FORMAT ">>9.99%".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.upd-date NE ttbl_po-ord2.upd-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Updated Date: " AT 3 ttbl_po-ord1.upd-date FORMAT "99/99/9999" " (upd-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.upd-date NE ttbl_po-ord2.upd-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Updated Date: " AT 3 ttbl_po-ord2.upd-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.upd-time NE ttbl_po-ord2.upd-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Updated Time: " AT 3 ttbl_po-ord1.upd-time FORMAT "->,>>>,>>9" " (upd-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.upd-time NE ttbl_po-ord2.upd-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Updated Time: " AT 3 ttbl_po-ord2.upd-time FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.vend-no NE ttbl_po-ord2.vend-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Vendor: " AT 3 ttbl_po-ord1.vend-no " (vend-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.vend-no NE ttbl_po-ord2.vend-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Vendor: " AT 3 ttbl_po-ord2.vend-no.
  END.
END.
IF NOT v_field_changed OR ttbl_po-ord1.zip NE ttbl_po-ord2.zip OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Zip Code: " AT 3 ttbl_po-ord1.zip " (zip)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_po-ord1.zip NE ttbl_po-ord2.zip THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Zip Code: " AT 3 ttbl_po-ord2.zip.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_po-ord2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_po-ord1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "PO Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_po-ord2.po-no FORMAT ">>>>>9" " (po-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_po-ord1.po-no FORMAT ">>>>>9" " (po-no)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
