/* invStart.p */

DEFINE INPUT PARAMETER cStartup AS CHARACTER NO-UNDO .

DEFINE VARIABLE hProc AS HANDLE NO-UNDO .

RUN Inventory\invBin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN Inventory\invIM.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN Inventory\invMTG.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN Inventory\invMTM.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN Inventory\invRG.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN Inventory\invRM.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN Inventory\invSG.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

OUTPUT TO 'invStart.log' APPEND.
PUT UNFORMATTED '[' REPLACE(STRING(NOW),' ','@') '] Inventory' SKIP.
OUTPUT CLOSE.
