/* aoaStart.p */

DEFINE INPUT PARAMETER cStartup AS CHARACTER NO-UNDO .

DEFINE VARIABLE hProc AS HANDLE NO-UNDO .

RUN aoa\appServer\aoaBin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaAdmin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaAP.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaAR.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaDC.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaEQ.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaFG.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaGL.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaHS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaJC.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaOE.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaPO.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaRM.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaSB.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaTS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

OUTPUT TO 'aoaStart.log' APPEND.
PUT UNFORMATTED '[' REPLACE(STRING(NOW),' ','@') '] AdvantzwareOA' SKIP.
OUTPUT CLOSE.
