/* attribs.i */

IF {&SELF-NAME}:PRIVATE-DATA IN FRAME {&FRAME-NAME} = ? THEN
{&SELF-NAME}:PRIVATE-DATA IN FRAME {&FRAME-NAME} = "save".

IF {&SELF-NAME}:BGCOLOR IN FRAME {&FRAME-NAME} = ? THEN
{&SELF-NAME}:BGCOLOR IN FRAME {&FRAME-NAME} = 15.

IF {&SELF-NAME}:FONT IN FRAME {&FRAME-NAME} = ? THEN
{&SELF-NAME}:FONT IN FRAME {&FRAME-NAME} = 2.
