/* dynParamValueDefs.i - rstark - 1.15.2020 */

DEFINE VARIABLE cLookupField  AS CHARACTER NO-UNDO.
DEFINE VARIABLE cParamList    AS CHARACTER NO-UNDO.
DEFINE VARIABLE cParamValue   AS CHARACTER NO-UNDO.
DEFINE VARIABLE cReturnFields AS CHARACTER NO-UNDO.
DEFINE VARIABLE iSubjectID    AS INTEGER   NO-UNDO.
DEFINE VARIABLE rRecID        AS RECID     NO-UNDO.
