DEF NEW GLOBAL SHARED VAR v-ap-entity AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR v-ar-entity AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR v-fa-entity AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR v-gl-entity AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR v-in-entity AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR condition AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR init-val AS CHAR EXTENT 250 NO-UNDO.
DEF NEW GLOBAL SHARED VAR terminalid  AS CHAR NO-UNDO.

DEF NEW GLOBAL SHARED VAR account-no AS CHAR.
DEF NEW GLOBAL SHARED VAR bank-id# AS CHAR.
DEF NEW GLOBAL SHARED VAR clRowid AS ROWID.
DEF NEW GLOBAL SHARED VAR ff-codes-rowid AS ROWID.
DEF NEW GLOBAL SHARED VAR from-date# AS DATE.
DEF NEW GLOBAL SHARED VAR funct-rowid AS ROWID.
DEF NEW GLOBAL SHARED VAR functionname AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR hrecno AS ROWID NO-UNDO.
DEF NEW GLOBAL SHARED VAR input-st LIKE state.st.
DEF NEW GLOBAL SHARED VAR inv-jrnl-rowid AS ROWID.
DEF NEW GLOBAL SHARED VAR inZoom AS LOG NO-UNDO.
DEF NEW GLOBAL SHARED VAR item-whs-rowid AS ROWID.
DEF NEW GLOBAL SHARED VAR pm-associated AS CHAR.
DEF NEW GLOBAL SHARED VAR pm-header-rowid AS ROWID.
DEF NEW GLOBAL SHARED VAR ProcHead-rowid AS rowid.
DEF NEW GLOBAL SHARED VAR result AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR serial-rowid AS ROWID.
DEF NEW GLOBAL SHARED VAR svc-terr-rowid AS ROWID.    
DEF NEW GLOBAL SHARED VAR tech-rowid AS ROWID.    
DEF NEW GLOBAL SHARED VAR to-date# AS DATE.
DEF NEW GLOBAL SHARED VAR wca-cust-no LIKE contract.cust-no NO-UNDO.
DEF NEW GLOBAL SHARED VAR wca-record-type LIKE contract.record-type NO-UNDO.
DEF NEW GLOBAL SHARED VAR wcust-no LIKE customer.cust-no NO-UNDO.
DEF NEW GLOBAL SHARED VAR wfilename AS CHAR.
DEF NEW GLOBAL SHARED VAR wkeylist AS CHAR.
DEF NEW GLOBAL SHARED VAR wmemo-code LIKE memo.memo-code NO-UNDO.
DEF NEW GLOBAL SHARED VAR wmemo-source LIKE memo.memo-source NO-UNDO.
DEF NEW GLOBAL SHARED VAR wse-item-no AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR wse-serial-no AS CHAR NO-UNDO.
DEF NEW GLOBAL SHARED VAR wso-service-no LIKE service.service-no NO-UNDO.
DEF NEW GLOBAL SHARED VAR wtrans-code LIKE ar-open-tr.trans-code NO-UNDO.
DEF NEW GLOBAL SHARED VAR xfocus# AS WIDGET-HANDLE NO-UNDO.

