IF AVAILABLE({1}) THEN DO WITH FRAME {3}:
    COLOR DISPLAY VALUE(C_LKUP) {1}.{2} WITH FRAME {3}.
    DISPLAY {1}.{2} WITH FRAME {3}. END.
ELSE DO WITH FRAME {3}:
    BELL. COLOR DISPLAY VALUE(C_ERR) {1}.{2} WITH FRAME {3}.
    DISPLAY '*Not in {1}*' @ {1}.{2} WITH FRAME {3}. END.
