DEFINE INPUT-OUTPUT PARAMETER PRINTSTRING AS CHARACTER  NO-UNDO.
DEFINE INPUT        PARAMETER VMI_UNITS   AS INTEGER    NO-UNDO.
DEFINE INPUT        PARAMETER VMI_TYPE    AS CHARACTER  NO-UNDO.
{rc/prtcvt.i printstring vmi_units vmi_type}
