find first ar-inv where
     ar-inv.company eq "001" and
     ar-inv.inv-no eq 380
     no-lock.
     
create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 390
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 2
       ar-invl.i-no = "CALLPRO0004A99"
       ar-invl.i-name = "CB14"
       ar-invl.part-no = "CB14"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 400
       ar-invl.inv-qty = 400
       ar-invl.qty = 400
       ar-invl.unit-pr = 1174
       ar-invl.pr-uom = "M"
       ar-invl.amt = 469.60  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .
            
create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 393
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 3
       ar-invl.i-no = "CALLPRO0005A99"
       ar-invl.i-name = "CB05"
       ar-invl.part-no = "CB05"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 200
       ar-invl.inv-qty = 200
       ar-invl.qty = 200
       ar-invl.unit-pr = 819
       ar-invl.pr-uom = "M"
       ar-invl.amt = 163.80  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M".

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 393
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 4
       ar-invl.i-no = "CALLPRO0006A99"
       ar-invl.i-name = "S10X19"
       ar-invl.part-no = "S10X19"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 1600
       ar-invl.inv-qty = 1600
       ar-invl.qty = 1600
       ar-invl.unit-pr = 163
       ar-invl.pr-uom = "M"
       ar-invl.amt = 260.80  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M".

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 389
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 850    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 5
       ar-invl.i-no = "FALLPRO0001A99"
       ar-invl.i-name = "AM906"
       ar-invl.part-no = "AM906"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 205
       ar-invl.inv-qty = 205
       ar-invl.qty = 200
       ar-invl.unit-pr = 1184
       ar-invl.pr-uom = "M"
       ar-invl.amt = 242.72  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 389
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 850    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 6
       ar-invl.i-no = "FALLPRO0002A99"
       ar-invl.i-name = "15 3/4 X 13 1/2 X 17"
       ar-invl.part-no = "CN1517"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 330
       ar-invl.inv-qty = 330
       ar-invl.qty = 300
       ar-invl.unit-pr = 1570
       ar-invl.pr-uom = "M"
       ar-invl.amt = 518.10  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 389
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 7
       ar-invl.i-no = "FALLPRO0007A99"
       ar-invl.i-name = "AM907"
       ar-invl.part-no = "AM907"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 400
       ar-invl.inv-qty = 400
       ar-invl.qty = 200
       ar-invl.unit-pr = 1355
       ar-invl.pr-uom = "M"
       ar-invl.amt = 542  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 393
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 8
       ar-invl.i-no = "FALLPRO0008A99"
       ar-invl.i-name = "CN141"
       ar-invl.part-no = "CN141"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 110
       ar-invl.inv-qty = 110
       ar-invl.qty = 100
       ar-invl.unit-pr = 1027
       ar-invl.pr-uom = "M"
       ar-invl.amt = 112.97  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .
  
create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 393
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 9
       ar-invl.i-no = "FALLPRO0009A99"
       ar-invl.i-name = "CN818"
       ar-invl.part-no = "CN818"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 200
       ar-invl.inv-qty = 200
       ar-invl.qty = 200
       ar-invl.unit-pr = 889
       ar-invl.pr-uom = "M"
       ar-invl.amt = 177.80  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 393
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 717    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 10
       ar-invl.i-no = "FALLPRO0010A99"
       ar-invl.i-name = "CSK09"
       ar-invl.part-no = "CSK09"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 920
       ar-invl.inv-qty = 920
       ar-invl.qty = 1000
       ar-invl.unit-pr = 1126
       ar-invl.pr-uom = "M"
       ar-invl.amt = 1035.92  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 389
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 850    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 11
       ar-invl.i-no = "FALLPRO0011A99"
       ar-invl.i-name = "CN550"
       ar-invl.part-no = "CN550"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 202
       ar-invl.inv-qty = 202
       ar-invl.qty = 200
       ar-invl.unit-pr = 1331
       ar-invl.pr-uom = "M"
       ar-invl.amt = 268.86  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 389
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 850    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 12
       ar-invl.i-no = "FALLPRO0012A99"
       ar-invl.i-name = "CN580"
       ar-invl.part-no = "CN580"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 205
       ar-invl.inv-qty = 205
       ar-invl.qty = 200
       ar-invl.unit-pr = 864
       ar-invl.pr-uom = "M"
       ar-invl.amt = 177.12  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 392
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 840    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 13
       ar-invl.i-no = "SB15 NEW"
       ar-invl.i-name = "SB15 NEW"
       ar-invl.part-no = "SB15 NEW"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 300
       ar-invl.inv-qty = 300
       ar-invl.qty = 600
       ar-invl.unit-pr = 740
       ar-invl.pr-uom = "M"
       ar-invl.amt = 222  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 392
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 840    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 14
       ar-invl.i-no = "SB30 NEW"
       ar-invl.i-name = "SB30 NEW"
       ar-invl.part-no = "SB30 NEW"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 1200
       ar-invl.inv-qty = 1200
       ar-invl.qty = 1000
       ar-invl.unit-pr = 833
       ar-invl.pr-uom = "M"
       ar-invl.amt = 999.6  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 390
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 840    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 15
       ar-invl.i-no = "SB62"
       ar-invl.i-name = "SB62"
       ar-invl.part-no = "SB62"
       ar-invl.part-dscr1 = "SB62"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 7242
       ar-invl.inv-qty = 7242
       ar-invl.qty = 6600
       ar-invl.unit-pr = 277
       ar-invl.pr-uom = "M"
       ar-invl.amt = 2006.03  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .

create ar-invl.
assign ar-invl.company = "001"
       ar-invl.inv-no = 380
       ar-invl.bol-no = 392
       ar-invl.x-no = ar-inv.x-no
       ar-invl.ord-no = 840    
       ar-invl.actnum = "01-300-0000"           
       ar-invl.cust-no = "RAYPOW"
       ar-invl.line = 16
       ar-invl.i-no = "SHB77"
       ar-invl.i-name = "SHB77"
       ar-invl.part-no = "SHB77"
       /*ar-invl.po-no = "5832"*/
       ar-invl.ship-qty = 2257
       ar-invl.inv-qty = 2257
       ar-invl.qty = 1800
       ar-invl.unit-pr = 186
       ar-invl.pr-uom = "M"
       ar-invl.amt = 419.80  
       ar-invl.sman[1] = "003"         
       ar-invl.s-pct[1] = 100
       ar-invl.misc = no
       ar-invl.posted = yes
       ar-invl.sname[1] = "Rick Tipmore"
       ar-invl.pr-qty-uom = "M" .
