/* shftdefs.i */

DEFINE VARIABLE shiftvar AS CHARACTER NO-UNDO.
DEFINE VARIABLE starttime AS INTEGER NO-UNDO.
DEFINE VARIABLE endtime AS INTEGER NO-UNDO.
DEFINE VARIABLE stoptime AS INTEGER NO-UNDO.
DEFINE VARIABLE missingshift AS CHARACTER NO-UNDO.
