copy z:\asi_gui9\pco400\addon\auditprg\cmpltjob.r z:\asi9test\rco400\addon\auditprg\cmpltjob.r
copy z:\asi_gui9\pco400\addon\auditprg\cmpltjob.r z:\asi9ship\rco400\addon\auditprg\cmpltjob.r
copy z:\asi_gui9\pco400\addon\auditprg\cmpltjob.p z:\asi9test\pco400\addon\auditprg\cmpltjob.p
copy z:\asi_gui9\pco400\addon\auditprg\contact.r z:\asi9test\rco400\addon\auditprg\contact.r
copy z:\asi_gui9\pco400\addon\auditprg\contact.r z:\asi9ship\rco400\addon\auditprg\contact.r
copy z:\asi_gui9\pco400\addon\auditprg\contact.p z:\asi9test\pco400\addon\auditprg\contact.p
copy z:\asi_gui9\pco400\addon\auditprg\emplogin.r z:\asi9test\rco400\addon\auditprg\emplogin.r
copy z:\asi_gui9\pco400\addon\auditprg\emplogin.r z:\asi9ship\rco400\addon\auditprg\emplogin.r
copy z:\asi_gui9\pco400\addon\auditprg\emplogin.p z:\asi9test\pco400\addon\auditprg\emplogin.p
copy z:\asi_gui9\pco400\addon\auditprg\employee.r z:\asi9test\rco400\addon\auditprg\employee.r
copy z:\asi_gui9\pco400\addon\auditprg\employee.r z:\asi9ship\rco400\addon\auditprg\employee.r
copy z:\asi_gui9\pco400\addon\auditprg\employee.p z:\asi9test\pco400\addon\auditprg\employee.p
copy z:\asi_gui9\pco400\addon\auditprg\empmach.r z:\asi9test\rco400\addon\auditprg\empmach.r
copy z:\asi_gui9\pco400\addon\auditprg\empmach.r z:\asi9ship\rco400\addon\auditprg\empmach.r
copy z:\asi_gui9\pco400\addon\auditprg\empmach.p z:\asi9test\pco400\addon\auditprg\empmach.p
copy z:\asi_gui9\pco400\addon\auditprg\emp_type.r z:\asi9test\rco400\addon\auditprg\emp_type.r
copy z:\asi_gui9\pco400\addon\auditprg\emp_type.r z:\asi9ship\rco400\addon\auditprg\emp_type.r
copy z:\asi_gui9\pco400\addon\auditprg\emp_type.p z:\asi9test\pco400\addon\auditprg\emp_type.p
copy z:\asi_gui9\pco400\addon\auditprg\jobcad.r z:\asi9test\rco400\addon\auditprg\jobcad.r
copy z:\asi_gui9\pco400\addon\auditprg\jobcad.r z:\asi9ship\rco400\addon\auditprg\jobcad.r
copy z:\asi_gui9\pco400\addon\auditprg\jobcad.p z:\asi9test\pco400\addon\auditprg\jobcad.p
copy z:\asi_gui9\pco400\addon\auditprg\jobitems.r z:\asi9test\rco400\addon\auditprg\jobitems.r
copy z:\asi_gui9\pco400\addon\auditprg\jobitems.r z:\asi9ship\rco400\addon\auditprg\jobitems.r
copy z:\asi_gui9\pco400\addon\auditprg\jobitems.p z:\asi9test\pco400\addon\auditprg\jobitems.p
copy z:\asi_gui9\pco400\addon\auditprg\jobmach.r z:\asi9test\rco400\addon\auditprg\jobmach.r
copy z:\asi_gui9\pco400\addon\auditprg\jobmach.r z:\asi9ship\rco400\addon\auditprg\jobmach.r
copy z:\asi_gui9\pco400\addon\auditprg\jobmach.p z:\asi9test\pco400\addon\auditprg\jobmach.p
copy z:\asi_gui9\pco400\addon\auditprg\jobmatl.r z:\asi9test\rco400\addon\auditprg\jobmatl.r
copy z:\asi_gui9\pco400\addon\auditprg\jobmatl.r z:\asi9ship\rco400\addon\auditprg\jobmatl.r
copy z:\asi_gui9\pco400\addon\auditprg\jobmatl.p z:\asi9test\pco400\addon\auditprg\jobmatl.p
copy z:\asi_gui9\pco400\addon\auditprg\jobnotes.r z:\asi9test\rco400\addon\auditprg\jobnotes.r
copy z:\asi_gui9\pco400\addon\auditprg\jobnotes.r z:\asi9ship\rco400\addon\auditprg\jobnotes.r
copy z:\asi_gui9\pco400\addon\auditprg\jobnotes.p z:\asi9test\pco400\addon\auditprg\jobnotes.p
copy z:\asi_gui9\pco400\addon\auditprg\jobs.r z:\asi9test\rco400\addon\auditprg\jobs.r
copy z:\asi_gui9\pco400\addon\auditprg\jobs.r z:\asi9ship\rco400\addon\auditprg\jobs.r
copy z:\asi_gui9\pco400\addon\auditprg\jobs.p z:\asi9test\pco400\addon\auditprg\jobs.p
copy z:\asi_gui9\pco400\addon\auditprg\jobseq.r z:\asi9test\rco400\addon\auditprg\jobseq.r
copy z:\asi_gui9\pco400\addon\auditprg\jobseq.r z:\asi9ship\rco400\addon\auditprg\jobseq.r
copy z:\asi_gui9\pco400\addon\auditprg\jobseq.p z:\asi9test\pco400\addon\auditprg\jobseq.p
copy z:\asi_gui9\pco400\addon\auditprg\jobsheet.r z:\asi9test\rco400\addon\auditprg\jobsheet.r
copy z:\asi_gui9\pco400\addon\auditprg\jobsheet.r z:\asi9ship\rco400\addon\auditprg\jobsheet.r
copy z:\asi_gui9\pco400\addon\auditprg\jobsheet.p z:\asi9test\pco400\addon\auditprg\jobsheet.p
copy z:\asi_gui9\pco400\addon\auditprg\jobstack.r z:\asi9test\rco400\addon\auditprg\jobstack.r
copy z:\asi_gui9\pco400\addon\auditprg\jobstack.r z:\asi9ship\rco400\addon\auditprg\jobstack.r
copy z:\asi_gui9\pco400\addon\auditprg\jobstack.p z:\asi9test\pco400\addon\auditprg\jobstack.p
copy z:\asi_gui9\pco400\addon\auditprg\machchrg.r z:\asi9test\rco400\addon\auditprg\machchrg.r
copy z:\asi_gui9\pco400\addon\auditprg\machchrg.r z:\asi9ship\rco400\addon\auditprg\machchrg.r
copy z:\asi_gui9\pco400\addon\auditprg\machchrg.p z:\asi9test\pco400\addon\auditprg\machchrg.p
copy z:\asi_gui9\pco400\addon\auditprg\machemp.r z:\asi9test\rco400\addon\auditprg\machemp.r
copy z:\asi_gui9\pco400\addon\auditprg\machemp.r z:\asi9ship\rco400\addon\auditprg\machemp.r
copy z:\asi_gui9\pco400\addon\auditprg\machemp.p z:\asi9test\pco400\addon\auditprg\machemp.p
copy z:\asi_gui9\pco400\addon\auditprg\machseq.r z:\asi9test\rco400\addon\auditprg\machseq.r
copy z:\asi_gui9\pco400\addon\auditprg\machseq.r z:\asi9ship\rco400\addon\auditprg\machseq.r
copy z:\asi_gui9\pco400\addon\auditprg\machseq.p z:\asi9test\pco400\addon\auditprg\machseq.p
copy z:\asi_gui9\pco400\addon\auditprg\MACHSHFT.r z:\asi9test\rco400\addon\auditprg\MACHSHFT.r
copy z:\asi_gui9\pco400\addon\auditprg\MACHSHFT.r z:\asi9ship\rco400\addon\auditprg\MACHSHFT.r
copy z:\asi_gui9\pco400\addon\auditprg\MACHSHFT.p z:\asi9test\pco400\addon\auditprg\MACHSHFT.p
copy z:\asi_gui9\pco400\addon\auditprg\machtran.r z:\asi9test\rco400\addon\auditprg\machtran.r
copy z:\asi_gui9\pco400\addon\auditprg\machtran.r z:\asi9ship\rco400\addon\auditprg\machtran.r
copy z:\asi_gui9\pco400\addon\auditprg\machtran.p z:\asi9test\pco400\addon\auditprg\machtran.p
copy z:\asi_gui9\pco400\addon\auditprg\OPTCONFG.r z:\asi9test\rco400\addon\auditprg\OPTCONFG.r
copy z:\asi_gui9\pco400\addon\auditprg\OPTCONFG.r z:\asi9ship\rco400\addon\auditprg\OPTCONFG.r
copy z:\asi_gui9\pco400\addon\auditprg\OPTCONFG.p z:\asi9test\pco400\addon\auditprg\OPTCONFG.p
copy z:\asi_gui9\pco400\addon\auditprg\rate.r z:\asi9test\rco400\addon\auditprg\rate.r
copy z:\asi_gui9\pco400\addon\auditprg\rate.r z:\asi9ship\rco400\addon\auditprg\rate.r
copy z:\asi_gui9\pco400\addon\auditprg\rate.p z:\asi9test\pco400\addon\auditprg\rate.p
copy z:\asi_gui9\pco400\addon\auditprg\shifts.r z:\asi9test\rco400\addon\auditprg\shifts.r
copy z:\asi_gui9\pco400\addon\auditprg\shifts.r z:\asi9ship\rco400\addon\auditprg\shifts.r
copy z:\asi_gui9\pco400\addon\auditprg\shifts.p z:\asi9test\pco400\addon\auditprg\shifts.p
copy z:\asi_gui9\pco400\addon\custitem\r-cstit2.r z:\asi9test\rco400\addon\custitem\r-cstit2.r
copy z:\asi_gui9\pco400\addon\custitem\r-cstit2.r z:\asi9ship\rco400\addon\custitem\r-cstit2.r
copy z:\asi_gui9\pco400\addon\custitem\r-cstit2.w z:\asi9test\pco400\addon\custitem\r-cstit2.w
copy z:\asi_gui9\pco400\addon\custitem\r-cstitm.r z:\asi9test\rco400\addon\custitem\r-cstitm.r
copy z:\asi_gui9\pco400\addon\custitem\r-cstitm.r z:\asi9ship\rco400\addon\custitem\r-cstitm.r
copy z:\asi_gui9\pco400\addon\custitem\r-cstitm.w z:\asi9test\pco400\addon\custitem\r-cstitm.w
copy z:\asi_gui9\pco400\addon\custom\kiwiexpt.r z:\asi9test\rco400\addon\custom\kiwiexpt.r
copy z:\asi_gui9\pco400\addon\custom\kiwiexpt.r z:\asi9ship\rco400\addon\custom\kiwiexpt.r
copy z:\asi_gui9\pco400\addon\custom\kiwiexpt.p z:\asi9test\pco400\addon\custom\kiwiexpt.p
copy z:\asi_gui9\pco400\addon\custom\SCOREEXP.r z:\asi9test\rco400\addon\custom\SCOREEXP.r
copy z:\asi_gui9\pco400\addon\custom\SCOREEXP.r z:\asi9ship\rco400\addon\custom\SCOREEXP.r
copy z:\asi_gui9\pco400\addon\custom\SCOREEXP.p z:\asi9test\pco400\addon\custom\SCOREEXP.p
copy z:\asi_gui9\pco400\addon\custom\SCOREIMP.r z:\asi9test\rco400\addon\custom\SCOREIMP.r
copy z:\asi_gui9\pco400\addon\custom\SCOREIMP.r z:\asi9ship\rco400\addon\custom\SCOREIMP.r
copy z:\asi_gui9\pco400\addon\custom\SCOREIMP.p z:\asi9test\pco400\addon\custom\SCOREIMP.p
copy z:\asi_gui9\pco400\addon\fg\b-delt.r z:\asi9test\rco400\addon\fg\b-delt.r
copy z:\asi_gui9\pco400\addon\fg\b-delt.r z:\asi9ship\rco400\addon\fg\b-delt.r
copy z:\asi_gui9\pco400\addon\fg\b-delt.w z:\asi9test\pco400\addon\fg\b-delt.w
copy z:\asi_gui9\pco400\addon\fg\b-rcptd.r z:\asi9test\rco400\addon\fg\b-rcptd.r
copy z:\asi_gui9\pco400\addon\fg\b-rcptd.r z:\asi9ship\rco400\addon\fg\b-rcptd.r
copy z:\asi_gui9\pco400\addon\fg\b-rcptd.w z:\asi9test\pco400\addon\fg\b-rcptd.w
copy z:\asi_gui9\pco400\addon\fg\b-rcptds.r z:\asi9test\rco400\addon\fg\b-rcptds.r
copy z:\asi_gui9\pco400\addon\fg\b-rcptds.r z:\asi9ship\rco400\addon\fg\b-rcptds.r
copy z:\asi_gui9\pco400\addon\fg\b-rcptds.w z:\asi9test\pco400\addon\fg\b-rcptds.w
copy z:\asi_gui9\pco400\addon\fg\fgpstall.r z:\asi9test\rco400\addon\fg\fgpstall.r
copy z:\asi_gui9\pco400\addon\fg\fgpstall.r z:\asi9ship\rco400\addon\fg\fgpstall.r
copy z:\asi_gui9\pco400\addon\fg\fgpstall.w z:\asi9test\pco400\addon\fg\fgpstall.w
copy z:\asi_gui9\pco400\addon\lookups\blanknum.r z:\asi9test\rco400\addon\lookups\blanknum.r
copy z:\asi_gui9\pco400\addon\lookups\blanknum.r z:\asi9ship\rco400\addon\lookups\blanknum.r
copy z:\asi_gui9\pco400\addon\lookups\blanknum.p z:\asi9test\pco400\addon\lookups\blanknum.p
copy z:\asi_gui9\pco400\addon\lookups\employee.r z:\asi9test\rco400\addon\lookups\employee.r
copy z:\asi_gui9\pco400\addon\lookups\employee.r z:\asi9ship\rco400\addon\lookups\employee.r
copy z:\asi_gui9\pco400\addon\lookups\employee.p z:\asi9test\pco400\addon\lookups\employee.p
copy z:\asi_gui9\pco400\addon\lookups\employe_.r z:\asi9test\rco400\addon\lookups\employe_.r
copy z:\asi_gui9\pco400\addon\lookups\employe_.r z:\asi9ship\rco400\addon\lookups\employe_.r
copy z:\asi_gui9\pco400\addon\lookups\employe_.p z:\asi9test\pco400\addon\lookups\employe_.p
copy z:\asi_gui9\pco400\addon\lookups\emp_ss.r z:\asi9test\rco400\addon\lookups\emp_ss.r
copy z:\asi_gui9\pco400\addon\lookups\emp_ss.r z:\asi9ship\rco400\addon\lookups\emp_ss.r
copy z:\asi_gui9\pco400\addon\lookups\emp_ss.p z:\asi9test\pco400\addon\lookups\emp_ss.p
copy z:\asi_gui9\pco400\addon\lookups\emp_type.r z:\asi9test\rco400\addon\lookups\emp_type.r
copy z:\asi_gui9\pco400\addon\lookups\emp_type.r z:\asi9ship\rco400\addon\lookups\emp_type.r
copy z:\asi_gui9\pco400\addon\lookups\emp_type.p z:\asi9test\pco400\addon\lookups\emp_type.p
copy z:\asi_gui9\pco400\addon\lookups\emp_typ_.r z:\asi9test\rco400\addon\lookups\emp_typ_.r
copy z:\asi_gui9\pco400\addon\lookups\emp_typ_.r z:\asi9ship\rco400\addon\lookups\emp_typ_.r
copy z:\asi_gui9\pco400\addon\lookups\emp_typ_.p z:\asi9test\pco400\addon\lookups\emp_typ_.p
copy z:\asi_gui9\pco400\addon\lookups\formnumb.r z:\asi9test\rco400\addon\lookups\formnumb.r
copy z:\asi_gui9\pco400\addon\lookups\formnumb.r z:\asi9ship\rco400\addon\lookups\formnumb.r
copy z:\asi_gui9\pco400\addon\lookups\formnumb.p z:\asi9test\pco400\addon\lookups\formnumb.p
copy z:\asi_gui9\pco400\addon\lookups\item1.r z:\asi9test\rco400\addon\lookups\item1.r
copy z:\asi_gui9\pco400\addon\lookups\item1.r z:\asi9ship\rco400\addon\lookups\item1.r
copy z:\asi_gui9\pco400\addon\lookups\item1.p z:\asi9test\pco400\addon\lookups\item1.p
copy z:\asi_gui9\pco400\addon\lookups\item1__.r z:\asi9test\rco400\addon\lookups\item1__.r
copy z:\asi_gui9\pco400\addon\lookups\item1__.r z:\asi9ship\rco400\addon\lookups\item1__.r
copy z:\asi_gui9\pco400\addon\lookups\item1__.p z:\asi9test\pco400\addon\lookups\item1__.p
copy z:\asi_gui9\pco400\addon\lookups\jobnumbr.r z:\asi9test\rco400\addon\lookups\jobnumbr.r
copy z:\asi_gui9\pco400\addon\lookups\jobnumbr.r z:\asi9ship\rco400\addon\lookups\jobnumbr.r
copy z:\asi_gui9\pco400\addon\lookups\jobnumbr.p z:\asi9test\pco400\addon\lookups\jobnumbr.p
copy z:\asi_gui9\pco400\addon\lookups\jobsub.r z:\asi9test\rco400\addon\lookups\jobsub.r
copy z:\asi_gui9\pco400\addon\lookups\jobsub.r z:\asi9ship\rco400\addon\lookups\jobsub.r
copy z:\asi_gui9\pco400\addon\lookups\jobsub.p z:\asi9test\pco400\addon\lookups\jobsub.p
copy z:\asi_gui9\pco400\addon\lookups\machchrg.r z:\asi9test\rco400\addon\lookups\machchrg.r
copy z:\asi_gui9\pco400\addon\lookups\machchrg.r z:\asi9ship\rco400\addon\lookups\machchrg.r
copy z:\asi_gui9\pco400\addon\lookups\machchrg.p z:\asi9test\pco400\addon\lookups\machchrg.p
copy z:\asi_gui9\pco400\addon\lookups\machine.r z:\asi9test\rco400\addon\lookups\machine.r
copy z:\asi_gui9\pco400\addon\lookups\machine.r z:\asi9ship\rco400\addon\lookups\machine.r
copy z:\asi_gui9\pco400\addon\lookups\machine.p z:\asi9test\pco400\addon\lookups\machine.p
copy z:\asi_gui9\pco400\addon\lookups\pass_seq.r z:\asi9test\rco400\addon\lookups\pass_seq.r
copy z:\asi_gui9\pco400\addon\lookups\pass_seq.r z:\asi9ship\rco400\addon\lookups\pass_seq.r
copy z:\asi_gui9\pco400\addon\lookups\pass_seq.p z:\asi9test\pco400\addon\lookups\pass_seq.p
copy z:\asi_gui9\pco400\addon\lookups\po-ordl.r z:\asi9test\rco400\addon\lookups\po-ordl.r
copy z:\asi_gui9\pco400\addon\lookups\po-ordl.r z:\asi9ship\rco400\addon\lookups\po-ordl.r
copy z:\asi_gui9\pco400\addon\lookups\po-ordl.p z:\asi9test\pco400\addon\lookups\po-ordl.p
copy z:\asi_gui9\pco400\addon\lookups\po-ordl1.r z:\asi9test\rco400\addon\lookups\po-ordl1.r
copy z:\asi_gui9\pco400\addon\lookups\po-ordl1.r z:\asi9ship\rco400\addon\lookups\po-ordl1.r
copy z:\asi_gui9\pco400\addon\lookups\po-ordl1.p z:\asi9test\pco400\addon\lookups\po-ordl1.p
copy z:\asi_gui9\pco400\addon\lookups\printer.r z:\asi9test\rco400\addon\lookups\printer.r
copy z:\asi_gui9\pco400\addon\lookups\printer.r z:\asi9ship\rco400\addon\lookups\printer.r
copy z:\asi_gui9\pco400\addon\lookups\printer.p z:\asi9test\pco400\addon\lookups\printer.p
copy z:\asi_gui9\pco400\addon\lookups\shifts.r z:\asi9test\rco400\addon\lookups\shifts.r
copy z:\asi_gui9\pco400\addon\lookups\shifts.r z:\asi9ship\rco400\addon\lookups\shifts.r
copy z:\asi_gui9\pco400\addon\lookups\shifts.p z:\asi9test\pco400\addon\lookups\shifts.p
copy z:\asi_gui9\pco400\addon\lookups\shifts_.r z:\asi9test\rco400\addon\lookups\shifts_.r
copy z:\asi_gui9\pco400\addon\lookups\shifts_.r z:\asi9ship\rco400\addon\lookups\shifts_.r
copy z:\asi_gui9\pco400\addon\lookups\shifts_.p z:\asi9test\pco400\addon\lookups\shifts_.p
copy z:\asi_gui9\pco400\addon\lookups\soc_sec.r z:\asi9test\rco400\addon\lookups\soc_sec.r
copy z:\asi_gui9\pco400\addon\lookups\soc_sec.r z:\asi9ship\rco400\addon\lookups\soc_sec.r
copy z:\asi_gui9\pco400\addon\lookups\soc_sec.p z:\asi9test\pco400\addon\lookups\soc_sec.p
copy z:\asi_gui9\pco400\addon\lstlogic\account_.r z:\asi9test\rco400\addon\lstlogic\account_.r
copy z:\asi_gui9\pco400\addon\lstlogic\account_.r z:\asi9ship\rco400\addon\lstlogic\account_.r
copy z:\asi_gui9\pco400\addon\lstlogic\account_.p z:\asi9test\pco400\addon\lstlogic\account_.p
copy z:\asi_gui9\pco400\addon\lstlogic\cmpltjo_.r z:\asi9test\rco400\addon\lstlogic\cmpltjo_.r
copy z:\asi_gui9\pco400\addon\lstlogic\cmpltjo_.r z:\asi9ship\rco400\addon\lstlogic\cmpltjo_.r
copy z:\asi_gui9\pco400\addon\lstlogic\cmpltjo_.p z:\asi9test\pco400\addon\lstlogic\cmpltjo_.p
copy z:\asi_gui9\pco400\addon\lstlogic\contact_.r z:\asi9test\rco400\addon\lstlogic\contact_.r
copy z:\asi_gui9\pco400\addon\lstlogic\contact_.r z:\asi9ship\rco400\addon\lstlogic\contact_.r
copy z:\asi_gui9\pco400\addon\lstlogic\contact_.p z:\asi9test\pco400\addon\lstlogic\contact_.p
copy z:\asi_gui9\pco400\addon\lstlogic\cstitm_.r z:\asi9test\rco400\addon\lstlogic\cstitm_.r
copy z:\asi_gui9\pco400\addon\lstlogic\cstitm_.r z:\asi9ship\rco400\addon\lstlogic\cstitm_.r
copy z:\asi_gui9\pco400\addon\lstlogic\cstitm_.p z:\asi9test\pco400\addon\lstlogic\cstitm_.p
copy z:\asi_gui9\pco400\addon\lstlogic\emplogi_.r z:\asi9test\rco400\addon\lstlogic\emplogi_.r
copy z:\asi_gui9\pco400\addon\lstlogic\emplogi_.r z:\asi9ship\rco400\addon\lstlogic\emplogi_.r
copy z:\asi_gui9\pco400\addon\lstlogic\emplogi_.p z:\asi9test\pco400\addon\lstlogic\emplogi_.p
copy z:\asi_gui9\pco400\addon\lstlogic\employe_.r z:\asi9test\rco400\addon\lstlogic\employe_.r
copy z:\asi_gui9\pco400\addon\lstlogic\employe_.r z:\asi9ship\rco400\addon\lstlogic\employe_.r
copy z:\asi_gui9\pco400\addon\lstlogic\employe_.p z:\asi9test\pco400\addon\lstlogic\employe_.p
copy z:\asi_gui9\pco400\addon\lstlogic\EMPRPT1_.r z:\asi9test\rco400\addon\lstlogic\EMPRPT1_.r
copy z:\asi_gui9\pco400\addon\lstlogic\EMPRPT1_.r z:\asi9ship\rco400\addon\lstlogic\EMPRPT1_.r
copy z:\asi_gui9\pco400\addon\lstlogic\EMPRPT1_.p z:\asi9test\pco400\addon\lstlogic\EMPRPT1_.p
copy z:\asi_gui9\pco400\addon\lstlogic\emp_typ_.r z:\asi9test\rco400\addon\lstlogic\emp_typ_.r
copy z:\asi_gui9\pco400\addon\lstlogic\emp_typ_.r z:\asi9ship\rco400\addon\lstlogic\emp_typ_.r
copy z:\asi_gui9\pco400\addon\lstlogic\emp_typ_.p z:\asi9test\pco400\addon\lstlogic\emp_typ_.p
copy z:\asi_gui9\pco400\addon\lstlogic\machchr_.r z:\asi9test\rco400\addon\lstlogic\machchr_.r
copy z:\asi_gui9\pco400\addon\lstlogic\machchr_.r z:\asi9ship\rco400\addon\lstlogic\machchr_.r
copy z:\asi_gui9\pco400\addon\lstlogic\machchr_.p z:\asi9test\pco400\addon\lstlogic\machchr_.p
copy z:\asi_gui9\pco400\addon\lstlogic\MACHSHF_.r z:\asi9test\rco400\addon\lstlogic\MACHSHF_.r
copy z:\asi_gui9\pco400\addon\lstlogic\MACHSHF_.r z:\asi9ship\rco400\addon\lstlogic\MACHSHF_.r
copy z:\asi_gui9\pco400\addon\lstlogic\MACHSHF_.p z:\asi9test\pco400\addon\lstlogic\MACHSHF_.p
copy z:\asi_gui9\pco400\addon\lstlogic\machtra_.r z:\asi9test\rco400\addon\lstlogic\machtra_.r
copy z:\asi_gui9\pco400\addon\lstlogic\machtra_.r z:\asi9ship\rco400\addon\lstlogic\machtra_.r
copy z:\asi_gui9\pco400\addon\lstlogic\machtra_.p z:\asi9test\pco400\addon\lstlogic\machtra_.p
copy z:\asi_gui9\pco400\addon\lstlogic\OPTCONF_.r z:\asi9test\rco400\addon\lstlogic\OPTCONF_.r
copy z:\asi_gui9\pco400\addon\lstlogic\OPTCONF_.r z:\asi9ship\rco400\addon\lstlogic\OPTCONF_.r
copy z:\asi_gui9\pco400\addon\lstlogic\OPTCONF_.p z:\asi9test\pco400\addon\lstlogic\OPTCONF_.p
copy z:\asi_gui9\pco400\addon\lstlogic\rm-aitem_.r z:\asi9test\rco400\addon\lstlogic\rm-aitem_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-aitem_.r z:\asi9ship\rco400\addon\lstlogic\rm-aitem_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-aitem_.p z:\asi9test\pco400\addon\lstlogic\rm-aitem_.p
copy z:\asi_gui9\pco400\addon\lstlogic\rm-ibtag_.r z:\asi9test\rco400\addon\lstlogic\rm-ibtag_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-ibtag_.r z:\asi9ship\rco400\addon\lstlogic\rm-ibtag_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-ibtag_.p z:\asi9test\pco400\addon\lstlogic\rm-ibtag_.p
copy z:\asi_gui9\pco400\addon\lstlogic\rm-reord_.r z:\asi9test\rco400\addon\lstlogic\rm-reord_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-reord_.r z:\asi9ship\rco400\addon\lstlogic\rm-reord_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-reord_.p z:\asi9test\pco400\addon\lstlogic\rm-reord_.p
copy z:\asi_gui9\pco400\addon\lstlogic\rm-trans_.r z:\asi9test\rco400\addon\lstlogic\rm-trans_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-trans_.r z:\asi9ship\rco400\addon\lstlogic\rm-trans_.r
copy z:\asi_gui9\pco400\addon\lstlogic\rm-trans_.p z:\asi9test\pco400\addon\lstlogic\rm-trans_.p
copy z:\asi_gui9\pco400\addon\lstlogic\shifts_.r z:\asi9test\rco400\addon\lstlogic\shifts_.r
copy z:\asi_gui9\pco400\addon\lstlogic\shifts_.r z:\asi9ship\rco400\addon\lstlogic\shifts_.r
copy z:\asi_gui9\pco400\addon\lstlogic\shifts_.p z:\asi9test\pco400\addon\lstlogic\shifts_.p
copy z:\asi_gui9\pco400\addon\lstlogic\shrpt1_.r z:\asi9test\rco400\addon\lstlogic\shrpt1_.r
copy z:\asi_gui9\pco400\addon\lstlogic\shrpt1_.r z:\asi9ship\rco400\addon\lstlogic\shrpt1_.r
copy z:\asi_gui9\pco400\addon\lstlogic\shrpt1_.p z:\asi9test\pco400\addon\lstlogic\shrpt1_.p
copy z:\asi_gui9\pco400\addon\lstlogic\vplist_.r z:\asi9test\rco400\addon\lstlogic\vplist_.r
copy z:\asi_gui9\pco400\addon\lstlogic\vplist_.r z:\asi9ship\rco400\addon\lstlogic\vplist_.r
copy z:\asi_gui9\pco400\addon\lstlogic\vplist_.p z:\asi9test\pco400\addon\lstlogic\vplist_.p
copy z:\asi_gui9\pco400\addon\sys\util\unpost.r z:\asi9test\rco400\addon\sys\util\unpost.r
copy z:\asi_gui9\pco400\addon\sys\util\unpost.r z:\asi9ship\rco400\addon\sys\util\unpost.r
copy z:\asi_gui9\pco400\addon\sys\util\unpost.p z:\asi9test\pco400\addon\sys\util\unpost.p
copy z:\asi_gui9\pco400\addon\touch\copynot2.r z:\asi9test\rco400\addon\touch\copynot2.r
copy z:\asi_gui9\pco400\addon\touch\copynot2.r z:\asi9ship\rco400\addon\touch\copynot2.r
copy z:\asi_gui9\pco400\addon\touch\copynot2.p z:\asi9test\pco400\addon\touch\copynot2.p
copy z:\asi_gui9\pco400\addon\util\empreset.r z:\asi9test\rco400\addon\util\empreset.r
copy z:\asi_gui9\pco400\addon\util\empreset.r z:\asi9ship\rco400\addon\util\empreset.r
copy z:\asi_gui9\pco400\addon\util\empreset.p z:\asi9test\pco400\addon\util\empreset.p
copy z:\asi_gui9\pco400\addon\util\spec-qt2.r z:\asi9test\rco400\addon\util\spec-qt2.r
copy z:\asi_gui9\pco400\addon\util\spec-qt2.r z:\asi9ship\rco400\addon\util\spec-qt2.r
copy z:\asi_gui9\pco400\addon\util\spec-qt2.p z:\asi9test\pco400\addon\util\spec-qt2.p
copy z:\asi_gui9\pco400\addon\windows\l-ldtag.r z:\asi9test\rco400\addon\windows\l-ldtag.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag.r z:\asi9ship\rco400\addon\windows\l-ldtag.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag.w z:\asi9test\pco400\addon\windows\l-ldtag.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag2.r z:\asi9test\rco400\addon\windows\l-ldtag2.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag2.r z:\asi9ship\rco400\addon\windows\l-ldtag2.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag2.w z:\asi9test\pco400\addon\windows\l-ldtag2.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag3.r z:\asi9test\rco400\addon\windows\l-ldtag3.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag3.r z:\asi9ship\rco400\addon\windows\l-ldtag3.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag3.w z:\asi9test\pco400\addon\windows\l-ldtag3.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag4.r z:\asi9test\rco400\addon\windows\l-ldtag4.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag4.r z:\asi9ship\rco400\addon\windows\l-ldtag4.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag4.w z:\asi9test\pco400\addon\windows\l-ldtag4.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag5.r z:\asi9test\rco400\addon\windows\l-ldtag5.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag5.r z:\asi9ship\rco400\addon\windows\l-ldtag5.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag5.w z:\asi9test\pco400\addon\windows\l-ldtag5.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag6.r z:\asi9test\rco400\addon\windows\l-ldtag6.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag6.r z:\asi9ship\rco400\addon\windows\l-ldtag6.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag6.w z:\asi9test\pco400\addon\windows\l-ldtag6.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag7.r z:\asi9test\rco400\addon\windows\l-ldtag7.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag7.r z:\asi9ship\rco400\addon\windows\l-ldtag7.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag7.w z:\asi9test\pco400\addon\windows\l-ldtag7.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag8.r z:\asi9test\rco400\addon\windows\l-ldtag8.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag8.r z:\asi9ship\rco400\addon\windows\l-ldtag8.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag8.w z:\asi9test\pco400\addon\windows\l-ldtag8.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtag9.r z:\asi9test\rco400\addon\windows\l-ldtag9.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag9.r z:\asi9ship\rco400\addon\windows\l-ldtag9.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtag9.w z:\asi9test\pco400\addon\windows\l-ldtag9.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtaga.r z:\asi9test\rco400\addon\windows\l-ldtaga.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtaga.r z:\asi9ship\rco400\addon\windows\l-ldtaga.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtaga.w z:\asi9test\pco400\addon\windows\l-ldtaga.w
copy z:\asi_gui9\pco400\addon\windows\l-ldtagc.r z:\asi9test\rco400\addon\windows\l-ldtagc.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtagc.r z:\asi9ship\rco400\addon\windows\l-ldtagc.r
copy z:\asi_gui9\pco400\addon\windows\l-ldtagc.w z:\asi9test\pco400\addon\windows\l-ldtagc.w
copy z:\asi_gui9\pco400\ap\ap-ckadv.r z:\asi9test\rco400\ap\ap-ckadv.r
copy z:\asi_gui9\pco400\ap\ap-ckadv.r z:\asi9ship\rco400\ap\ap-ckadv.r
copy z:\asi_gui9\pco400\ap\ap-ckadv.p z:\asi9test\pco400\ap\ap-ckadv.p
copy z:\asi_gui9\pco400\ap\b-apdis.r z:\asi9test\rco400\ap\b-apdis.r
copy z:\asi_gui9\pco400\ap\b-apdis.r z:\asi9ship\rco400\ap\b-apdis.r
copy z:\asi_gui9\pco400\ap\b-apdis.w z:\asi9test\pco400\ap\b-apdis.w
copy z:\asi_gui9\pco400\ap\b-apdis2.r z:\asi9test\rco400\ap\b-apdis2.r
copy z:\asi_gui9\pco400\ap\b-apdis2.r z:\asi9ship\rco400\ap\b-apdis2.r
copy z:\asi_gui9\pco400\ap\b-apdis2.w z:\asi9test\pco400\ap\b-apdis2.w
copy z:\asi_gui9\pco400\ap\b-chkrec.r z:\asi9test\rco400\ap\b-chkrec.r
copy z:\asi_gui9\pco400\ap\b-chkrec.r z:\asi9ship\rco400\ap\b-chkrec.r
copy z:\asi_gui9\pco400\ap\b-chkrec.w z:\asi9test\pco400\ap\b-chkrec.w
copy z:\asi_gui9\pco400\ap\b-dbcr.r z:\asi9test\rco400\ap\b-dbcr.r
copy z:\asi_gui9\pco400\ap\b-dbcr.r z:\asi9ship\rco400\ap\b-dbcr.r
copy z:\asi_gui9\pco400\ap\b-dbcr.w z:\asi9test\pco400\ap\b-dbcr.w
copy z:\asi_gui9\pco400\ap\b-seldue.r z:\asi9test\rco400\ap\b-seldue.r
copy z:\asi_gui9\pco400\ap\b-seldue.r z:\asi9ship\rco400\ap\b-seldue.r
copy z:\asi_gui9\pco400\ap\b-seldue.w z:\asi9test\pco400\ap\b-seldue.w
copy z:\asi_gui9\pco400\ap\b-test.r z:\asi9test\rco400\ap\b-test.r
copy z:\asi_gui9\pco400\ap\b-test.r z:\asi9ship\rco400\ap\b-test.r
copy z:\asi_gui9\pco400\ap\b-test.w z:\asi9test\pco400\ap\b-test.w
copy z:\asi_gui9\pco400\ap\b-void.r z:\asi9test\rco400\ap\b-void.r
copy z:\asi_gui9\pco400\ap\b-void.r z:\asi9ship\rco400\ap\b-void.r
copy z:\asi_gui9\pco400\ap\b-void.w z:\asi9test\pco400\ap\b-void.w
copy z:\asi_gui9\pco400\ap\d-crtvnd.wsav.r z:\asi9test\rco400\ap\d-crtvnd.wsav.r
copy z:\asi_gui9\pco400\ap\d-crtvnd.wsav.r z:\asi9ship\rco400\ap\d-crtvnd.wsav.r
copy z:\asi_gui9\pco400\ap\d-crtvnd.wsav.w z:\asi9test\pco400\ap\d-crtvnd.wsav.w
copy z:\asi_gui9\pco400\ar\b-arinq.r z:\asi9test\rco400\ar\b-arinq.r
copy z:\asi_gui9\pco400\ar\b-arinq.r z:\asi9ship\rco400\ar\b-arinq.r
copy z:\asi_gui9\pco400\ar\b-arinq.w z:\asi9test\pco400\ar\b-arinq.w
copy z:\asi_gui9\pco400\ar\b-arlinq.r z:\asi9test\rco400\ar\b-arlinq.r
copy z:\asi_gui9\pco400\ar\b-arlinq.r z:\asi9ship\rco400\ar\b-arlinq.r
copy z:\asi_gui9\pco400\ar\b-arlinq.w z:\asi9test\pco400\ar\b-arlinq.w
copy z:\asi_gui9\pco400\ar\b-mcash-.r z:\asi9test\rco400\ar\b-mcash-.r
copy z:\asi_gui9\pco400\ar\b-mcash-.r z:\asi9ship\rco400\ar\b-mcash-.r
copy z:\asi_gui9\pco400\ar\b-mcash-.w z:\asi9test\pco400\ar\b-mcash-.w
copy z:\asi_gui9\pco400\ar\b-voidchk.r z:\asi9test\rco400\ar\b-voidchk.r
copy z:\asi_gui9\pco400\ar\b-voidchk.r z:\asi9ship\rco400\ar\b-voidchk.r
copy z:\asi_gui9\pco400\ar\b-voidchk.w z:\asi9test\pco400\ar\b-voidchk.w
copy z:\asi_gui9\pco400\arrep\r-ariprt_fax.r z:\asi9test\rco400\arrep\r-ariprt_fax.r
copy z:\asi_gui9\pco400\arrep\r-ariprt_fax.r z:\asi9ship\rco400\arrep\r-ariprt_fax.r
copy z:\asi_gui9\pco400\arrep\r-ariprt_fax.w z:\asi9test\pco400\arrep\r-ariprt_fax.w
copy z:\asi_gui9\pco400\bol\b-oebolh.r z:\asi9test\rco400\bol\b-oebolh.r
copy z:\asi_gui9\pco400\bol\b-oebolh.r z:\asi9ship\rco400\bol\b-oebolh.r
copy z:\asi_gui9\pco400\bol\b-oebolh.w z:\asi9test\pco400\bol\b-oebolh.w
copy z:\asi_gui9\pco400\bol\b-oeboll.r z:\asi9test\rco400\bol\b-oeboll.r
copy z:\asi_gui9\pco400\bol\b-oeboll.r z:\asi9ship\rco400\bol\b-oeboll.r
copy z:\asi_gui9\pco400\bol\b-oeboll.w z:\asi9test\pco400\bol\b-oeboll.w
copy z:\asi_gui9\pco400\bol\sc-oeboh.r z:\asi9test\rco400\bol\sc-oeboh.r
copy z:\asi_gui9\pco400\bol\sc-oeboh.r z:\asi9ship\rco400\bol\sc-oeboh.r
copy z:\asi_gui9\pco400\bol\sc-oeboh.w z:\asi9test\pco400\bol\sc-oeboh.w
copy z:\asi_gui9\pco400\bol\sc-oetag.r z:\asi9test\rco400\bol\sc-oetag.r
copy z:\asi_gui9\pco400\bol\sc-oetag.r z:\asi9ship\rco400\bol\sc-oetag.r
copy z:\asi_gui9\pco400\bol\sc-oetag.w z:\asi9test\pco400\bol\sc-oetag.w
copy z:\asi_gui9\pco400\bol\v-blpost.r z:\asi9test\rco400\bol\v-blpost.r
copy z:\asi_gui9\pco400\bol\v-blpost.r z:\asi9ship\rco400\bol\v-blpost.r
copy z:\asi_gui9\pco400\bol\v-blpost.w z:\asi9test\pco400\bol\v-blpost.w
copy z:\asi_gui9\pco400\browsers\itemfg2.r z:\asi9test\rco400\browsers\itemfg2.r
copy z:\asi_gui9\pco400\browsers\itemfg2.r z:\asi9ship\rco400\browsers\itemfg2.r
copy z:\asi_gui9\pco400\browsers\itemfg2.w z:\asi9test\pco400\browsers\itemfg2.w
copy z:\asi_gui9\pco400\ce\b-estlst.r z:\asi9test\rco400\ce\b-estlst.r
copy z:\asi_gui9\pco400\ce\b-estlst.r z:\asi9ship\rco400\ce\b-estlst.r
copy z:\asi_gui9\pco400\ce\b-estlst.w z:\asi9test\pco400\ce\b-estlst.w
copy z:\asi_gui9\pco400\cec\quote\prtquo10.r z:\asi9test\rco400\cec\quote\prtquo10.r
copy z:\asi_gui9\pco400\cec\quote\prtquo10.r z:\asi9ship\rco400\cec\quote\prtquo10.r
copy z:\asi_gui9\pco400\cec\quote\prtquo10.p z:\asi9test\pco400\cec\quote\prtquo10.p
copy z:\asi_gui9\pco400\cec\quote\quoabox.r z:\asi9test\rco400\cec\quote\quoabox.r
copy z:\asi_gui9\pco400\cec\quote\quoabox.r z:\asi9ship\rco400\cec\quote\quoabox.r
copy z:\asi_gui9\pco400\cec\quote\quoabox.p z:\asi9test\pco400\cec\quote\quoabox.p
copy z:\asi_gui9\pco400\cec\quote\quocentx.r z:\asi9test\rco400\cec\quote\quocentx.r
copy z:\asi_gui9\pco400\cec\quote\quocentx.r z:\asi9ship\rco400\cec\quote\quocentx.r
copy z:\asi_gui9\pco400\cec\quote\quocentx.p z:\asi9test\pco400\cec\quote\quocentx.p
copy z:\asi_gui9\pco400\cec\quote\quocsc.r z:\asi9test\rco400\cec\quote\quocsc.r
copy z:\asi_gui9\pco400\cec\quote\quocsc.r z:\asi9ship\rco400\cec\quote\quocsc.r
copy z:\asi_gui9\pco400\cec\quote\quocsc.p z:\asi9test\pco400\cec\quote\quocsc.p
copy z:\asi_gui9\pco400\cec\quote\quoelite.r z:\asi9test\rco400\cec\quote\quoelite.r
copy z:\asi_gui9\pco400\cec\quote\quoelite.r z:\asi9ship\rco400\cec\quote\quoelite.r
copy z:\asi_gui9\pco400\cec\quote\quoelite.p z:\asi9test\pco400\cec\quote\quoelite.p
copy z:\asi_gui9\pco400\cec\quote\quofibre.r z:\asi9test\rco400\cec\quote\quofibre.r
copy z:\asi_gui9\pco400\cec\quote\quofibre.r z:\asi9ship\rco400\cec\quote\quofibre.r
copy z:\asi_gui9\pco400\cec\quote\quofibre.p z:\asi9test\pco400\cec\quote\quofibre.p
copy z:\asi_gui9\pco400\cec\quote\quofrank.r z:\asi9test\rco400\cec\quote\quofrank.r
copy z:\asi_gui9\pco400\cec\quote\quofrank.r z:\asi9ship\rco400\cec\quote\quofrank.r
copy z:\asi_gui9\pco400\cec\quote\quofrank.p z:\asi9test\pco400\cec\quote\quofrank.p
copy z:\asi_gui9\pco400\cec\quote\quohawl.r z:\asi9test\rco400\cec\quote\quohawl.r
copy z:\asi_gui9\pco400\cec\quote\quohawl.r z:\asi9ship\rco400\cec\quote\quohawl.r
copy z:\asi_gui9\pco400\cec\quote\quohawl.p z:\asi9test\pco400\cec\quote\quohawl.p
copy z:\asi_gui9\pco400\cec\quote\quohop.r z:\asi9test\rco400\cec\quote\quohop.r
copy z:\asi_gui9\pco400\cec\quote\quohop.r z:\asi9ship\rco400\cec\quote\quohop.r
copy z:\asi_gui9\pco400\cec\quote\quohop.p z:\asi9test\pco400\cec\quote\quohop.p
copy z:\asi_gui9\pco400\cec\quote\quomwest.r z:\asi9test\rco400\cec\quote\quomwest.r
copy z:\asi_gui9\pco400\cec\quote\quomwest.r z:\asi9ship\rco400\cec\quote\quomwest.r
copy z:\asi_gui9\pco400\cec\quote\quomwest.p z:\asi9test\pco400\cec\quote\quomwest.p
copy z:\asi_gui9\pco400\cec\quote\quooracl.r z:\asi9test\rco400\cec\quote\quooracl.r
copy z:\asi_gui9\pco400\cec\quote\quooracl.r z:\asi9ship\rco400\cec\quote\quooracl.r
copy z:\asi_gui9\pco400\cec\quote\quooracl.p z:\asi9test\pco400\cec\quote\quooracl.p
copy z:\asi_gui9\pco400\cec\quote\quoottpk.r z:\asi9test\rco400\cec\quote\quoottpk.r
copy z:\asi_gui9\pco400\cec\quote\quoottpk.r z:\asi9ship\rco400\cec\quote\quoottpk.r
copy z:\asi_gui9\pco400\cec\quote\quoottpk.p z:\asi9test\pco400\cec\quote\quoottpk.p
copy z:\asi_gui9\pco400\cec\quote\quopacif.r z:\asi9test\rco400\cec\quote\quopacif.r
copy z:\asi_gui9\pco400\cec\quote\quopacif.r z:\asi9ship\rco400\cec\quote\quopacif.r
copy z:\asi_gui9\pco400\cec\quote\quopacif.p z:\asi9test\pco400\cec\quote\quopacif.p
copy z:\asi_gui9\pco400\cec\quote\quosthpk.r z:\asi9test\rco400\cec\quote\quosthpk.r
copy z:\asi_gui9\pco400\cec\quote\quosthpk.r z:\asi9ship\rco400\cec\quote\quosthpk.r
copy z:\asi_gui9\pco400\cec\quote\quosthpk.p z:\asi9test\pco400\cec\quote\quosthpk.p
copy z:\asi_gui9\pco400\cec\quote\quounipk.r z:\asi9test\rco400\cec\quote\quounipk.r
copy z:\asi_gui9\pco400\cec\quote\quounipk.r z:\asi9ship\rco400\cec\quote\quounipk.r
copy z:\asi_gui9\pco400\cec\quote\quounipk.p z:\asi9test\pco400\cec\quote\quounipk.p
copy z:\asi_gui9\pco400\cec\quote\quoxprem.r z:\asi9test\rco400\cec\quote\quoxprem.r
copy z:\asi_gui9\pco400\cec\quote\quoxprem.r z:\asi9ship\rco400\cec\quote\quoxprem.r
copy z:\asi_gui9\pco400\cec\quote\quoxprem.p z:\asi9test\pco400\cec\quote\quoxprem.p
copy z:\asi_gui9\pco400\cec\quote\quoxprnt.r z:\asi9test\rco400\cec\quote\quoxprnt.r
copy z:\asi_gui9\pco400\cec\quote\quoxprnt.r z:\asi9ship\rco400\cec\quote\quoxprnt.r
copy z:\asi_gui9\pco400\cec\quote\quoxprnt.p z:\asi9test\pco400\cec\quote\quoxprnt.p
copy z:\asi_gui9\pco400\cerep\r-quotes.r z:\asi9test\rco400\cerep\r-quotes.r
copy z:\asi_gui9\pco400\cerep\r-quotes.r z:\asi9ship\rco400\cerep\r-quotes.r
copy z:\asi_gui9\pco400\cerep\r-quotes.w z:\asi9test\pco400\cerep\r-quotes.w
copy z:\asi_gui9\pco400\custom\emailListAddon.r z:\asi9test\rco400\custom\emailListAddon.r
copy z:\asi_gui9\pco400\custom\emailListAddon.r z:\asi9ship\rco400\custom\emailListAddon.r
copy z:\asi_gui9\pco400\custom\emailListAddon.p z:\asi9test\pco400\custom\emailListAddon.p
copy z:\asi_gui9\pco400\custom\t-fax.r z:\asi9test\rco400\custom\t-fax.r
copy z:\asi_gui9\pco400\custom\t-fax.r z:\asi9ship\rco400\custom\t-fax.r
copy z:\asi_gui9\pco400\custom\t-fax.p z:\asi9test\pco400\custom\t-fax.p
copy z:\asi_gui9\pco400\custom\t-faxcli.r z:\asi9test\rco400\custom\t-faxcli.r
copy z:\asi_gui9\pco400\custom\t-faxcli.r z:\asi9ship\rco400\custom\t-faxcli.r
copy z:\asi_gui9\pco400\custom\t-faxcli.p z:\asi9test\pco400\custom\t-faxcli.p
copy z:\asi_gui9\pco400\custom\t-print.r z:\asi9test\rco400\custom\t-print.r
copy z:\asi_gui9\pco400\custom\t-print.r z:\asi9ship\rco400\custom\t-print.r
copy z:\asi_gui9\pco400\custom\t-print.p z:\asi9test\pco400\custom\t-print.p
copy z:\asi_gui9\pco400\est\b-estitm.r z:\asi9test\rco400\est\b-estitm.r
copy z:\asi_gui9\pco400\est\b-estitm.r z:\asi9ship\rco400\est\b-estitm.r
copy z:\asi_gui9\pco400\est\b-estitm.w z:\asi9test\pco400\est\b-estitm.w
copy z:\asi_gui9\pco400\est\b-estlst.r z:\asi9test\rco400\est\b-estlst.r
copy z:\asi_gui9\pco400\est\b-estlst.r z:\asi9ship\rco400\est\b-estlst.r
copy z:\asi_gui9\pco400\est\b-estlst.w z:\asi9test\pco400\est\b-estlst.w
copy z:\asi_gui9\pco400\est\b-qtchg2.r z:\asi9test\rco400\est\b-qtchg2.r
copy z:\asi_gui9\pco400\est\b-qtchg2.r z:\asi9ship\rco400\est\b-qtchg2.r
copy z:\asi_gui9\pco400\est\b-qtchg2.w z:\asi9test\pco400\est\b-qtchg2.w
copy z:\asi_gui9\pco400\est\b-qthd2.r z:\asi9test\rco400\est\b-qthd2.r
copy z:\asi_gui9\pco400\est\b-qthd2.r z:\asi9ship\rco400\est\b-qthd2.r
copy z:\asi_gui9\pco400\est\b-qthd2.w z:\asi9test\pco400\est\b-qthd2.w
copy z:\asi_gui9\pco400\est\b-quoit.r z:\asi9test\rco400\est\b-quoit.r
copy z:\asi_gui9\pco400\est\b-quoit.r z:\asi9ship\rco400\est\b-quoit.r
copy z:\asi_gui9\pco400\est\b-quoit.w z:\asi9test\pco400\est\b-quoit.w
copy z:\asi_gui9\pco400\est\b-quote.r z:\asi9test\rco400\est\b-quote.r
copy z:\asi_gui9\pco400\est\b-quote.r z:\asi9ship\rco400\est\b-quote.r
copy z:\asi_gui9\pco400\est\b-quote.w z:\asi9test\pco400\est\b-quote.w
copy z:\asi_gui9\pco400\est\b-quote1.r z:\asi9test\rco400\est\b-quote1.r
copy z:\asi_gui9\pco400\est\b-quote1.r z:\asi9ship\rco400\est\b-quote1.r
copy z:\asi_gui9\pco400\est\b-quote1.w z:\asi9test\pco400\est\b-quote1.w
copy z:\asi_gui9\pco400\fg\b-eitmfg.r z:\asi9test\rco400\fg\b-eitmfg.r
copy z:\asi_gui9\pco400\fg\b-eitmfg.r z:\asi9ship\rco400\fg\b-eitmfg.r
copy z:\asi_gui9\pco400\fg\b-eitmfg.w z:\asi9test\pco400\fg\b-eitmfg.w
copy z:\asi_gui9\pco400\fg\b-fg-set.r z:\asi9test\rco400\fg\b-fg-set.r
copy z:\asi_gui9\pco400\fg\b-fg-set.r z:\asi9ship\rco400\fg\b-fg-set.r
copy z:\asi_gui9\pco400\fg\b-fg-set.w z:\asi9test\pco400\fg\b-fg-set.w
copy z:\asi_gui9\pco400\fg\b-prdlin.r z:\asi9test\rco400\fg\b-prdlin.r
copy z:\asi_gui9\pco400\fg\b-prdlin.r z:\asi9ship\rco400\fg\b-prdlin.r
copy z:\asi_gui9\pco400\fg\b-prdlin.w z:\asi9test\pco400\fg\b-prdlin.w
copy z:\asi_gui9\pco400\fg\b-prodct.r z:\asi9test\rco400\fg\b-prodct.r
copy z:\asi_gui9\pco400\fg\b-prodct.r z:\asi9ship\rco400\fg\b-prodct.r
copy z:\asi_gui9\pco400\fg\b-prodct.w z:\asi9test\pco400\fg\b-prodct.w
copy z:\asi_gui9\pco400\fg\v-eitmfg.r z:\asi9test\rco400\fg\v-eitmfg.r
copy z:\asi_gui9\pco400\fg\v-eitmfg.r z:\asi9ship\rco400\fg\v-eitmfg.r
copy z:\asi_gui9\pco400\fg\v-eitmfg.w z:\asi9test\pco400\fg\v-eitmfg.w
copy z:\asi_gui9\pco400\gl\b-ccode.r z:\asi9test\rco400\gl\b-ccode.r
copy z:\asi_gui9\pco400\gl\b-ccode.r z:\asi9ship\rco400\gl\b-ccode.r
copy z:\asi_gui9\pco400\gl\b-ccode.w z:\asi9test\pco400\gl\b-ccode.w
copy z:\asi_gui9\pco400\jc\b-job.r z:\asi9test\rco400\jc\b-job.r
copy z:\asi_gui9\pco400\jc\b-job.r z:\asi9ship\rco400\jc\b-job.r
copy z:\asi_gui9\pco400\jc\b-job.w z:\asi9test\pco400\jc\b-job.w
copy z:\asi_gui9\pco400\jcinq\do-jobno_cl.r z:\asi9test\rco400\jcinq\do-jobno_cl.r
copy z:\asi_gui9\pco400\jcinq\do-jobno_cl.r z:\asi9ship\rco400\jcinq\do-jobno_cl.r
copy z:\asi_gui9\pco400\jcinq\do-jobno_cl.w z:\asi9test\pco400\jcinq\do-jobno_cl.w
copy z:\asi_gui9\pco400\lookups\i-nop.r z:\asi9test\rco400\lookups\i-nop.r
copy z:\asi_gui9\pco400\lookups\i-nop.r z:\asi9ship\rco400\lookups\i-nop.r
copy z:\asi_gui9\pco400\lookups\i-nop.p z:\asi9test\pco400\lookups\i-nop.p
copy z:\asi_gui9\pco400\lookups\itemfg.r z:\asi9test\rco400\lookups\itemfg.r
copy z:\asi_gui9\pco400\lookups\itemfg.r z:\asi9ship\rco400\lookups\itemfg.r
copy z:\asi_gui9\pco400\lookups\itemfg.p z:\asi9test\pco400\lookups\itemfg.p
copy z:\asi_gui9\pco400\oe\b-oebolh.r z:\asi9test\rco400\oe\b-oebolh.r
copy z:\asi_gui9\pco400\oe\b-oebolh.r z:\asi9ship\rco400\oe\b-oebolh.r
copy z:\asi_gui9\pco400\oe\b-oebolh.w z:\asi9test\pco400\oe\b-oebolh.w
copy z:\asi_gui9\pco400\oe\b-oewebq.r z:\asi9test\rco400\oe\b-oewebq.r
copy z:\asi_gui9\pco400\oe\b-oewebq.r z:\asi9ship\rco400\oe\b-oewebq.r
copy z:\asi_gui9\pco400\oe\b-oewebq.w z:\asi9test\pco400\oe\b-oewebq.w
copy z:\asi_gui9\pco400\oe\b-ord.r z:\asi9test\rco400\oe\b-ord.r
copy z:\asi_gui9\pco400\oe\b-ord.r z:\asi9ship\rco400\oe\b-ord.r
copy z:\asi_gui9\pco400\oe\b-ord.w z:\asi9test\pco400\oe\b-ord.w
copy z:\asi_gui9\pco400\oe\b-return.r z:\asi9test\rco400\oe\b-return.r
copy z:\asi_gui9\pco400\oe\b-return.r z:\asi9ship\rco400\oe\b-return.r
copy z:\asi_gui9\pco400\oe\b-return.w z:\asi9test\pco400\oe\b-return.w
copy z:\asi_gui9\pco400\oe\b-test2.r z:\asi9test\rco400\oe\b-test2.r
copy z:\asi_gui9\pco400\oe\b-test2.r z:\asi9ship\rco400\oe\b-test2.r
copy z:\asi_gui9\pco400\oe\b-test2.w z:\asi9test\pco400\oe\b-test2.w
copy z:\asi_gui9\pco400\oe\b-test3.2.r z:\asi9test\rco400\oe\b-test3.2.r
copy z:\asi_gui9\pco400\oe\b-test3.2.r z:\asi9ship\rco400\oe\b-test3.2.r
copy z:\asi_gui9\pco400\oe\b-test3.2.w z:\asi9test\pco400\oe\b-test3.2.w
copy z:\asi_gui9\pco400\oe\b-webord.r z:\asi9test\rco400\oe\b-webord.r
copy z:\asi_gui9\pco400\oe\b-webord.r z:\asi9ship\rco400\oe\b-webord.r
copy z:\asi_gui9\pco400\oe\b-webord.w z:\asi9test\pco400\oe\b-webord.w
copy z:\asi_gui9\pco400\oe\rep\bolcscin.r z:\asi9test\rco400\oe\rep\bolcscin.r
copy z:\asi_gui9\pco400\oe\rep\bolcscin.r z:\asi9ship\rco400\oe\rep\bolcscin.r
copy z:\asi_gui9\pco400\oe\rep\bolcscin.p z:\asi9test\pco400\oe\rep\bolcscin.p
copy z:\asi_gui9\pco400\pc\r-wipe&p.r z:\asi9test\rco400\pc\r-wipe&p.r
copy z:\asi_gui9\pco400\pc\r-wipe&p.r z:\asi9ship\rco400\pc\r-wipe&p.r
copy z:\asi_gui9\pco400\pc\r-wipe&p.w z:\asi9test\pco400\pc\r-wipe&p.w
copy z:\asi_gui9\pco400\pc\r-wipedt.r z:\asi9test\rco400\pc\r-wipedt.r
copy z:\asi_gui9\pco400\pc\r-wipedt.r z:\asi9ship\rco400\pc\r-wipedt.r
copy z:\asi_gui9\pco400\pc\r-wipedt.p z:\asi9test\pco400\pc\r-wipedt.p
copy z:\asi_gui9\pco400\po\b-purord.r z:\asi9test\rco400\po\b-purord.r
copy z:\asi_gui9\pco400\po\b-purord.r z:\asi9ship\rco400\po\b-purord.r
copy z:\asi_gui9\pco400\po\b-purord.w z:\asi9test\pco400\po\b-purord.w
copy z:\asi_gui9\pco400\rm\b-issue.r z:\asi9test\rco400\rm\b-issue.r
copy z:\asi_gui9\pco400\rm\b-issue.r z:\asi9ship\rco400\rm\b-issue.r
copy z:\asi_gui9\pco400\rm\b-issue.w z:\asi9test\pco400\rm\b-issue.w
copy z:\asi_gui9\pco400\rm\b-phycnt.r z:\asi9test\rco400\rm\b-phycnt.r
copy z:\asi_gui9\pco400\rm\b-phycnt.r z:\asi9ship\rco400\rm\b-phycnt.r
copy z:\asi_gui9\pco400\rm\b-phycnt.w z:\asi9test\pco400\rm\b-phycnt.w
copy z:\asi_gui9\pco400\rm\b-pstlst.r z:\asi9test\rco400\rm\b-pstlst.r
copy z:\asi_gui9\pco400\rm\b-pstlst.r z:\asi9ship\rco400\rm\b-pstlst.r
copy z:\asi_gui9\pco400\rm\b-pstlst.w z:\asi9test\pco400\rm\b-pstlst.w
copy z:\asi_gui9\pco400\rm\b-rcpt.r z:\asi9test\rco400\rm\b-rcpt.r
copy z:\asi_gui9\pco400\rm\b-rcpt.r z:\asi9ship\rco400\rm\b-rcpt.r
copy z:\asi_gui9\pco400\rm\b-rcpt.w z:\asi9test\pco400\rm\b-rcpt.w
copy z:\asi_gui9\pco400\rm\b-rctd.r z:\asi9test\rco400\rm\b-rctd.r
copy z:\asi_gui9\pco400\rm\b-rctd.r z:\asi9ship\rco400\rm\b-rctd.r
copy z:\asi_gui9\pco400\rm\b-rctd.w z:\asi9test\pco400\rm\b-rctd.w
copy z:\asi_gui9\pco400\rm\sc-issue.r z:\asi9test\rco400\rm\sc-issue.r
copy z:\asi_gui9\pco400\rm\sc-issue.r z:\asi9ship\rco400\rm\sc-issue.r
copy z:\asi_gui9\pco400\rm\sc-issue.w z:\asi9test\pco400\rm\sc-issue.w
copy z:\asi_gui9\pco400\rm\sc-rcpt.r z:\asi9test\rco400\rm\sc-rcpt.r
copy z:\asi_gui9\pco400\rm\sc-rcpt.r z:\asi9ship\rco400\rm\sc-rcpt.r
copy z:\asi_gui9\pco400\rm\sc-rcpt.w z:\asi9test\pco400\rm\sc-rcpt.w
copy z:\asi_gui9\pco400\salrep\s-slmprd.r z:\asi9test\rco400\salrep\s-slmprd.r
copy z:\asi_gui9\pco400\salrep\s-slmprd.r z:\asi9ship\rco400\salrep\s-slmprd.r
copy z:\asi_gui9\pco400\salrep\s-slmprd.p z:\asi9test\pco400\salrep\s-slmprd.p
copy z:\asi_gui9\pco400\sys\help\b-head.r z:\asi9test\rco400\sys\help\b-head.r
copy z:\asi_gui9\pco400\sys\help\b-head.r z:\asi9ship\rco400\sys\help\b-head.r
copy z:\asi_gui9\pco400\sys\help\b-head.w z:\asi9test\pco400\sys\help\b-head.w
copy z:\asi_gui9\pco400\sys\ref\d-passwd_adm1.r z:\asi9test\rco400\sys\ref\d-passwd_adm1.r
copy z:\asi_gui9\pco400\sys\ref\d-passwd_adm1.r z:\asi9ship\rco400\sys\ref\d-passwd_adm1.r
copy z:\asi_gui9\pco400\sys\ref\d-passwd_adm1.w z:\asi9test\pco400\sys\ref\d-passwd_adm1.w
copy z:\asi_gui9\pco400\util\mkfginks.r z:\asi9test\rco400\util\mkfginks.r
copy z:\asi_gui9\pco400\util\mkfginks.r z:\asi9ship\rco400\util\mkfginks.r
copy z:\asi_gui9\pco400\util\mkfginks.p z:\asi9test\pco400\util\mkfginks.p
copy z:\asi_gui9\pco400\write.trg\mch-act.r z:\asi9test\rco400\write.trg\mch-act.r
copy z:\asi_gui9\pco400\write.trg\mch-act.r z:\asi9ship\rco400\write.trg\mch-act.r
copy z:\asi_gui9\pco400\write.trg\mch-act.p z:\asi9test\pco400\write.trg\mch-act.p
