/* est-op.p - generated 01/10/2001 - 13:00:02 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_est-op1 NO-UNDO LIKE est-op.
DEFINE WORK-TABLE ttbl_est-op2 NO-UNDO LIKE est-op.

CREATE ttbl_est-op1.
IMPORT STREAM s_audit_file ttbl_est-op1.
CREATE ttbl_est-op2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_est-op2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_est-op1.auto NE ttbl_est-op2.auto OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_est-op1.auto FORMAT "Y/N" " (auto)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.auto NE ttbl_est-op2.auto THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_est-op2.auto FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.b-num NE ttbl_est-op2.b-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Blank #: " AT 3 ttbl_est-op1.b-num FORMAT ">9" " (b-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.b-num NE ttbl_est-op2.b-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Blank #: " AT 3 ttbl_est-op2.b-num FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.d-seq NE ttbl_est-op2.d-seq OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Dept. Sequence: " AT 3 ttbl_est-op1.d-seq FORMAT ">9" " (d-seq)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.d-seq NE ttbl_est-op2.d-seq THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Dept. Sequence: " AT 3 ttbl_est-op2.d-seq FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.dept NE ttbl_est-op2.dept OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Department: " AT 3 ttbl_est-op1.dept " (dept)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.dept NE ttbl_est-op2.dept THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Department: " AT 3 ttbl_est-op2.dept.
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.e-num NE ttbl_est-op2.e-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Est.#: " AT 3 ttbl_est-op1.e-num FORMAT ">>>>>>>9" " (e-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.e-num NE ttbl_est-op2.e-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Est.#: " AT 3 ttbl_est-op2.e-num FORMAT ">>>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.est-no NE ttbl_est-op2.est-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate#: " AT 3 ttbl_est-op1.est-no " (est-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.est-no NE ttbl_est-op2.est-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Estimate#: " AT 3 ttbl_est-op2.est-no.
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.line NE ttbl_est-op2.line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Line #: " AT 3 ttbl_est-op1.line FORMAT ">9" " (line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.line NE ttbl_est-op2.line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Line #: " AT 3 ttbl_est-op2.line FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.m-code NE ttbl_est-op2.m-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 3 ttbl_est-op1.m-code " (m-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.m-code NE ttbl_est-op2.m-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 3 ttbl_est-op2.m-code.
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.m-dscr NE ttbl_est-op2.m-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Description: " AT 3 ttbl_est-op1.m-dscr " (m-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.m-dscr NE ttbl_est-op2.m-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Description: " AT 3 ttbl_est-op2.m-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.n-out NE ttbl_est-op2.n-out OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Number Out: " AT 3 ttbl_est-op1.n-out FORMAT ">>9" " (n-out)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.n-out NE ttbl_est-op2.n-out THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Number Out: " AT 3 ttbl_est-op2.n-out FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.num-coat NE ttbl_est-op2.num-coat OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Number of Coatings: " AT 3 ttbl_est-op1.num-coat FORMAT ">9" " (num-coat)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.num-coat NE ttbl_est-op2.num-coat THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Number of Coatings: " AT 3 ttbl_est-op2.num-coat FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.num-col NE ttbl_est-op2.num-col OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Number of Colors: " AT 3 ttbl_est-op1.num-col FORMAT ">9" " (num-col)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.num-col NE ttbl_est-op2.num-col THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Number of Colors: " AT 3 ttbl_est-op2.num-col FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.num-sh NE ttbl_est-op2.num-sh OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "# of Sheets: " AT 3 ttbl_est-op1.num-sh FORMAT ">,>>>,>>9" " (num-sh)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.num-sh NE ttbl_est-op2.num-sh THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "# of Sheets: " AT 3 ttbl_est-op2.num-sh FORMAT ">,>>>,>>9".
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_est-op1.op-crew[i] NE ttbl_est-op2.op-crew[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_est-op1.op-crew[i] FORMAT "9.99" " (op-crew[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-crew[i] NE ttbl_est-op2.op-crew[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_est-op2.op-crew[i] FORMAT "9.99".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_est-op1.op-mr NE ttbl_est-op2.op-mr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "MRhrs.: " AT 3 ttbl_est-op1.op-mr FORMAT ">>9.99" " (op-mr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-mr NE ttbl_est-op2.op-mr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "MRhrs.: " AT 3 ttbl_est-op2.op-mr FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.op-pass NE ttbl_est-op2.op-pass OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Pass #: " AT 3 ttbl_est-op1.op-pass FORMAT ">9" " (op-pass)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-pass NE ttbl_est-op2.op-pass THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Pass #: " AT 3 ttbl_est-op2.op-pass FORMAT ">9".
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_est-op1.op-rate[i] NE ttbl_est-op2.op-rate[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Rate[" AT 3 i "]: " ttbl_est-op1.op-rate[i] FORMAT ">>9.99" " (op-rate[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-rate[i] NE ttbl_est-op2.op-rate[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Rate[" AT 3 i "]: " ttbl_est-op2.op-rate[i] FORMAT ">>9.99".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_est-op1.op-sb NE ttbl_est-op2.op-sb OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED ": " AT 3 ttbl_est-op1.op-sb FORMAT "Y/N" " (op-sb)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-sb NE ttbl_est-op2.op-sb THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED ": " AT 3 ttbl_est-op2.op-sb FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.op-speed NE ttbl_est-op2.op-speed OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Speed: " AT 3 ttbl_est-op1.op-speed FORMAT ">>>>9" " (op-speed)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-speed NE ttbl_est-op2.op-speed THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Speed: " AT 3 ttbl_est-op2.op-speed FORMAT ">>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.op-spoil NE ttbl_est-op2.op-spoil OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Spoil%: " AT 3 ttbl_est-op1.op-spoil FORMAT ">>9.99" " (op-spoil)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-spoil NE ttbl_est-op2.op-spoil THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Spoil%: " AT 3 ttbl_est-op2.op-spoil FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.op-waste NE ttbl_est-op2.op-waste OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Waste: " AT 3 ttbl_est-op1.op-waste FORMAT ">>>>>9" " (op-waste)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.op-waste NE ttbl_est-op2.op-waste THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Waste: " AT 3 ttbl_est-op2.op-waste FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.qty NE ttbl_est-op2.qty OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_est-op1.qty FORMAT "->,>>>,>>9" " (qty)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.qty NE ttbl_est-op2.qty THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_est-op2.qty FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_est-op1.s-num NE ttbl_est-op2.s-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Sheet #: " AT 3 ttbl_est-op1.s-num FORMAT ">9" " (s-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_est-op1.s-num NE ttbl_est-op2.s-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Sheet #: " AT 3 ttbl_est-op2.s-num FORMAT ">9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Est.#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op2.e-num FORMAT ">>>>>>>9" " (e-num)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op1.e-num FORMAT ">>>>>>>9" " (e-num)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op2.qty FORMAT "->,>>>,>>9" " (qty)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op1.qty FORMAT "->,>>>,>>9" " (qty)".
  PUT STREAM s-audit-rpt UNFORMATTED "Sheet #: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op2.s-num FORMAT ">9" " (s-num)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op1.s-num FORMAT ">9" " (s-num)".
  PUT STREAM s-audit-rpt UNFORMATTED "Dept. Sequence: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op2.d-seq FORMAT ">9" " (d-seq)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op1.d-seq FORMAT ">9" " (d-seq)".
  PUT STREAM s-audit-rpt UNFORMATTED "Blank #: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op2.b-num FORMAT ">9" " (b-num)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op1.b-num FORMAT ">9" " (b-num)".
  PUT STREAM s-audit-rpt UNFORMATTED "Pass #: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op2.op-pass FORMAT ">9" " (op-pass)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_est-op1.op-pass FORMAT ">9" " (op-pass)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
