/* gl-ctrl.p - generated 01/10/2001 - 13:00:03 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_gl-ctrl1 NO-UNDO LIKE gl-ctrl.
DEFINE WORK-TABLE ttbl_gl-ctrl2 NO-UNDO LIKE gl-ctrl.

CREATE ttbl_gl-ctrl1.
IMPORT STREAM s_audit_file ttbl_gl-ctrl1.
CREATE ttbl_gl-ctrl2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_gl-ctrl2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_gl-ctrl1.company NE ttbl_gl-ctrl2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_gl-ctrl1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.company NE ttbl_gl-ctrl2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_gl-ctrl2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_gl-ctrl1.con-dscr NE ttbl_gl-ctrl2.con-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl1.con-dscr " (con-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.con-dscr NE ttbl_gl-ctrl2.con-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl2.con-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_gl-ctrl1.contra NE ttbl_gl-ctrl2.contra OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "P/L Contra: " AT 3 ttbl_gl-ctrl1.contra " (contra)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.contra NE ttbl_gl-ctrl2.contra THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "P/L Contra: " AT 3 ttbl_gl-ctrl2.contra.
  END.
END.
IF NOT v_field_changed OR ttbl_gl-ctrl1.journal NE ttbl_gl-ctrl2.journal OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl1.journal FORMAT ">>>>>>9" " (journal)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.journal NE ttbl_gl-ctrl2.journal THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl2.journal FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_gl-ctrl1.ret NE ttbl_gl-ctrl2.ret OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Retained Earnings: " AT 3 ttbl_gl-ctrl1.ret " (ret)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.ret NE ttbl_gl-ctrl2.ret THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Retained Earnings: " AT 3 ttbl_gl-ctrl2.ret.
  END.
END.
IF NOT v_field_changed OR ttbl_gl-ctrl1.ret-dscr NE ttbl_gl-ctrl2.ret-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl1.ret-dscr " (ret-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.ret-dscr NE ttbl_gl-ctrl2.ret-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl2.ret-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_gl-ctrl1.trnum NE ttbl_gl-ctrl2.trnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl1.trnum FORMAT ">>>>>>9" " (trnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_gl-ctrl1.trnum NE ttbl_gl-ctrl2.trnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_gl-ctrl2.trnum FORMAT ">>>>>>9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_gl-ctrl2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_gl-ctrl1.company " (company)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
