/* inv-misc.p - generated 01/10/2001 - 13:00:03 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_inv-misc1 NO-UNDO LIKE inv-misc.
DEFINE WORK-TABLE ttbl_inv-misc2 NO-UNDO LIKE inv-misc.

CREATE ttbl_inv-misc1.
IMPORT STREAM s_audit_file ttbl_inv-misc1.
CREATE ttbl_inv-misc2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_inv-misc2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_inv-misc1.actnum NE ttbl_inv-misc2.actnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_inv-misc1.actnum " (actnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.actnum NE ttbl_inv-misc2.actnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_inv-misc2.actnum.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.amt NE ttbl_inv-misc2.amt OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Amount: " AT 3 ttbl_inv-misc1.amt FORMAT "->>>,>>9.99" " (amt)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.amt NE ttbl_inv-misc2.amt THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Amount: " AT 3 ttbl_inv-misc2.amt FORMAT "->>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.bill NE ttbl_inv-misc2.bill OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bill: " AT 3 ttbl_inv-misc1.bill " (bill)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.bill NE ttbl_inv-misc2.bill THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bill: " AT 3 ttbl_inv-misc2.bill.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.charge NE ttbl_inv-misc2.charge OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Charge: " AT 3 ttbl_inv-misc1.charge " (charge)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.charge NE ttbl_inv-misc2.charge THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Charge: " AT 3 ttbl_inv-misc2.charge.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.company NE ttbl_inv-misc2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_inv-misc1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.company NE ttbl_inv-misc2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_inv-misc2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.cost NE ttbl_inv-misc2.cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cost: " AT 3 ttbl_inv-misc1.cost FORMAT "->>,>>>,>>9.99" " (cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.cost NE ttbl_inv-misc2.cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cost: " AT 3 ttbl_inv-misc2.cost FORMAT "->>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.deleted NE ttbl_inv-misc2.deleted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Deleted?: " AT 3 ttbl_inv-misc1.deleted FORMAT "Y/N" " (deleted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.deleted NE ttbl_inv-misc2.deleted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Deleted?: " AT 3 ttbl_inv-misc2.deleted FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.dscr NE ttbl_inv-misc2.dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Description: " AT 3 ttbl_inv-misc1.dscr " (dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.dscr NE ttbl_inv-misc2.dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Description: " AT 3 ttbl_inv-misc2.dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.est-no NE ttbl_inv-misc2.est-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate#: " AT 3 ttbl_inv-misc1.est-no " (est-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.est-no NE ttbl_inv-misc2.est-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Estimate#: " AT 3 ttbl_inv-misc2.est-no.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.inv-i-no NE ttbl_inv-misc2.inv-i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Invoice Line Item: " AT 3 ttbl_inv-misc1.inv-i-no " (inv-i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.inv-i-no NE ttbl_inv-misc2.inv-i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Invoice Line Item: " AT 3 ttbl_inv-misc2.inv-i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.inv-line NE ttbl_inv-misc2.inv-line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Invoice Line: " AT 3 ttbl_inv-misc1.inv-line FORMAT ">9" " (inv-line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.inv-line NE ttbl_inv-misc2.inv-line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Invoice Line: " AT 3 ttbl_inv-misc2.inv-line FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.line NE ttbl_inv-misc2.line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 3 ttbl_inv-misc1.line FORMAT ">9" " (line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.line NE ttbl_inv-misc2.line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 3 ttbl_inv-misc2.line FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.ord-no NE ttbl_inv-misc2.ord-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Order#: " AT 3 ttbl_inv-misc1.ord-no FORMAT ">>>>>9" " (ord-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.ord-no NE ttbl_inv-misc2.ord-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Order#: " AT 3 ttbl_inv-misc2.ord-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.posted NE ttbl_inv-misc2.posted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_inv-misc1.posted FORMAT "y/n" " (posted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.posted NE ttbl_inv-misc2.posted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_inv-misc2.posted FORMAT "y/n".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.r-no NE ttbl_inv-misc2.r-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Unique Internal Number: " AT 3 ttbl_inv-misc1.r-no FORMAT ">>>>>>>9" " (r-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.r-no NE ttbl_inv-misc2.r-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Unique Internal Number: " AT 3 ttbl_inv-misc2.r-no FORMAT ">>>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_inv-misc1.tax NE ttbl_inv-misc2.tax OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Tax: " AT 3 ttbl_inv-misc1.tax FORMAT "Y/N" " (tax)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_inv-misc1.tax NE ttbl_inv-misc2.tax THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Tax: " AT 3 ttbl_inv-misc2.tax FORMAT "Y/N".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Unique Internal Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_inv-misc2.r-no FORMAT ">>>>>>>9" " (r-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_inv-misc1.r-no FORMAT ">>>>>>>9" " (r-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_inv-misc2.line FORMAT ">9" " (line)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_inv-misc1.line FORMAT ">9" " (line)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
