/* oe-ship.p - generated 01/10/2001 - 13:00:07 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_oe-ship1 NO-UNDO LIKE oe-ship.
DEFINE WORK-TABLE ttbl_oe-ship2 NO-UNDO LIKE oe-ship.

CREATE ttbl_oe-ship1.
IMPORT STREAM s_audit_file ttbl_oe-ship1.
CREATE ttbl_oe-ship2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_oe-ship2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_oe-ship1.b-no NE ttbl_oe-ship2.b-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.b-no FORMAT ">>>>>9" " (b-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.b-no NE ttbl_oe-ship2.b-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.b-no FORMAT ">>>>>9".
  END.
END.
DO i = 1 TO 4:
IF NOT v_field_changed OR ttbl_oe-ship1.bill-i[i] NE ttbl_oe-ship2.bill-i[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_oe-ship1.bill-i[i] " (bill-i[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.bill-i[i] NE ttbl_oe-ship2.bill-i[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_oe-ship2.bill-i[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.bol-no NE ttbl_oe-ship2.bol-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.bol-no " (bol-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.bol-no NE ttbl_oe-ship2.bol-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.bol-no.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.carrier NE ttbl_oe-ship2.carrier OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Carrier: " AT 3 ttbl_oe-ship1.carrier " (carrier)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.carrier NE ttbl_oe-ship2.carrier THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Carrier: " AT 3 ttbl_oe-ship2.carrier.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.cases NE ttbl_oe-ship2.cases OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.cases FORMAT ">>>,>>9" " (cases)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.cases NE ttbl_oe-ship2.cases THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.cases FORMAT ">>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.company NE ttbl_oe-ship2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_oe-ship1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.company NE ttbl_oe-ship2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_oe-ship2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.cust-no NE ttbl_oe-ship2.cust-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 3 ttbl_oe-ship1.cust-no " (cust-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.cust-no NE ttbl_oe-ship2.cust-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 3 ttbl_oe-ship2.cust-no.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.dest-code NE ttbl_oe-ship2.dest-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Dest. Code: " AT 3 ttbl_oe-ship1.dest-code " (dest-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.dest-code NE ttbl_oe-ship2.dest-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Dest. Code: " AT 3 ttbl_oe-ship2.dest-code.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.hold NE ttbl_oe-ship2.hold OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.hold FORMAT "yes/no" " (hold)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.hold NE ttbl_oe-ship2.hold THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.hold FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.i-no NE ttbl_oe-ship2.i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 3 ttbl_oe-ship1.i-no " (i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.i-no NE ttbl_oe-ship2.i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 3 ttbl_oe-ship2.i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.line NE ttbl_oe-ship2.line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 3 ttbl_oe-ship1.line FORMAT "99" " (line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.line NE ttbl_oe-ship2.line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 3 ttbl_oe-ship2.line FORMAT "99".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.loc NE ttbl_oe-ship2.loc OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Warehouse: " AT 3 ttbl_oe-ship1.loc " (loc)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.loc NE ttbl_oe-ship2.loc THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Warehouse: " AT 3 ttbl_oe-ship2.loc.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.loc-bin NE ttbl_oe-ship2.loc-bin OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Primary Bin Loc.: " AT 3 ttbl_oe-ship1.loc-bin " (loc-bin)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.loc-bin NE ttbl_oe-ship2.loc-bin THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Primary Bin Loc.: " AT 3 ttbl_oe-ship2.loc-bin.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.o-no NE ttbl_oe-ship2.o-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.o-no FORMAT ">>>>>9" " (o-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.o-no NE ttbl_oe-ship2.o-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.o-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.ord-no NE ttbl_oe-ship2.ord-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Order#: " AT 3 ttbl_oe-ship1.ord-no FORMAT ">>>>>9" " (ord-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.ord-no NE ttbl_oe-ship2.ord-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Order#: " AT 3 ttbl_oe-ship2.ord-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.partial NE ttbl_oe-ship2.partial OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.partial FORMAT ">>>,>>9" " (partial)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.partial NE ttbl_oe-ship2.partial THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.partial FORMAT ">>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.po-no NE ttbl_oe-ship2.po-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.po-no " (po-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.po-no NE ttbl_oe-ship2.po-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.po-no.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.qty NE ttbl_oe-ship2.qty OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.qty FORMAT "->>,>>>,>>9" " (qty)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.qty NE ttbl_oe-ship2.qty THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.qty FORMAT "->>,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.qty-case NE ttbl_oe-ship2.qty-case OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.qty-case FORMAT ">>>,>>9" " (qty-case)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.qty-case NE ttbl_oe-ship2.qty-case THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.qty-case FORMAT ">>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.r-no NE ttbl_oe-ship2.r-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.r-no FORMAT ">>>>>9" " (r-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.r-no NE ttbl_oe-ship2.r-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.r-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.rel-date NE ttbl_oe-ship2.rel-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Date Last Counted: " AT 3 ttbl_oe-ship1.rel-date FORMAT "99/99/99" " (rel-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.rel-date NE ttbl_oe-ship2.rel-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Date Last Counted: " AT 3 ttbl_oe-ship2.rel-date FORMAT "99/99/99".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.rel-no NE ttbl_oe-ship2.rel-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.rel-no FORMAT ">>>>>9" " (rel-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.rel-no NE ttbl_oe-ship2.rel-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.rel-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.s-comm NE ttbl_oe-ship2.s-comm OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Commission: " AT 3 ttbl_oe-ship1.s-comm FORMAT ">>9.99" " (s-comm)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.s-comm NE ttbl_oe-ship2.s-comm THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Commission: " AT 3 ttbl_oe-ship2.s-comm FORMAT ">>9.99".
  END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_oe-ship1.s-name[i] NE ttbl_oe-ship2.s-name[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Salesman Name[" AT 3 i "]: " ttbl_oe-ship1.s-name[i] " (s-name[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.s-name[i] NE ttbl_oe-ship2.s-name[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Salesman Name[" AT 3 i "]: " ttbl_oe-ship2.s-name[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.s-no NE ttbl_oe-ship2.s-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.s-no FORMAT ">9" " (s-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.s-no NE ttbl_oe-ship2.s-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.s-no FORMAT ">9".
  END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_oe-ship1.s-pct[i] NE ttbl_oe-ship2.s-pct[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Percentage[" AT 3 i "]: " ttbl_oe-ship1.s-pct[i] FORMAT ">9.99" " (s-pct[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.s-pct[i] NE ttbl_oe-ship2.s-pct[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Percentage[" AT 3 i "]: " ttbl_oe-ship2.s-pct[i] FORMAT ">9.99".
  END.
END.
END.
DO i = 1 TO 4:
IF NOT v_field_changed OR ttbl_oe-ship1.ship-i[i] NE ttbl_oe-ship2.ship-i[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_oe-ship1.ship-i[i] " (ship-i[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.ship-i[i] NE ttbl_oe-ship2.ship-i[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_oe-ship2.ship-i[i].
  END.
END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_oe-ship1.sman[i] NE ttbl_oe-ship2.sman[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Salesman Code[" AT 3 i "]: " ttbl_oe-ship1.sman[i] " (sman[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.sman[i] NE ttbl_oe-ship2.sman[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Salesman Code[" AT 3 i "]: " ttbl_oe-ship2.sman[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.tag NE ttbl_oe-ship2.tag OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.tag " (tag)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.tag NE ttbl_oe-ship2.tag THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.tag.
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.tot-qty NE ttbl_oe-ship2.tot-qty OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.tot-qty FORMAT "->>,>>>,>>9" " (tot-qty)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.tot-qty NE ttbl_oe-ship2.tot-qty THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.tot-qty FORMAT "->>,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_oe-ship1.trailer NE ttbl_oe-ship2.trailer OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship1.trailer " (trailer)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_oe-ship1.trailer NE ttbl_oe-ship2.trailer THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_oe-ship2.trailer.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_oe-ship2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_oe-ship1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_oe-ship2.bol-no " (bol-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_oe-ship1.bol-no " (bol-no)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
