/* pc-prdh.p - generated 01/10/2001 - 13:00:07 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_pc-prdh1 NO-UNDO LIKE pc-prdh.
DEFINE WORK-TABLE ttbl_pc-prdh2 NO-UNDO LIKE pc-prdh.

CREATE ttbl_pc-prdh1.
IMPORT STREAM s_audit_file ttbl_pc-prdh1.
CREATE ttbl_pc-prdh2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_pc-prdh2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_pc-prdh1.bc-m-code NE ttbl_pc-prdh2.bc-m-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pc-prdh1.bc-m-code " (bc-m-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pc-prdh1.bc-m-code NE ttbl_pc-prdh2.bc-m-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pc-prdh2.bc-m-code.
  END.
END.
IF NOT v_field_changed OR ttbl_pc-prdh1.company NE ttbl_pc-prdh2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_pc-prdh1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pc-prdh1.company NE ttbl_pc-prdh2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_pc-prdh2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_pc-prdh1.m-code NE ttbl_pc-prdh2.m-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 3 ttbl_pc-prdh1.m-code " (m-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pc-prdh1.m-code NE ttbl_pc-prdh2.m-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 3 ttbl_pc-prdh2.m-code.
  END.
END.
IF NOT v_field_changed OR ttbl_pc-prdh1.shift NE ttbl_pc-prdh2.shift OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Shift: " AT 3 ttbl_pc-prdh1.shift FORMAT "9" " (shift)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pc-prdh1.shift NE ttbl_pc-prdh2.shift THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Shift: " AT 3 ttbl_pc-prdh2.shift FORMAT "9".
  END.
END.
IF NOT v_field_changed OR ttbl_pc-prdh1.trans-date NE ttbl_pc-prdh2.trans-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pc-prdh1.trans-date FORMAT "99/99/99" " (trans-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pc-prdh1.trans-date NE ttbl_pc-prdh2.trans-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pc-prdh2.trans-date FORMAT "99/99/99".
  END.
END.
IF NOT v_field_changed OR ttbl_pc-prdh1.user-id NE ttbl_pc-prdh2.user-id OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 3 ttbl_pc-prdh1.user-id " (user-id)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pc-prdh1.user-id NE ttbl_pc-prdh2.user-id THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 3 ttbl_pc-prdh2.user-id.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh2.m-code " (m-code)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh1.m-code " (m-code)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh2.trans-date FORMAT "99/99/99" " (trans-date)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh1.trans-date FORMAT "99/99/99" " (trans-date)".
  PUT STREAM s-audit-rpt UNFORMATTED "Shift: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh2.shift FORMAT "9" " (shift)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pc-prdh1.shift FORMAT "9" " (shift)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
