/* RCErr.p - generated 01/10/2001 - 13:00:08 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_RCErr1 NO-UNDO LIKE RCErr.
DEFINE WORK-TABLE ttbl_RCErr2 NO-UNDO LIKE RCErr.

CREATE ttbl_RCErr1.
IMPORT STREAM s_audit_file ttbl_RCErr1.
CREATE ttbl_RCErr2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_RCErr2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_RCErr1.App NE ttbl_RCErr2.App OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr1.App " (App)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_RCErr1.App NE ttbl_RCErr2.App THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr2.App.
  END.
END.
IF NOT v_field_changed OR ttbl_RCErr1.Erc NE ttbl_RCErr2.Erc OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr1.Erc FORMAT ">>>>9" " (Erc)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_RCErr1.Erc NE ttbl_RCErr2.Erc THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr2.Erc FORMAT ">>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_RCErr1.Errmsg NE ttbl_RCErr2.Errmsg OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr1.Errmsg " (Errmsg)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_RCErr1.Errmsg NE ttbl_RCErr2.Errmsg THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr2.Errmsg.
  END.
END.
DO i = 1 TO 10:
IF NOT v_field_changed OR ttbl_RCErr1.Solution[i] NE ttbl_RCErr2.Solution[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_RCErr1.Solution[i] " (Solution[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_RCErr1.Solution[i] NE ttbl_RCErr2.Solution[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_RCErr2.Solution[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_RCErr1.Solution-type NE ttbl_RCErr2.Solution-type OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr1.Solution-type " (Solution-type)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_RCErr1.Solution-type NE ttbl_RCErr2.Solution-type THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_RCErr2.Solution-type.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_RCErr2.Erc FORMAT ">>>>9" " (Erc)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_RCErr1.Erc FORMAT ">>>>9" " (Erc)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_RCErr2.App " (App)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_RCErr1.App " (App)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
