/* rm-rcpt.i */

DEFINE {&NEW} SHARED VARIABLE s-i-no AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-job-no AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-job-no2 AS INTEGER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-i-name AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-recid AS RECID NO-UNDO.
