/* sortByDefs.i - rstark - 12.8.2018 */

DEFINE VARIABLE cColumnLabel AS CHARACTER NO-UNDO {1}.
DEFINE VARIABLE cSaveLabel   AS CHARACTER NO-UNDO {1}.
DEFINE VARIABLE lAscending   AS LOGICAL   NO-UNDO INITIAL YES.
