/* scheduleID.p - holds the selected ID value for smart objects to find */

DEFINE VARIABLE ID AS CHARACTER NO-UNDO.
DEFINE VARIABLE scenario AS CHARACTER NO-UNDO.

PROCEDURE setValues:
  DEFINE INPUT PARAMETER ipID AS CHARACTER NO-UNDO.
  DEFINE INPUT PARAMETER ipscenario AS CHARACTER NO-UNDO.
  ASSIGN
    ID = ipID
    scenario = ipScenario.
END PROCEDURE.

PROCEDURE ID:
  DEFINE OUTPUT PARAMETER opID AS CHARACTER NO-UNDO.
  opID = ID.
END PROCEDURE.

PROCEDURE scenario:
  DEFINE OUTPUT PARAMETER opScenario AS CHARACTER NO-UNDO.
  opScenario = scenario.
END PROCEDURE.
