/**********************************************************************
 * Copyright (C) 2006-2015 by Consultingwerk Ltd. ("CW") -            *
 * www.consultingwerk.de and other contributors as listed             *
 * below.  All Rights Reserved.                                       *
 *                                                                    *
 *  Software is distributed on an "AS IS", WITHOUT WARRANTY OF ANY    *
 *   KIND, either express or implied.                                 *
 *                                                                    *
 *  Contributors:                                                     *
 *                                                                    *
 **********************************************************************/
/*------------------------------------------------------------------------
    File        : Int64ArrayHolder
    Purpose     : Holder class for Array. Supports manipualtion methods on 
                  the array
    Syntax      : 
    Description : 
    Author(s)   : Mike Fechner / Consultingwerk Ltd.
    Created     : Wed Aug 05 00:36:56 CEST 2015
    Notes       : SCL-941, see also CharacterArrayHolder, DateArrayHolder,
                  DateTimeArrayHolder, DateTimeTzArrayHolder, DecimalArrayHolder, 
                  HandleArrayHolder, Int64ArrayHolder, IntegerArrayHolder, 
                  LogicalArrayHolder, ObjectArrayHolder
  ----------------------------------------------------------------------*/

&GLOBAL-DEFINE DataType INT64
&GLOBAL-DEFINE ClassNamePrefix Int64

{Consultingwerk/ArrayHolder.i}
