  FIELD deviceName LIKE userLog.deviceName~
  FIELD EulaVersion LIKE userLog.EulaVersion~
  FIELD IpAddress LIKE userLog.IpAddress~
  FIELD loginDateTime LIKE userLog.loginDateTime~
  FIELD logoutDateTime LIKE userLog.logoutDateTime~
  FIELD rec_key LIKE userLog.rec_key~
  FIELD sessionID LIKE userLog.sessionID~
  FIELD userName LIKE userLog.userName~
  FIELD userStatus LIKE userLog.userStatus~
  FIELD user_id LIKE userLog.user_id
