/* winReSize.i */

DEFINE VARIABLE rowDiff       AS DECIMAL   NO-UNDO.
DEFINE VARIABLE colDiff       AS DECIMAL   NO-UNDO.
DEFINE VARIABLE winReSize     AS LOGICAL   NO-UNDO.
DEFINE VARIABLE winObjects    AS CHARACTER NO-UNDO.
DEFINE VARIABLE iPage1RowDiff AS DECIMAL   NO-UNDO.
DEFINE VARIABLE iPage1ColDiff AS DECIMAL   NO-UNDO.
