/* account.p - generated 01/10/2001 - 12:59:57 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_account1 NO-UNDO LIKE account.
DEFINE WORK-TABLE ttbl_account2 NO-UNDO LIKE account.

CREATE ttbl_account1.
IMPORT STREAM s_audit_file ttbl_account1.
CREATE ttbl_account2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_account2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_account1.actnum NE ttbl_account2.actnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_account1.actnum " (actnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.actnum NE ttbl_account2.actnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_account2.actnum.
  END.
END.
DO i = 1 TO 13:
IF NOT v_field_changed OR ttbl_account1.bud[i] NE ttbl_account2.bud[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_account1.bud[i] FORMAT "->>>,>>>,>>>,>>9.99" " (bud[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.bud[i] NE ttbl_account2.bud[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_account2.bud[i] FORMAT "->>>,>>>,>>>,>>9.99".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_account1.company NE ttbl_account2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_account1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.company NE ttbl_account2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_account2.company.
  END.
END.
DO i = 1 TO 13:
IF NOT v_field_changed OR ttbl_account1.cyr[i] NE ttbl_account2.cyr[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_account1.cyr[i] FORMAT "->>>,>>>,>>>,>>9.99" " (cyr[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.cyr[i] NE ttbl_account2.cyr[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_account2.cyr[i] FORMAT "->>>,>>>,>>>,>>9.99".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_account1.cyr-open NE ttbl_account2.cyr-open OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cur Year Open Bal: " AT 3 ttbl_account1.cyr-open FORMAT "->>>,>>>,>>>,>>9.99" " (cyr-open)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.cyr-open NE ttbl_account2.cyr-open THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cur Year Open Bal: " AT 3 ttbl_account2.cyr-open FORMAT "->>>,>>>,>>>,>>9.99".
  END.
END.
DO i = 1 TO 10:
IF NOT v_field_changed OR ttbl_account1.dist-actnum[i] NE ttbl_account2.dist-actnum[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Distribution Account[" AT 3 i "]: " ttbl_account1.dist-actnum[i] " (dist-actnum[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.dist-actnum[i] NE ttbl_account2.dist-actnum[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Distribution Account[" AT 3 i "]: " ttbl_account2.dist-actnum[i].
  END.
END.
END.
DO i = 1 TO 10:
IF NOT v_field_changed OR ttbl_account1.dist-percent[i] NE ttbl_account2.dist-percent[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Distribution Percent[" AT 3 i "]: " ttbl_account1.dist-percent[i] FORMAT ">>9.99" " (dist-percent[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.dist-percent[i] NE ttbl_account2.dist-percent[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Distribution Percent[" AT 3 i "]: " ttbl_account2.dist-percent[i] FORMAT ">>9.99".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_account1.dscr NE ttbl_account2.dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Desc: " AT 3 ttbl_account1.dscr " (dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.dscr NE ttbl_account2.dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Desc: " AT 3 ttbl_account2.dscr.
  END.
END.
DO i = 1 TO 13:
IF NOT v_field_changed OR ttbl_account1.lyr[i] NE ttbl_account2.lyr[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_account1.lyr[i] FORMAT "->>>,>>>,>>>,>>9.99" " (lyr[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.lyr[i] NE ttbl_account2.lyr[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?[" AT 3 i "]: " ttbl_account2.lyr[i] FORMAT "->>>,>>>,>>>,>>9.99".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_account1.lyr-open NE ttbl_account2.lyr-open OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Last Year Open: " AT 3 ttbl_account1.lyr-open FORMAT "->>>,>>>,>>>,>>9.99" " (lyr-open)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.lyr-open NE ttbl_account2.lyr-open THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Last Year Open: " AT 3 ttbl_account2.lyr-open FORMAT "->>>,>>>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.multi-dist NE ttbl_account2.multi-dist OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Multiple GL Distribution: " AT 3 ttbl_account1.multi-dist FORMAT "Y/N" " (multi-dist)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.multi-dist NE ttbl_account2.multi-dist THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Multiple GL Distribution: " AT 3 ttbl_account2.multi-dist FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.n1 NE ttbl_account2.n1 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "N1: " AT 3 ttbl_account1.n1 FORMAT ">9" " (n1)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.n1 NE ttbl_account2.n1 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "N1: " AT 3 ttbl_account2.n1 FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.n2 NE ttbl_account2.n2 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "N2: " AT 3 ttbl_account1.n2 FORMAT ">>>>>9" " (n2)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.n2 NE ttbl_account2.n2 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "N2: " AT 3 ttbl_account2.n2 FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.n3 NE ttbl_account2.n3 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "N3: " AT 3 ttbl_account1.n3 FORMAT ">>9" " (n3)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.n3 NE ttbl_account2.n3 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "N3: " AT 3 ttbl_account2.n3 FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.n4 NE ttbl_account2.n4 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "N4: " AT 3 ttbl_account1.n4 FORMAT ">>>>>9" " (n4)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.n4 NE ttbl_account2.n4 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "N4: " AT 3 ttbl_account2.n4 FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.n5 NE ttbl_account2.n5 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "N5: " AT 3 ttbl_account1.n5 FORMAT ">>>>>9" " (n5)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.n5 NE ttbl_account2.n5 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "N5: " AT 3 ttbl_account2.n5 FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_account1.type NE ttbl_account2.type OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 3 ttbl_account1.type " (type)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_account1.type NE ttbl_account2.type THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 3 ttbl_account2.type.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_account2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_account1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_account2.actnum " (actnum)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_account1.actnum " (actnum)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
