/* ar-cash.p - generated 01/10/2001 - 12:59:58 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_ar-cash1 NO-UNDO LIKE ar-cash.
DEFINE WORK-TABLE ttbl_ar-cash2 NO-UNDO LIKE ar-cash.

CREATE ttbl_ar-cash1.
IMPORT STREAM s_audit_file ttbl_ar-cash1.
CREATE ttbl_ar-cash2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_ar-cash2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_ar-cash1.bank-code NE ttbl_ar-cash2.bank-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash1.bank-code " (bank-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.bank-code NE ttbl_ar-cash2.bank-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash2.bank-code.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.c-no NE ttbl_ar-cash2.c-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash1.c-no FORMAT ">>>>>>>>9" " (c-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.c-no NE ttbl_ar-cash2.c-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash2.c-no FORMAT ">>>>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cc-auth NE ttbl_ar-cash2.cc-auth OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Authorization: " AT 3 ttbl_ar-cash1.cc-auth " (cc-auth)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cc-auth NE ttbl_ar-cash2.cc-auth THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Authorization: " AT 3 ttbl_ar-cash2.cc-auth.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cc-expiration NE ttbl_ar-cash2.cc-expiration OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Expiration: " AT 3 ttbl_ar-cash1.cc-expiration FORMAT "99/99/9999" " (cc-expiration)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cc-expiration NE ttbl_ar-cash2.cc-expiration THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Expiration: " AT 3 ttbl_ar-cash2.cc-expiration FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cc-name NE ttbl_ar-cash2.cc-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Holders Name: " AT 3 ttbl_ar-cash1.cc-name " (cc-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cc-name NE ttbl_ar-cash2.cc-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Holders Name: " AT 3 ttbl_ar-cash2.cc-name.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cc-num NE ttbl_ar-cash2.cc-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Number: " AT 3 ttbl_ar-cash1.cc-num " (cc-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cc-num NE ttbl_ar-cash2.cc-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Number: " AT 3 ttbl_ar-cash2.cc-num.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cc-type NE ttbl_ar-cash2.cc-type OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Type: " AT 3 ttbl_ar-cash1.cc-type " (cc-type)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cc-type NE ttbl_ar-cash2.cc-type THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Credit Card Type: " AT 3 ttbl_ar-cash2.cc-type.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.check-amt NE ttbl_ar-cash2.check-amt OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Amount: " AT 3 ttbl_ar-cash1.check-amt FORMAT "->>,>>>,>>9.99" " (check-amt)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.check-amt NE ttbl_ar-cash2.check-amt THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Amount: " AT 3 ttbl_ar-cash2.check-amt FORMAT "->>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.check-date NE ttbl_ar-cash2.check-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Check Date: " AT 3 ttbl_ar-cash1.check-date FORMAT "99/99/99" " (check-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.check-date NE ttbl_ar-cash2.check-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Check Date: " AT 3 ttbl_ar-cash2.check-date FORMAT "99/99/99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.check-no NE ttbl_ar-cash2.check-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Check No: " AT 3 ttbl_ar-cash1.check-no FORMAT "999999" " (check-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.check-no NE ttbl_ar-cash2.check-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Check No: " AT 3 ttbl_ar-cash2.check-no FORMAT "999999".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cleared NE ttbl_ar-cash2.cleared OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cleared Bank?: " AT 3 ttbl_ar-cash1.cleared FORMAT "Yes/No" " (cleared)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cleared NE ttbl_ar-cash2.cleared THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cleared Bank?: " AT 3 ttbl_ar-cash2.cleared FORMAT "Yes/No".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.company NE ttbl_ar-cash2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ar-cash1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.company NE ttbl_ar-cash2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ar-cash2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.cust-no NE ttbl_ar-cash2.cust-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 3 ttbl_ar-cash1.cust-no " (cust-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.cust-no NE ttbl_ar-cash2.cust-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 3 ttbl_ar-cash2.cust-no.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.memo NE ttbl_ar-cash2.memo OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash1.memo FORMAT "yes/no" " (memo)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.memo NE ttbl_ar-cash2.memo THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash2.memo FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.posted NE ttbl_ar-cash2.posted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_ar-cash1.posted FORMAT "y/n" " (posted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.posted NE ttbl_ar-cash2.posted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_ar-cash2.posted FORMAT "y/n".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-cash1.ret-memo NE ttbl_ar-cash2.ret-memo OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash1.ret-memo FORMAT "yes/no" " (ret-memo)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-cash1.ret-memo NE ttbl_ar-cash2.ret-memo THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-cash2.ret-memo FORMAT "yes/no".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-cash2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-cash1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-cash2.cust-no " (cust-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-cash1.cust-no " (cust-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Check Date: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-cash2.check-date FORMAT "99/99/99" " (check-date)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-cash1.check-date FORMAT "99/99/99" " (check-date)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
