DEFINE TEMP-TABLE ttItem NO-UNDO
    FIELD WarehouseID              AS CHARACTER
    FIELD LocationID               AS CHARACTER
    FIELD PrimaryID                AS CHARACTER
    FIELD InventoryStockID         AS CHARACTER
    FIELD Quantity                 AS DECIMAL
    FIELD ItemType                 AS CHARACTER  
    FIELD tag                      AS CHARACTER
    FIELD QuantityUOM              AS CHARACTER
    FIELD QuantityPerSubUnit       AS INTEGER
    FIELD QuantitySubUnitsPerUnit  AS INTEGER
    FIELD QuantityPartial          AS INTEGER
    FIELD Units                    AS INTEGER
    FIELD JobNo                    AS CHARACTER
    FIELD JobNo2                   AS INTEGER
    FIELD POID                     AS INTEGER
    FIELD UnitLength               AS DECIMAL
    FIELD UnitHeight               AS DECIMAL
    FIELD UnitWidth                AS DECIMAL
    FIELD StackHeight              AS INTEGER
    FIELD TagStatus                AS CHARACTER 
    FIELD StatusDescription        AS CHARACTER 
    FIELD OnHold                   AS LOGICAL
    .
