DEFINE INPUT  PARAMETER phDset  AS HANDLE     NO-UNDO.
DEFINE INPUT  PARAMETER phBuff1 AS HANDLE     NO-UNDO.
DEFINE INPUT  PARAMETER phBuff2 AS HANDLE     NO-UNDO.
DEFINE INPUT  PARAMETER pcRel   AS CHARACTER  NO-UNDO.
DEFINE OUTPUT PARAMETER ophRel  AS HANDLE     NO-UNDO.
    
ophRel = phDset:ADD-RELATION(phBuff1, phBuff2, pcRel). 
