/* aoaURL.p */

DEFINE INPUT PARAMETER ipcConnect AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER ipcAppInfo AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER ipcURL     AS CHARACTER NO-UNDO.

DEFINE VARIABLE        hAppSrv    AS HANDLE    NO-UNDO.
DEFINE VARIABLE        lReturn    AS LOGICAL   NO-UNDO.

CREATE SERVER hAppSrv.
lReturn = hAppSrv:CONNECT(ipcConnect,"","",ipcAppInfo).

OS-COMMAND NO-WAIT START VALUE(ipcURL).

lReturn = hAppSrv:DISCONNECT().
DELETE OBJECT hAppSrv.
