/* edi810Xcp.p */

&SCOPED-DEFINE aoaID 7AC01BEE24C74ACDA9FA49041AC25AC7
&SCOPED-DEFINE aoaProgramID edi810Xcp.
&SCOPED-DEFINE aoaTitle EDI 810 Exception
&SCOPED-DEFINE aoaType Report
&SCOPED-DEFINE aoaParam YES
&SCOPED-DEFINE aoaColumns YES
&SCOPED-DEFINE test NO

{AOA/includes/aoaParam.i}
