/* sharedVars.i */

DEFINE {1} SHARED VARIABLE asOfTime AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE capacityLoad AS LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE cascadeJob AS LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE changeResource AS LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE copyToResource AS LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE customValueList AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE departmentList AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE endDateMove AS LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE ID AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE loginID AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE printPrgm AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE saveTimeInterval AS DECIMAL NO-UNDO.
DEFINE {1} SHARED VARIABLE sharedRowIDs AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE sortByValue AS CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE statusObject AS CHARACTER NO-UNDO EXTENT {&statusExtent}.
DEFINE {1} SHARED VARIABLE udfLabel AS CHARACTER NO-UNDO EXTENT {&udfExtent}.
DEFINE {1} SHARED VARIABLE udfWidth AS INTEGER NO-UNDO EXTENT {&udfExtent}.
DEFINE {1} SHARED VARIABLE userLabel AS CHARACTER NO-UNDO EXTENT {&userExtent}.
DEFINE {1} SHARED VARIABLE userWidth AS INTEGER NO-UNDO EXTENT {&userExtent}.

&IF '{1}' EQ 'NEW' &THEN
ASSIGN
  udfLabel  = 'Unused'
  udfWidth  = 10
  userLabel = 'Not Used'
  userWidth = 10.
&ENDIF
