  FIELD resource AS CHARACTER LABEL 'Resource'
  FIELD jobSequence AS INTEGER LABEL 'Seq' FORMAT '>>9'
  FIELD job AS CHARACTER LABEL 'Job ID' FORMAT 'X(20)'
  FIELD jobSort AS CHARACTER
  FIELD jobDescription AS CHARACTER
  FIELD resourceSequence AS INTEGER LABEL 'ResSeq' FORMAT '>>9'
  FIELD origResSeq AS INTEGER
  FIELD altResSeq AS INTEGER
  FIELD resourceDescription AS CHARACTER FORMAT 'X(30)'
  FIELD altResource AS CHARACTER
  FIELD department AS CHARACTER
  FIELD origStartDate AS DATE LABEL 'Orig Start' FORMAT '99/99/99'
  FIELD origStartTime AS INTEGER LABEL 'Orig Start' FORMAT '>>>>9'
  FIELD origEndDate AS DATE LABEL 'Orig End' FORMAT '99/99/99'
  FIELD origEndTime AS INTEGER LABEL 'Orig End' FORMAT '>>>>9'
  FIELD timeSpan AS INTEGER
  FIELD jobLocked AS LOGICAL LABEL 'Locked'
  FIELD dueDate AS DATE LABEL 'Due Date' FORMAT '99/99/99'
  FIELD dueTime AS INTEGER LABEL 'Due Time' FORMAT '>>>>9'
  FIELD prodDate AS DATE LABEL 'Prod Date' FORMAT '99/99/99'
  FIELD userValue AS CHARACTER LABEL 'User Value' FORMAT 'X(80)'
  FIELD jobCompleted AS LOGICAL LABEL 'C' FORMAT 'C/'
  FIELD rowIDs AS CHARACTER /* comma delimited row id's */
  FIELD keyValue AS CHARACTER
  FIELD udfField01 AS CHARACTER
  FIELD udfField02 AS CHARACTER
  FIELD udfField03 AS CHARACTER
  FIELD udfField04 AS CHARACTER
  FIELD udfField05 AS CHARACTER
  FIELD udfField06 AS CHARACTER
  FIELD udfField07 AS CHARACTER
  FIELD udfField08 AS CHARACTER
  FIELD udfField09 AS CHARACTER
  FIELD udfField10 AS CHARACTER
  FIELD udfField11 AS CHARACTER
  FIELD udfField12 AS CHARACTER
  FIELD udfField13 AS CHARACTER
  FIELD udfField14 AS CHARACTER
  FIELD udfField15 AS CHARACTER
  FIELD udfField16 AS CHARACTER
  FIELD udfField17 AS CHARACTER
  FIELD udfField18 AS CHARACTER
  FIELD udfField19 AS CHARACTER
  FIELD udfField20 AS CHARACTER
  FIELD userField01 AS CHARACTER
  FIELD userField02 AS CHARACTER
  FIELD userField03 AS CHARACTER
  FIELD userField04 AS CHARACTER
  FIELD userField05 AS CHARACTER
  FIELD userField06 AS CHARACTER
  FIELD userField07 AS CHARACTER
  FIELD userField08 AS CHARACTER
  FIELD userField09 AS CHARACTER
  FIELD userField10 AS CHARACTER
  FIELD userField11 AS CHARACTER
  FIELD userField12 AS CHARACTER
  FIELD userField13 AS CHARACTER
  FIELD userField14 AS CHARACTER
  FIELD userField15 AS CHARACTER
  FIELD userField16 AS CHARACTER
  FIELD userField17 AS CHARACTER
  FIELD userField18 AS CHARACTER
  FIELD userField19 AS CHARACTER
  FIELD userField20 AS CHARACTER
  FIELD userField21 AS CHARACTER
  FIELD userField22 AS CHARACTER
  FIELD userField23 AS CHARACTER
  FIELD userField24 AS CHARACTER
  FIELD userField25 AS CHARACTER
  FIELD userField26 AS CHARACTER
  FIELD userField27 AS CHARACTER
  FIELD userField28 AS CHARACTER
  FIELD userField29 AS CHARACTER
  FIELD userField30 AS CHARACTER
  FIELD userField31 AS CHARACTER
  FIELD userField32 AS CHARACTER
  FIELD userField33 AS CHARACTER
  FIELD userField34 AS CHARACTER
  FIELD userField35 AS CHARACTER
  FIELD userField36 AS CHARACTER
  FIELD userField37 AS CHARACTER
  FIELD userField38 AS CHARACTER
  FIELD userField39 AS CHARACTER
  FIELD userField40 AS CHARACTER
  FIELD userField41 AS CHARACTER
  FIELD userField42 AS CHARACTER
  FIELD userField43 AS CHARACTER
  FIELD userField44 AS CHARACTER
  FIELD userField45 AS CHARACTER
  FIELD userField46 AS CHARACTER
  FIELD userField47 AS CHARACTER
  FIELD userField48 AS CHARACTER
  FIELD userField49 AS CHARACTER
  FIELD userField50 AS CHARACTER
  FIELD userField51 AS CHARACTER
  FIELD userField52 AS CHARACTER
  FIELD userField53 AS CHARACTER
  FIELD userField54 AS CHARACTER
  FIELD userField55 AS CHARACTER
  FIELD userField56 AS CHARACTER
  FIELD userField57 AS CHARACTER
  FIELD userField58 AS CHARACTER
  FIELD userField59 AS CHARACTER
  FIELD userField60 AS CHARACTER
  FIELD userField61 AS CHARACTER
  FIELD userField62 AS CHARACTER
  FIELD userField63 AS CHARACTER
  FIELD userField64 AS CHARACTER
  FIELD userField65 AS CHARACTER
  FIELD userField66 AS CHARACTER
  FIELD userField67 AS CHARACTER
  FIELD userField68 AS CHARACTER
  FIELD userField69 AS CHARACTER
  FIELD userField70 AS CHARACTER
  FIELD userField71 AS CHARACTER
  FIELD userField72 AS CHARACTER
  FIELD userField73 AS CHARACTER
  FIELD userField74 AS CHARACTER
  FIELD userField75 AS CHARACTER
  FIELD userField76 AS CHARACTER
  FIELD userField77 AS CHARACTER
  FIELD userField78 AS CHARACTER
  FIELD userField79 AS CHARACTER
  FIELD userField80 AS CHARACTER
  FIELD userField81 AS CHARACTER
  FIELD userField82 AS CHARACTER
  FIELD userField83 AS CHARACTER
  FIELD userField84 AS CHARACTER
  FIELD userField85 AS CHARACTER
  FIELD userField86 AS CHARACTER
  FIELD userField87 AS CHARACTER
  FIELD userField88 AS CHARACTER
  FIELD userField89 AS CHARACTER
  FIELD userField90 AS CHARACTER
  FIELD userField91 AS CHARACTER
  FIELD userField92 AS CHARACTER
  FIELD userField93 AS CHARACTER
  FIELD userField94 AS CHARACTER
  FIELD userField95 AS CHARACTER
  FIELD userField96 AS CHARACTER
  FIELD userField97 AS CHARACTER
  FIELD userField98 AS CHARACTER
  FIELD userField99 AS CHARACTER
  FIELD userField100 AS CHARACTER
  FIELD userField101 AS CHARACTER
  FIELD userField102 AS CHARACTER
  FIELD userField103 AS CHARACTER
  FIELD userField104 AS CHARACTER
  FIELD userField105 AS CHARACTER
  FIELD userField106 AS CHARACTER
  FIELD userField107 AS CHARACTER
  FIELD userField108 AS CHARACTER
  FIELD userField109 AS CHARACTER
  FIELD userField110 AS CHARACTER
  FIELD userField111 AS CHARACTER
  FIELD userField112 AS CHARACTER
  FIELD userField113 AS CHARACTER
  FIELD userField114 AS CHARACTER
  FIELD userField115 AS CHARACTER
  FIELD userField116 AS CHARACTER
  FIELD userField117 AS CHARACTER
  FIELD userField118 AS CHARACTER
  FIELD userField119 AS CHARACTER
  FIELD userField120 AS CHARACTER
  FIELD userField121 AS CHARACTER
  FIELD userField122 AS CHARACTER
  FIELD userField123 AS CHARACTER
  FIELD jobStatus AS LOGICAL EXTENT {&statusExtent}
  FIELD statusTimeStamp AS CHARACTER EXTENT {&statusExtent}
  FIELD liveUpdate AS LOGICAL INITIAL YES
  FIELD lagTime AS INTEGER
  FIELD jobToolTip AS CHARACTER
  FIELD statusLabel AS CHARACTER FORMAT 'x(12)'
  FIELD prepCompleted AS LOGICAL INITIAL YES
  FIELD sequenced AS LOGICAL
  FIELD anchored AS LOGICAL
  FIELD sortSequence AS INTEGER
  FIELD origResource AS CHARACTER
  FIELD startDate AS DATE  LABEL 'Start Date' FORMAT '99/99/99'
  FIELD startTime AS INTEGER LABEL 'Start Time' FORMAT '>>>>9'
  FIELD endDate AS DATE LABEL 'End Date' FORMAT '99/99/99'
  FIELD endTime AS INTEGER LABEL 'End Time' FORMAT '>>>>9'
  FIELD startDateTime AS DECIMAL FORMAT '>>>>>>>9.99999'
  FIELD endDateTime AS DECIMAL FORMAT '>>>>>>>9.99999'
  FIELD dueDateTime AS DECIMAL FORMAT '>>>>>>>9.99999'
  FIELD downtimeSpan AS INTEGER
  FIELD conflictSpan AS INTEGER
  FIELD jobBGColor AS INTEGER
  FIELD jobFGColor AS INTEGER
  FIELD widgetIdx AS INTEGER
  FIELD priority-1 AS INTEGER
  FIELD priority-2 AS INTEGER
  FIELD priority-3 AS INTEGER
  FIELD jobType AS CHARACTER INITIAL 'S'
  FIELD sbStatus AS LOGICAL
  FIELD jobBrowseFlag AS LOGICAL
  FIELD pendingJobFlag AS LOGICAL
  FIELD resourceDetailFlag AS LOGICAL
  FIELD printFlag AS LOGICAL
  FIELD sortBy AS CHARACTER
