/* sortByDefs.i - rstark - 12.8.2018 */

DEFINE VARIABLE cColLabel    AS CHARACTER NO-UNDO.
DEFINE VARIABLE cColumnLabel AS CHARACTER NO-UNDO {1}.
DEFINE VARIABLE cSaveLabel   AS CHARACTER NO-UNDO {1}.
DEFINE VARIABLE hColumnLabel AS HANDLE    NO-UNDO {1}.
DEFINE VARIABLE hSaveLabel   AS HANDLE    NO-UNDO {1}.
DEFINE VARIABLE lAscending   AS LOGICAL   NO-UNDO INITIAL YES.
