/* auditDefs.i - rstark - 5.21.2021 */

DEFINE VARIABLE hTable      AS HANDLE    NO-UNDO EXTENT 2.
DEFINE VARIABLE iAuditIdx   AS INTEGER   NO-UNDO.
DEFINE VARIABLE iExtent     AS INTEGER   NO-UNDO.
DEFINE VARIABLE iExtentBase AS INTEGER   NO-UNDO.
DEFINE VARIABLE cIdxFields  AS CHARACTER NO-UNDO.
