/* This routine copies <src> to <dest>. */
DEFINE INPUT PARAMETER src AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER dest AS CHARACTER NO-UNDO.
IF OPSYS = "MSDOS" OR OPSYS = "WIN32" THEN
  DOS SILENT copy VALUE(src) VALUE(dest).
ELSE IF OPSYS = "OS2" THEN
  OS2 SILENT copy VALUE(src) VALUE(dest).
ELSE IF OPSYS = "UNIX" THEN
  UNIX SILENT cat VALUE(src) VALUE(dest).
ELSE IF OPSYS = "VMS" THEN
  VMS SILENT copy VALUE(src) VALUE(dest).
ELSE IF OPSYS = "BTOS" THEN
  BTOS SILENT OS-copy VALUE(src) VALUE(dest).
ELSE MESSAGE "oscopy.p: Unknown Operating System -" OPSYS.
RETURN.
