/* aoaStart.p */

DEFINE INPUT PARAMETER cStartup AS CHARACTER NO-UNDO .

DEFINE VARIABLE hProc AS HANDLE NO-UNDO .

RUN aoaBin.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaAdmin.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaAP.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaAR.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaDC.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaEQ.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaFG.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaGL.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaHS.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaJC.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaOE.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaPO.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaRM.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

RUN aoaSB.p PERSISTENT SET hProc .
SESSION:ADD-SUPER-PROCEDURE (hProc) .

OUTPUT TO 'aoaStart.log' APPEND .
PUT UNFORMATTED
    'AdvantzwareOA '
    TODAY FORMAT '99.99.9999'
    ' @ '
    STRING(TIME,'hh:mm:ss am')
    SKIP
    .
OUTPUT CLOSE .

RUN pSetCompany ('001') .
