/* aoaStart.p */

DEFINE INPUT PARAMETER cStartup AS CHARACTER NO-UNDO .

DEFINE VARIABLE hProc AS HANDLE NO-UNDO .

RUN aoaAppSrv\aoaBin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaAdmin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaAP.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaAR.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaDC.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaEQ.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaFG.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaGL.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaHS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaJC.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaOE.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaPO.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaRM.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaSB.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoaAppSrv\aoaTS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

OUTPUT TO 'aoaStart.log' APPEND.
PUT UNFORMATTED '[' REPLACE(STRING(NOW),' ','@') '] AdvantzwareOA' SKIP.
OUTPUT CLOSE.
