COPY addon\bol\bolemail.p p:\asi10compile\src\addon\bol\bolemail.p
COPY addon\custom\emailListAddon.p p:\asi10compile\src\addon\custom\emailListAddon.p
COPY addon\fg\b-cons.w p:\asi10compile\src\addon\fg\b-cons.w
COPY addon\fg\v-fgpost.w p:\asi10compile\src\addon\fg\v-fgpost.w
COPY addon\lookups\item.p p:\asi10compile\src\addon\lookups\item.p
COPY addon\lookups\itemfg.p p:\asi10compile\src\addon\lookups\itemfg.p
COPY addon\lookups\job.p p:\asi10compile\src\addon\lookups\job.p
COPY addon\lookups\jobno.p p:\asi10compile\src\addon\lookups\jobno.p
COPY addon\lookups\poprint.p p:\asi10compile\src\addon\lookups\poprint.p
COPY addon\touch\copynot2A.p p:\asi10compile\src\addon\touch\copynot2A.p
COPY addon\touch\copynoteA.p p:\asi10compile\src\addon\touch\copynoteA.p
COPY methods\viewers\enable\note.i p:\asi10compile\src\methods\viewers\enable\note.i
COPY methods\viewers\enable\note.i p:\asi10compile\src\methods\viewers\enable\note.i
COPY bol\b-bolh.w p:\asi10compile\src\bol\b-bolh.w
COPY bol\b-boll.w p:\asi10compile\src\bol\b-boll.w
COPY cec\est-6.w p:\asi10compile\src\cec\est-6.w
COPY cec\quote\b-probit.w p:\asi10compile\src\cec\quote\b-probit.w
COPY cec\quote\quookla.p p:\asi10compile\src\cec\quote\quookla.p
COPY create.trg\est-pf.p p:\asi10compile\src\create.trg\est-pf.p
COPY create.trg\prgmparm.p p:\asi10compile\src\create.trg\prgmparm.p
COPY create.trg\quote-vendor-item.p p:\asi10compile\src\create.trg\quote-vendor-item.p
COPY create.trg\quote-vendor-qty.p p:\asi10compile\src\create.trg\quote-vendor-qty.p
COPY create.trg\quote-vendor.p p:\asi10compile\src\create.trg\quote-vendor.p
COPY custom\printfile.p p:\asi10compile\src\custom\printfile.p
COPY custom\xldemo.w p:\asi10compile\src\custom\xldemo.w
COPY delete.trg\emailntf.p p:\asi10compile\src\delete.trg\emailntf.p
COPY delete.trg\est-pf.p p:\asi10compile\src\delete.trg\est-pf.p
COPY delete.trg\prgmparm.p p:\asi10compile\src\delete.trg\prgmparm.p
COPY delete.trg\quote-vendor-item.p p:\asi10compile\src\delete.trg\quote-vendor-item.p
COPY delete.trg\quote-vendor-qty.p p:\asi10compile\src\delete.trg\quote-vendor-qty.p
COPY delete.trg\quote-vendor.p p:\asi10compile\src\delete.trg\quote-vendor.p
COPY est\b-vendrf.w p:\asi10compile\src\est\b-vendrf.w
COPY est\b-vendrfq.w p:\asi10compile\src\est\b-vendrfq.w
COPY est\b-vqtitm.w p:\asi10compile\src\est\b-vqtitm.w
COPY est\d-grpcst.w p:\asi10compile\src\est\d-grpcst.w
COPY est\r-quoprt_pdf.w p:\asi10compile\src\est\r-quoprt_pdf.w
COPY est\v-vendrf.w p:\asi10compile\src\est\v-vendrf.w
COPY est\w-vendrf.w p:\asi10compile\src\est\w-vendrf.w
COPY est\w-vendrfq.w p:\asi10compile\src\est\w-vendrfq.w
COPY fg\b-rparts.w p:\asi10compile\src\fg\b-rparts.w
COPY jcsch\b-jobsch2.w p:\asi10compile\src\jcsch\b-jobsch2.w
COPY jcsch\crosstab.w p:\asi10compile\src\jcsch\crosstab.w
COPY jcsch\t-test.w p:\asi10compile\src\jcsch\t-test.w
COPY jcsch\w-test3.w p:\asi10compile\src\jcsch\w-test3.w
COPY jc\b-jobfarm-rctd.w p:\asi10compile\src\jc\b-jobfarm-rctd.w
COPY jc\d-mtcopy.w p:\asi10compile\src\jc\d-mtcopy.w
COPY nosweat\mfvalad.p p:\asi10compile\src\nosweat\mfvalad.p
COPY oerep\bolprt.p p:\asi10compile\src\oerep\bolprt.p
COPY oe\b-binsel.w p:\asi10compile\src\oe\b-binsel.w
COPY oe\b-cloord.w p:\asi10compile\src\oe\b-cloord.w
COPY oe\doBolSingle.p p:\asi10compile\src\oe\doBolSingle.p
COPY oe\orduser.p p:\asi10compile\src\oe\orduser.p
COPY oe\rep\bolallws.p p:\asi10compile\src\oe\rep\bolallws.p
COPY oe\rep\relmcell.p p:\asi10compile\src\oe\rep\relmcell.p
COPY po\poaddscores.p p:\asi10compile\src\po\poaddscores.p
COPY po\poordls1.w p:\asi10compile\src\po\poordls1.w
COPY po\poordls2.w p:\asi10compile\src\po\poordls2.w
COPY po\poordls3.w p:\asi10compile\src\po\poordls3.w
COPY sys\convert\compupdt.p p:\asi10compile\src\sys\convert\compupdt.p
COPY sys\convert\resetrel.p p:\asi10compile\src\sys\convert\resetrel.p
COPY sys\look\loc.w p:\asi10compile\src\sys\look\loc.w
COPY util\deltable.p p:\asi10compile\src\util\deltable.p
COPY util\reckey2.p p:\asi10compile\src\util\reckey2.p
COPY util\rest-bin.p p:\asi10compile\src\util\rest-bin.p
COPY util\srupe.p p:\asi10compile\src\util\srupe.p
COPY util\w-updsmn.w p:\asi10compile\src\util\w-updsmn.w
COPY windows\l-jobfrm.w p:\asi10compile\src\windows\l-jobfrm.w
COPY write.trg\prgmparm.p p:\asi10compile\src\write.trg\prgmparm.p
COPY write.trg\quote-vendor-qty.p p:\asi10compile\src\write.trg\quote-vendor-qty.p
COPY write.trg\quote-vendor.p p:\asi10compile\src\write.trg\quote-vendor.p
