<?xml version="1.0" encoding="utf-8"?>
<styleLibrary office2007ColorScheme="Silver">
  <annotation>
    <lastModified>2011-09-18T11:00:40</lastModified>
  </annotation>
  <styleSets defaultStyleSet="Default">
    <styleSet name="Default" viewStyle="Office2007">
      <componentStyles>
        <componentStyle name="Inbox MonthCalendar">
          <properties>
            <property name="TitleBackColor" colorCategory="{Default}">224, 224, 224</property>
            <property name="TitleForeColor" colorCategory="{Default}">64, 64, 64</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraCalculator" useFlatMode="True" />
        <componentStyle name="UltraCombo" useFlatMode="True" />
        <componentStyle name="UltraDockManager" useFlatMode="True" />
        <componentStyle name="UltraDropDownButton" useFlatMode="True" />
        <componentStyle name="UltraExplorerBar" useFlatMode="True" />
        <componentStyle name="UltraGrid" useFlatMode="True" />
        <componentStyle name="UltraTree" useFlatMode="True" />
      </componentStyles>
      <styles>
        <style role="Base">
          <states>
            <state name="Normal" fontName="Segoe UI" themedElementAlpha="Transparent" />
          </states>
        </style>
        <style role="DesktopAlertCaptionLink">
          <states>
            <state name="HotTracked" foreColor="Black" />
          </states>
        </style>
        <style role="DesktopAlertCloseButton">
          <states>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertDropDownButton">
          <states>
            <state name="Normal">
              <resources>
                <name>spacer</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertFooterTextLink">
          <states>
            <state name="HotTracked" foreColor="Black" fontName="Segoe UI" />
          </states>
        </style>
        <style role="DesktopAlertPinButton">
          <states>
            <state name="Normal">
              <resources>
                <name>spacer</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>DesktopAlertDropDownButton_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="DesktopAlertTextLink">
          <states>
            <state name="HotTracked" foreColor="Black" />
          </states>
        </style>
        <style role="DotNetMonthDropDownTitle">
          <states>
            <state name="Normal" backColor="224, 224, 224" foreColor="64, 64, 64" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarGroupHeader">
          <states>
            <state name="Normal" borderColor="Transparent" />
          </states>
        </style>
        <style role="GridAddNewBox">
          <states>
            <state name="Normal" backColor="232, 232, 232" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridAddNewBoxButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridAddNewBoxPrompt">
          <states>
            <state name="Normal" foreColor="111, 112, 116" />
          </states>
        </style>
        <style role="GridCardCaption">
          <states>
            <state name="Normal" backColor="235, 233, 237" backGradientStyle="None" backHatchStyle="None" />
            <state name="Selected" backColor="169, 177, 184" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridCell">
          <states>
            <state name="EditMode">
              <resources>
                <name>GridCellOffice2K7Black_EditMode</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridColumnHeader">
          <states>
            <state name="Normal">
              <resources>
                <name>GridColumnHeaderOffice2K7_Normal</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>GridColumnHeaderOffice2K7_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridRow">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
            <state name="Selected">
              <resources>
                <name>GridRowOffice2K7Black_Selected</name>
              </resources>
            </state>
            <state name="Active">
              <resources>
                <name>GridRowOffice2K7Black_Active</name>
              </resources>
            </state>
            <state name="AlternateItem" backColor="Office2007.ContextualTabGroupCaptionGradientLight" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridRowSelector">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
          </states>
        </style>
        <style role="ProgressBarFill">
          <states>
            <state name="Normal">
              <resources>
                <name>ProgressBarFill_Normal</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="TabCloseButton">
          <states>
            <state name="Normal" backColor="Transparent" imageBackgroundStyle="Centered" foregroundAlpha="Transparent" borderAlpha="Transparent" backGradientStyle="None" backHatchStyle="None">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsQAAALEAGtI711AAAAdklEQVQ4T2P4//8/A6WYYgNADhjuhqSmpv6HYeQAxyWOM0zyy+r+wzBIETofPTZxBmxl2/T/6BhXUsAbO7U9C/7DML60hNeQ+v7F/2GYLEOaJi3/j45J8k7L1FX/YRikEZ1PMGDbZ6z7D8PIinGJj4RkT07ZAgD6d0+KuyhQiwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked" imageBackgroundStyle="Centered" foregroundAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAIgIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsQAAALEAGtI711AAABi0lEQVQ4T52UPUvDUBSG+0/aP9fZTXBQQUQXQRBER8FBcFA3N+MiuLSIFAcHwbZqaz9scm++mqTH896b3KStInF4aM+5533ObSCt3DdaNeaKoX+AXK1yc/dgPT23KZlRaZBDvnJ926SEDWMnoC/h00QGZMuQHC8k4U1J+jmo0cc55pBDXkliJfG1RARqQEvCBYmW4xxzyOWSeEYjlmgRJLzNZZGrRbgBPlGjj3PMxZwzkoiLoe0pUb1eN9j4aSoYzvUhwELkCpKEJT6NUtHK6gZl4NrFWgsCtTCKk1wyjRIaTDyFuhEL13aOlhjzM0MY55hDztzEcafU/RT0NhD0PpT0wfRGLq3vnRj6Y5cA+jjHHHJaYjVU0e471OmLVCZZKGlz/9SAEEAfYKmScF5J8PQhyUQdHtg6OFuim4ZxjoXI/SiBaPvw3IDAXM3hTrpwQRLRa89R7B5fGLLeb33hRcWb5JJi8K/vcxLpQ2KXBrnsmVjN1gu/I1FpkGOJxX8Fj1XmkuHXujTIVb8Bbt355gHAqXoAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
            <state name="Pressed" imageBackgroundStyle="Centered" foregroundAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAASQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsQAAALEAGtI711AAABsklEQVQ4T52TyUrDUBSG75vUl+vaneBCBRHdCIIDDjgPVKvW2mhbO5jSKbGJSZtWW4ciiEpB8BV+7x/ohSou4uJLOOf838lExMLKxpAkLsE/oDck5EHXUln0Pr8CQ48+l+D1vYd6sxMYevT9Jc8vr7DdVmDoqSXtxy5Mqx4YempJo9VG2bB9wuGwot/7q09PLbFdD4WSqRgeGUcf9n/W/Sw9tcS0XOT0sk++UIFeNDA6vfwL9jnvZ+mpJYfHZziIxnEU03ASTyKWSCN+kcHY7LaCNfucM8c8PX/J4uomzrUUTs6TvqilcrjM6EhmC5iY21OwZp9z5pinR18sr+/gKqsjQVkG09dFZOUtT85HfsE+58wxT4++WNvaR14vIZkvIiNDefkip5aiitKNM1Bzzhzz9OiLjd0IimUDOfnS9EoNMysxheF4MJymxBvoM8c8Pfpi+yCKqmmjULVQqrmo3now3TvUGm1YXgeW/B14Zs0+58wxT4++2I2cwqk3/QGvWmvcw249wLl/gtPuwu10/TNr9jlnjnl69IX8VHpOPuPbRy8w9OiLw1MtJDmT4B/QC30DRBKLNrwkm/0AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
          </states>
        </style>
        <style role="TabControlTabCloseButton">
          <states>
            <state name="Normal" backColor="Transparent" imageBackgroundStyle="Centered" borderAlpha="Transparent" backGradientStyle="None" backHatchStyle="None">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAdklEQVQ4T2P4//8/A6WYYgNADhjuhqSmpv6HYeQAxyWOM0zyy+r+wzBIETofPTZxBmxl2/T/6BhXUsAbO7U9C/7DML60hNeQ+v7F/2GYLEOaJi3/j45J8k7L1FX/YRikEZ1PMGDbZ6z7D8PIinGJj4RkT07ZAgD6d0+KuyhQiwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked" imageBackgroundStyle="Centered" borderAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAIgIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAABi0lEQVQ4T52UPUvDUBSG+0/aP9fZTXBQQUQXQRBER8FBcFA3N+MiuLSIFAcHwbZqaz9scm++mqTH896b3KStInF4aM+5533ObSCt3DdaNeaKoX+AXK1yc/dgPT23KZlRaZBDvnJ926SEDWMnoC/h00QGZMuQHC8k4U1J+jmo0cc55pBDXkliJfG1RARqQEvCBYmW4xxzyOWSeEYjlmgRJLzNZZGrRbgBPlGjj3PMxZwzkoiLoe0pUb1eN9j4aSoYzvUhwELkCpKEJT6NUtHK6gZl4NrFWgsCtTCKk1wyjRIaTDyFuhEL13aOlhjzM0MY55hDztzEcafU/RT0NhD0PpT0wfRGLq3vnRj6Y5cA+jjHHHJaYjVU0e471OmLVCZZKGlz/9SAEEAfYKmScF5J8PQhyUQdHtg6OFuim4ZxjoXI/SiBaPvw3IDAXM3hTrpwQRLRa89R7B5fGLLeb33hRcWb5JJi8K/vcxLpQ2KXBrnsmVjN1gu/I1FpkGOJxX8Fj1XmkuHXujTIVb8Bbt355gHAqXoAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
            <state name="Pressed" imageBackgroundStyle="Centered" borderAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAASQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAABsklEQVQ4T52TyUrDUBSG75vUl+vaneBCBRHdCIIDDjgPVKvW2mhbO5jSKbGJSZtWW4ciiEpB8BV+7x/ohSou4uJLOOf838lExMLKxpAkLsE/oDck5EHXUln0Pr8CQ48+l+D1vYd6sxMYevT9Jc8vr7DdVmDoqSXtxy5Mqx4YempJo9VG2bB9wuGwot/7q09PLbFdD4WSqRgeGUcf9n/W/Sw9tcS0XOT0sk++UIFeNDA6vfwL9jnvZ+mpJYfHZziIxnEU03ASTyKWSCN+kcHY7LaCNfucM8c8PX/J4uomzrUUTs6TvqilcrjM6EhmC5iY21OwZp9z5pinR18sr+/gKqsjQVkG09dFZOUtT85HfsE+58wxT4++WNvaR14vIZkvIiNDefkip5aiitKNM1Bzzhzz9OiLjd0IimUDOfnS9EoNMysxheF4MJymxBvoM8c8Pfpi+yCKqmmjULVQqrmo3now3TvUGm1YXgeW/B14Zs0+58wxT4++2I2cwqk3/QGvWmvcw249wLl/gtPuwu10/TNr9jlnjnl69IX8VHpOPuPbRy8w9OiLw1MtJDmT4B/QC30DRBKLNrwkm/0AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
          </states>
        </style>
        <style role="TreeCell">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
          </states>
        </style>
        <style role="UltraButton" buttonStyle="FlatBorderless">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraCalculator">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraCalculatorButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>Button_HotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraCalculatorButtonBase">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraDropDownButtonMainButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraDropDownButtonSplitButton">
          <states>
            <state name="Normal">
              <resources>
                <name>Button</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="UltraPanel">
          <states>
            <state name="Normal" backColor="Office2007.GroupBoxContentAreaGradientLight" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraProgressBar" borderStyle="Rounded1">
          <states>
            <state name="Normal" borderColor="169, 177, 184" />
          </states>
        </style>
        <style role="UnpinnedTabAreaTop">
          <states>
            <state name="Normal" backColor="208, 212, 221" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
      </styles>
    </styleSet>
  </styleSets>
  <resources>
    <resource name="Button" foreColor="75, 75, 75" borderColor="Transparent" fontName="Segoe UI" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADAIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAABdUlEQVRIS62VSU8CQRBG62dr4nIQTVgSMAaXQAIYgQRDDIoHbx6NiR5ERJZhYIaBmWHY1Ptn1STcOJE6vGO/r7uqq5sAUOXhCdtwU3vEmk3rxU3FWh3PL68wx2NVxCluylXvMJpO8dU3VTFGDsRNmVIFXjBDezBUZThxIW5K54vw5wu0h5Yqtu9D3JTM5hAsV+hYtiqTaQBxU/T8EvPVD7rWSBV3Noe46ej0DMvfP/Q4QJMZV0XcdBBPYsUB2icIFkuIm/ZO4gi4yR/triqO50PctBOJQRry3mypMnDGEDcHRCH1anx3VHF50+Km3eNYOGgNLpEmFg+auGk/moDPV6rZNVQZTTyImw4TqTCg1eurYrsexE0RvqtSopZhqmJzicRN8fQVPD5B2+THThGLTyBuSmXyYUBvaKticw/ETReFUhhg2I4qFgeIm7Ll2/C5HjgTVWzXh7ipwL/OW+MzHDZNxCluko+5fF/HNlxXa1izab24/wGYijQEAlatQAAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="Button_HotTracked" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAJwIAAAKJUE5HDQoaCgAAAA1JSERSAAAAGAAAABYIBgAAANp9XIgAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAABkElEQVRIS63V2yuDcRzH8e+fhwuuEFG4EsUdN+QwtWRFjcIFynHUpjk0OZQsF0O2tGSRHJblkNDSxvbx+T7jzhXfi/fFc/F7/Z7n9/TtJwDEE7jAX+qbT+Cn39arLe7FM/jDV8BHyjQ11RbX3Any2WSh97hd9NSWzqlj5DPXyKejttFUW9rHI3zrS+ReI6apqba0eMPIpRP4fN4zTU21pdGzjdxbHB+PW2zTqC3HVFsa3CF8vkSRTa2woFErjqm21LjWeDQRZJM+tmCUzzHVlqquZeB6EIgWsyKjaNFUW8o7A3wYIlzyvYlu9N9o0VRbyjv8wI0XiJWxUqNo0VRbKvQLbkeBk0pWYRQtmmpLtf6D5AQQr2d1RtGiqbbUulaBuxngtJk1GUWLptqcg3UgtQQk2lmbUbRoqu1MMu6DwHkv6zGKFk1nklu9u8BDCLj0sAGjaNFUW9rG9oGnHeBqhA0bRYum2rwPDoDncKHkpF301BbXbAwbR7wuM4emqam26MXc74vjL3VPx/DTb+vV/gI1IvgvDRzuVgAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="DesktopAlertDropDownButton_HotTracked" backColor="255, 231, 162" foreColor="Black" borderColor="255, 189, 105" backGradientStyle="None" backHatchStyle="None" />
    <resource name="GridCellOffice2K7Black_EditMode" backColor="Transparent" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAANQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAGQAAAB8IBgAAABKwZn4AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAnklEQVRIS+2WsQrAIAxE/f+Psp8i6uYq4mRST4p0bCB2SkAQCXfmkeFcCMGVUq4YI807ax3oQRf6yyClxL13JiLWKuhBF/oOjng4UbVWhr4DnjHGCY+lC/1lcrLMRETXcBkuEQFRs22X4RIREDXbdhkuEQFR87/bpZkc32Pu3IWE11oTIfjavBPkzKo+58x40JoIE+DjTxb2SJDHU/0NMeXg0vYq1UsAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridColumnHeaderOffice2K7_HotTracked" backColor="Transparent" borderColor="242, 149, 54" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAGwEAAAKJUE5HDQoaCgAAAA1JSERSAAAAPwAAABMIBgAAACcx1ZIAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAhElEQVRYR+XDwQoBUQCF4f9NLdQslIWyUBbKQlkoC2VhMc+CEEKIaR5j5s7cGavjQc5XH788lWvabCPXtN+1XNN8VnJN817KNfG1kGvicy7XxMdMrqnvU7mmvk3kmuo6lmuqy0iuCeehXBNOA7kmHPtyTXnoyTXlPpFril1Xrim2Hbn+A3dxL3HvrvjoAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridColumnHeaderOffice2K7_Normal" backColor="246, 250, 251" foreColor="75, 75, 75" borderColor="195, 195, 195" imageBackgroundStyle="Stretched" fontBold="True" backColor2="210, 210, 210" backGradientStyle="Vertical" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridRowOffice2K7Black_Active" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="2, 2, 2, 2">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAASgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAGQAAAB8IBgAAABKwZn4AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAs0lEQVRIS7XDQWcCAACG4e+fjRgdRuwwRocYHaIZG9MOnbp06dSl0y6dijEiNiUiy6ayKSWiP/K9+xXfwyMOA9LFrk+6+HslXWx6pItVl3Tx3SFdfLVJF4sW6WLeJF3MGqSL6SPp4vOedDG8IF1+K5Auv1+SLo+KpMvjK9LljxLp8uSadHl2Q7o8vyVdXpRJl5cV0uWfO9LldZV0+bdGurytky7vH0iXj0+ky6dn0uXzC+n/F1uxr62SBiUAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="GridRowOffice2K7Black_Selected" foreColor="Black" imageBackgroundStyle="Stretched">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADAEAAAKJUE5HDQoaCgAAAA1JSERSAAAACwAAABQIBgAAAFssx2gAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAdUlEQVQ4T5XTOwrCUABE0dn/gkSwsLCxsRBsBAsLQdAk/kjEz8v1LeFanO5WAxPKgBW+HVb4NFgZ3yesjK8jVsrzgJUy7OsYTkq/wwrNBOvPuJ2CFNpZjZ3QzbHCZYEVrkuscFthhfsaKzw2WKHfYoVyrrdyfjBIPq4yqftlAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="ProgressBarFill_Normal" backColor="Transparent" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="0, 1, 0, 1">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAJgEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEAAAABcIBgAAAAL2z9kAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAj0lEQVQ4T6XUXwoBUQCF8bOGuTcPZmzJUqRISORPmgfLUlKTUpo7pGQlx7WG7+H3eL7Ho95+aEJ1dzKhQ6pNaNseTWjd7kxo2W5MaJ5WJjRNCxMadzMTGj0nJlSc+yZUXHIAUHEtTSg0pQmFWw4ACvccABQelQmFlAOA4qsyofgemFD85ACg+M0BQOSR/9sfqPZSHmz/0sMAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="spacer" backColor="Transparent" borderColor="Transparent" backGradientStyle="None" backHatchStyle="None">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAqQAAAAKJUE5HDQoaCgAAAA1JSERSAAAAAgAAAAIIBgAAAHK2DSQAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAAAEklEQVQYV2P4//8/AwiDCRAGAHGgC/UyI4PKAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
    <resource name="TabControlTabItemHorizontalBottomOffice2k7Black_Selected" foreColor="Black" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="6, 0, 5, 3">
      <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA4AMAAAKJUE5HDQoaCgAAAA1JSERSAAAANgAAABYIBgAAAIvpb+sAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsPAAALDwGS+QOlAAADSUlEQVRYR9XW2VLaYBQHcN7RF/DG0YfxxtEH8AW8cqaiTi3YVtuZVmtd2JcQIED2AAm4nf4PIWQB7LThIl78Jgt+n+fkO+dLUsfFCn2TVXrA8efvAl0tcV+oUnw1zBHfA+aIyhXrVBFEutFMSudLlPp0cUmn1pgq9da7T6zZ7tHF8JFOz79QKpPJUNp+plpDouvb4kK/7orETyQxSoglIF8SiLU7CmWdZzo7O/MTE5oS3dyXlsqXMTimAsavXKVBBSiC1OXEXtzEstksnSBLsdWl21xl4i5fnVOqihRbrUmlFShjjiBuI9aVNfo8CiR2jCy5Pt3NwW/uhyKadKpSb2JwQghIZKqKo6tNPSWS2AkSa0my30Oo33xEDQNja2COFatjvjr2h7ookazq9DW4Yqe4aHfkBfWP+i27eGBSCGKHZpodakwpmkEX40ApcmIdNF6p2pgpo6eCvMFxjmKrg15ehe5kT2DNtk/TTbr0EuPt/oPzSt2eOmvICpozSsQEcQWDiHfem+wJrMUkl6ZbSOzV3+6PODHsKFVsDhPCvCYGxuUFsMpjG3FxGzHdWJCYrOhoQm7ENglMDJMwMDHQNvzO8nAbMcPsR1fshRTVQBNKMyIaMqjTw+CE4LYJwbduF0xrQJePgVL8iO8r3lFa6CPftH6nddxDqSaFjPfVPJ2sfiSxL/0RqUjsrVJT8I5IKhWxcfz9wTC8Yj/M4eSHLkptGf49KTTdwA4YZdJgGEksp/dJQ+Cyoi6l4DcFJRCi4noJFfdDNH6qOv5P0KIA3Xt6iIkdz2fgfI5p0nBo+yvGH8ENvNh4MlVDMDNuIEHhoKJB4loPCgetGwg2ZEFwHDACjDJNi0IsXC9g2zZ9917Q6XSaOqhRxxn9mxH+fs4Y91yjqDHuBYxxvlqPNLAdunKe6PDwkFK7u7skCAKWcfif7EkJ/A0/TZezkOM4eLAx4EEqWJxr7BM7OzuU2tzcJP6sqtVq6B+85FAubyXJDerp4zzIwrXLJgtJmFMGjjr+KdM8WG0NwagBCgfnwYoqE3gVzXnCPZ+M8ybmzfVkypyf08bGBqXW1tZofX2dtre3aX9/nw4ODibfWu/N0dER7e3t0dbWFnFOfwCl4PjzNrFdPwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
    </resource>
  </resources>
</styleLibrary>