DEFINE TEMP-TABLE tt NO-UNDO LABEL "tt"
 FIELD c AS CHAR
 INDEX c c.

DEFINE VARIABLE c AS CHARACTER  NO-UNDO.

INPUT FROM "CLIPBOARD".
REPEAT:
    IMPORT UNFORM c.
    FIND FIRST tt WHERE tt.c = c NO-ERROR.
    IF AVAIL tt THEN NEXT.
    
    CREATE tt.
    tt.c = c.
END.

INPUT CLOSE.

OUTPUT TO "CLIPBOARD".
FOR EACH tt BY c:
    PUT UNFORMATTED tt.c SKIP.
END.
OUTPUT CLOSE.
