/* item-spec.p - generated 12/09/2005 - 15:42:46 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_item-spec1 NO-UNDO LIKE item-spec.
DEFINE WORK-TABLE ttbl_item-spec2 NO-UNDO LIKE item-spec.

CREATE ttbl_item-spec1.
IMPORT STREAM s_audit_file ttbl_item-spec1.
CREATE ttbl_item-spec2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_item-spec2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_item-spec1.code NE ttbl_item-spec2.code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Spec Code: " AT 3 ttbl_item-spec1.code " (code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_item-spec1.code NE ttbl_item-spec2.code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Spec Code: " AT 3 ttbl_item-spec2.code.
  END.
END.
IF NOT v_field_changed OR ttbl_item-spec1.company NE ttbl_item-spec2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_item-spec1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_item-spec1.company NE ttbl_item-spec2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_item-spec2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_item-spec1.i-no NE ttbl_item-spec2.i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item Number: " AT 3 ttbl_item-spec1.i-no " (i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_item-spec1.i-no NE ttbl_item-spec2.i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item Number: " AT 3 ttbl_item-spec2.i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_item-spec1.item-type NE ttbl_item-spec2.item-type OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "RM/FG: " AT 3 ttbl_item-spec1.item-type FORMAT "RM/FG" " (item-type)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_item-spec1.item-type NE ttbl_item-spec2.item-type THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "RM/FG: " AT 3 ttbl_item-spec2.item-type FORMAT "RM/FG".
  END.
END.
DO i = 1 TO 4:
IF NOT v_field_changed OR ttbl_item-spec1.notes[i] NE ttbl_item-spec2.notes[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_item-spec1.notes[i] " (notes[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_item-spec1.notes[i] NE ttbl_item-spec2.notes[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_item-spec2.notes[i].
  END.
END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "RM/FG: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec2.item-type FORMAT "RM/FG" " (item-type)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec1.item-type FORMAT "RM/FG" " (item-type)".
  PUT STREAM s-audit-rpt UNFORMATTED "Item Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec2.i-no " (i-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec1.i-no " (i-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Spec Code: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec2.code " (code)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_item-spec1.code " (code)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
