copy addon\start.r      ..\rcode\addon\start.r
copy addon\start10.r    ..\rcode\addon\start10.r
copy addon\start1010.r  ..\rcode\addon\start1010.r
copy addon\touchscr.r   ..\rcode\addon\touchscr.r
copy addon\sharpsh.r    ..\rcode\addon\sharpsh.r
copy addon\sharpsh2.r   ..\rcode\addon\sharpsh2.r
copy nosweat.r          ..\rcode\nosweat.r
copy addon\nosweat.r    ..\rcode\addon\nosweat.r
copy caselbl.r          ..\rcode\caselbl.r
copy ldtagcrt.r         ..\rcode\ldtagcrt.r
copy schedule\sbPro.r   ..\rcode\schedule\sbPro.r