/* jobsheet.p - generated 12/02/2005 - 16:52:40 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_jobsheet1 NO-UNDO LIKE jobsheet.
DEFINE WORK-TABLE ttbl_jobsheet2 NO-UNDO LIKE jobsheet.

CREATE ttbl_jobsheet1.
IMPORT STREAM s_audit_file ttbl_jobsheet1.
CREATE ttbl_jobsheet2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_jobsheet2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_jobsheet1.blank_number NE ttbl_jobsheet2.blank_number OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Blank Number: " AT 3 ttbl_jobsheet1.blank_number FORMAT ">9" " (blank_number)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.blank_number NE ttbl_jobsheet2.blank_number THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Blank Number: " AT 3 ttbl_jobsheet2.blank_number FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.caliper NE ttbl_jobsheet2.caliper OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Caliper: " AT 3 ttbl_jobsheet1.caliper FORMAT "9.99999" " (caliper)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.caliper NE ttbl_jobsheet2.caliper THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Caliper: " AT 3 ttbl_jobsheet2.caliper FORMAT "9.99999".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.die_number NE ttbl_jobsheet2.die_number OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Die Number: " AT 3 ttbl_jobsheet1.die_number " (die_number)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.die_number NE ttbl_jobsheet2.die_number THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Die Number: " AT 3 ttbl_jobsheet2.die_number.
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.die_size NE ttbl_jobsheet2.die_size OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Die Size: " AT 3 ttbl_jobsheet1.die_size FORMAT ">>>>9.99" " (die_size)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.die_size NE ttbl_jobsheet2.die_size THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Die Size: " AT 3 ttbl_jobsheet2.die_size FORMAT ">>>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.form_number NE ttbl_jobsheet2.form_number OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Form Number: " AT 3 ttbl_jobsheet1.form_number FORMAT ">>9" " (form_number)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.form_number NE ttbl_jobsheet2.form_number THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Form Number: " AT 3 ttbl_jobsheet2.form_number FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.item_number NE ttbl_jobsheet2.item_number OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item Number: " AT 3 ttbl_jobsheet1.item_number " (item_number)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.item_number NE ttbl_jobsheet2.item_number THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item Number: " AT 3 ttbl_jobsheet2.item_number.
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.job NE ttbl_jobsheet2.job OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_jobsheet1.job " (job)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.job NE ttbl_jobsheet2.job THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_jobsheet2.job.
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.number_cuts NE ttbl_jobsheet2.number_cuts OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Number of Cuts: " AT 3 ttbl_jobsheet1.number_cuts FORMAT ">9" " (number_cuts)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.number_cuts NE ttbl_jobsheet2.number_cuts THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Number of Cuts: " AT 3 ttbl_jobsheet2.number_cuts FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.number_sheets NE ttbl_jobsheet2.number_sheets OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Number of Sheet: " AT 3 ttbl_jobsheet1.number_sheets FORMAT ">,>>>,>>9.9<<" " (number_sheets)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.number_sheets NE ttbl_jobsheet2.number_sheets THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Number of Sheet: " AT 3 ttbl_jobsheet2.number_sheets FORMAT ">,>>>,>>9.9<<".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.roll_width NE ttbl_jobsheet2.roll_width OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Roll Width: " AT 3 ttbl_jobsheet1.roll_width FORMAT ">>9.9999" " (roll_width)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.roll_width NE ttbl_jobsheet2.roll_width THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Roll Width: " AT 3 ttbl_jobsheet2.roll_width FORMAT ">>9.9999".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.sheet_length NE ttbl_jobsheet2.sheet_length OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Sheet Length: " AT 3 ttbl_jobsheet1.sheet_length FORMAT ">>9.9999" " (sheet_length)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.sheet_length NE ttbl_jobsheet2.sheet_length THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Sheet Length: " AT 3 ttbl_jobsheet2.sheet_length FORMAT ">>9.9999".
  END.
END.
IF NOT v_field_changed OR ttbl_jobsheet1.sheet_width NE ttbl_jobsheet2.sheet_width OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Sheet Width: " AT 3 ttbl_jobsheet1.sheet_width FORMAT ">>9.9999" " (sheet_width)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_jobsheet1.sheet_width NE ttbl_jobsheet2.sheet_width THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Sheet Width: " AT 3 ttbl_jobsheet2.sheet_width FORMAT ">>9.9999".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet2.job " (job)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet1.job " (job)".
  PUT STREAM s-audit-rpt UNFORMATTED "Form Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet2.form_number FORMAT ">>9" " (form_number)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet1.form_number FORMAT ">>9" " (form_number)".
  PUT STREAM s-audit-rpt UNFORMATTED "Blank Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet2.blank_number FORMAT ">9" " (blank_number)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet1.blank_number FORMAT ">9" " (blank_number)".
  PUT STREAM s-audit-rpt UNFORMATTED "Item Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet2.item_number " (item_number)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_jobsheet1.item_number " (item_number)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
