/* prgmxref.p - generated 12/02/2005 - 16:52:37 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_prgmxref1 NO-UNDO LIKE prgmxref.
DEFINE WORK-TABLE ttbl_prgmxref2 NO-UNDO LIKE prgmxref.

CREATE ttbl_prgmxref1.
IMPORT STREAM s_audit_file ttbl_prgmxref1.
CREATE ttbl_prgmxref2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_prgmxref2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_prgmxref1.pageno NE ttbl_prgmxref2.pageno OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Page No.: " AT 3 ttbl_prgmxref1.pageno FORMAT "z9" " (pageno)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_prgmxref1.pageno NE ttbl_prgmxref2.pageno THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Page No.: " AT 3 ttbl_prgmxref2.pageno FORMAT "z9".
  END.
END.
IF NOT v_field_changed OR ttbl_prgmxref1.prgmname NE ttbl_prgmxref2.prgmname OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Program: " AT 3 ttbl_prgmxref1.prgmname " (prgmname)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_prgmxref1.prgmname NE ttbl_prgmxref2.prgmname THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Program: " AT 3 ttbl_prgmxref2.prgmname.
  END.
END.
IF NOT v_field_changed OR ttbl_prgmxref1.table_name NE ttbl_prgmxref2.table_name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Table Name: " AT 3 ttbl_prgmxref1.table_name " (table_name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_prgmxref1.table_name NE ttbl_prgmxref2.table_name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Table Name: " AT 3 ttbl_prgmxref2.table_name.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Table Name: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_prgmxref2.table_name " (table_name)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_prgmxref1.table_name " (table_name)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
