DEF VAR WS_RECS AS INT NO-UNDO.
DEF STREAM S-EXP.
PAUSE MESSAGE "INSERT FLOPPY DISK IN DRIVE A".
OUTPUT STREAM S-EXP TO "A:\FDXCUST.CSV".
FOR EACH CUST NO-LOCK:
    IF CUST-NO = "730000" 
    OR CUST-NO BEGINS "TEST"
    THEN NEXT.
    /*
    RUN EXP.IP
       (CUST.CUST-NO, 
        "", 
        CUST.NAME, 
        CUST.CONTACT, 
        CUST.ADDR[1], 
        CUST.ADDR[2], 
        CUST.CITY, 
        CUST.STATE, 
        CUST.ZIP,
        CUST.AREA-CODE + CUST.PHONE).
    */    
    FOR EACH SHIPTO OF CUST NO-LOCK:
        RUN EXP.IP
       (SHIPTO.CUST-NO, 
        SHIP-ID, 
        SHIPTO.SHIP-NAME, 
        "",
        SHIPTO.SHIP-ADDR[1], 
        SHIPTO.SHIP-ADDR[2], 
        SHIPTO.SHIP-CITY, 
        SHIPTO.SHIP-STATE, 
        SHIPTO.SHIP-ZIP,
        CUST.AREA-CODE + CUST.PHONE).
    END.
END.
OUTPUT STREAM S-EXP CLOSE.
MESSAGE WS_RECS "ADDRESS RECORDS EXPORTED.  YOU MAY REMOVE THE DISK.".
HIDE MESSAGE NO-PAUSE.
STATUS DEFAULT.
PROCEDURE EXP.IP:
DEF INPUT PARAM P-CUST AS CHAR.
DEF INPUT PARAM P-SHIP AS CHAR.
DEF INPUT PARAM P-NAME AS CHAR.
DEF INPUT PARAM P-CONTACT AS CHAR.
DEF INPUT PARAM P-ADDR1 AS CHAR.
DEF INPUT PARAM P-ADDR2 AS CHAR.
DEF INPUT PARAM P-CITY AS CHAR.
DEF INPUT PARAM P-STATE AS CHAR.
DEF INPUT PARAM P-ZIP AS CHAR.
DEF INPUT PARAM P-PHONE AS CHAR.
DEF VAR WS_CODE AS CHAR.
P-CUST = SUBSTRING(P-CUST,1,3).
WS_CODE = P-CUST +
    (IF P-SHIP > "" THEN "-" + P-SHIP ELSE "").
IF P-CONTACT = "" THEN P-CONTACT = "RECEIVING".    
IF LENGTH(P-ZIP) > 5 THEN P-ZIP = SUBSTRING(P-ZIP,1,5).
IF LENGTH(WS_CODE) > 12 THEN DO: BELL. PAUSE. END.
EXPORT STREAM S-EXP DELIMITER ","
    WS_CODE P-NAME P-CONTACT P-ADDR1 P-ADDR2 P-CITY P-STATE P-ZIP P-PHONE.
    
WS_RECS = WS_RECS + 1.
    STATUS DEFAULT WS_CODE + " [" + STRING(WS_RECS) + "]".
END PROCEDURE.
