  FIELD acc-dep-book LIKE fa-mast.acc-dep-book VALIDATE ~
  FIELD acc-dep-tax1 LIKE fa-mast.acc-dep-tax1 VALIDATE ~
  FIELD acc-dep-tax2 LIKE fa-mast.acc-dep-tax2 VALIDATE ~
  FIELD asset-code LIKE fa-mast.asset-code VALIDATE ~
  FIELD asset-desc LIKE fa-mast.asset-desc VALIDATE ~
  FIELD asset-status LIKE fa-mast.asset-status VALIDATE ~
  FIELD auto LIKE fa-mast.auto VALIDATE ~
  FIELD business-% LIKE fa-mast.business-% VALIDATE ~
  FIELD child-par LIKE fa-mast.child-par VALIDATE ~
  FIELD cost-book LIKE fa-mast.cost-book VALIDATE ~
  FIELD Cust-no LIKE fa-mast.Cust-no VALIDATE ~
  FIELD cy-dep-book LIKE fa-mast.cy-dep-book VALIDATE ~
  FIELD cy-dep-tax-1 LIKE fa-mast.cy-dep-tax-1 VALIDATE ~
  FIELD cy-dep-tax-2 LIKE fa-mast.cy-dep-tax-2 VALIDATE ~
  FIELD date-aquired LIKE fa-mast.date-aquired VALIDATE ~
  FIELD date-retired LIKE fa-mast.date-retired VALIDATE ~
  FIELD date-service LIKE fa-mast.date-service VALIDATE ~
  FIELD dep-basis-bk LIKE fa-mast.dep-basis-bk VALIDATE ~
  FIELD dep-basis-t1 LIKE fa-mast.dep-basis-t1 VALIDATE ~
  FIELD dep-basis-t2 LIKE fa-mast.dep-basis-t2 VALIDATE ~
  FIELD Depr-alt LIKE fa-mast.Depr-alt VALIDATE ~
  FIELD Document LIKE fa-mast.Document VALIDATE ~
  FIELD Entity-code LIKE fa-mast.Entity-code VALIDATE ~
  FIELD Exch-rate LIKE fa-mast.Exch-rate VALIDATE ~
  FIELD fa-entity LIKE fa-mast.fa-entity VALIDATE ~
  FIELD gl-code LIKE fa-mast.gl-code VALIDATE ~
  FIELD group-code LIKE fa-mast.group-code VALIDATE ~
  FIELD itc-amt LIKE fa-mast.itc-amt VALIDATE ~
  FIELD itc-recap LIKE fa-mast.itc-recap VALIDATE ~
  FIELD Job-no LIKE fa-mast.Job-no VALIDATE ~
  FIELD last-autodepr-date LIKE fa-mast.last-autodepr-date VALIDATE ~
  FIELD life-amt LIKE fa-mast.life-amt VALIDATE ~
  FIELD life-book LIKE fa-mast.life-book VALIDATE ~
  FIELD life-tax-1 LIKE fa-mast.life-tax-1 VALIDATE ~
  FIELD life-tax-2 LIKE fa-mast.life-tax-2 VALIDATE ~
  FIELD location LIKE fa-mast.location VALIDATE ~
  FIELD memo LIKE fa-mast.memo VALIDATE ~
  FIELD method-book LIKE fa-mast.method-book VALIDATE ~
  FIELD method-tax-1 LIKE fa-mast.method-tax-1 VALIDATE ~
  FIELD method-tax-2 LIKE fa-mast.method-tax-2 VALIDATE ~
  FIELD mth-year LIKE fa-mast.mth-year VALIDATE ~
  FIELD multiple LIKE fa-mast.multiple VALIDATE ~
  FIELD new-used LIKE fa-mast.new-used VALIDATE ~
  FIELD obal-acc-bk LIKE fa-mast.obal-acc-bk VALIDATE ~
  FIELD obal-acc-t1 LIKE fa-mast.obal-acc-t1 VALIDATE ~
  FIELD obal-acc-t2 LIKE fa-mast.obal-acc-t2 VALIDATE ~
  FIELD par-asset LIKE fa-mast.par-asset VALIDATE ~
  FIELD period1 LIKE fa-mast.period[1] VALIDATE ~
  FIELD period2 LIKE fa-mast.period[2] VALIDATE ~
  FIELD period3 LIKE fa-mast.period[3] VALIDATE ~
  FIELD period4 LIKE fa-mast.period[4] VALIDATE ~
  FIELD period5 LIKE fa-mast.period[5] VALIDATE ~
  FIELD period6 LIKE fa-mast.period[6] VALIDATE ~
  FIELD period7 LIKE fa-mast.period[7] VALIDATE ~
  FIELD period8 LIKE fa-mast.period[8] VALIDATE ~
  FIELD period9 LIKE fa-mast.period[9] VALIDATE ~
  FIELD period10 LIKE fa-mast.period[10] VALIDATE ~
  FIELD period11 LIKE fa-mast.period[11] VALIDATE ~
  FIELD period12 LIKE fa-mast.period[12] VALIDATE ~
  FIELD period13 LIKE fa-mast.period[13] VALIDATE ~
  FIELD proceeds LIKE fa-mast.proceeds VALIDATE ~
  FIELD processed LIKE fa-mast.processed VALIDATE ~
  FIELD profit-bk LIKE fa-mast.profit-bk VALIDATE ~
  FIELD profit-t1 LIKE fa-mast.profit-t1 VALIDATE ~
  FIELD profit-t2 LIKE fa-mast.profit-t2 VALIDATE ~
  FIELD purch-order# LIKE fa-mast.purch-order# VALIDATE ~
  FIELD recalc LIKE fa-mast.recalc VALIDATE ~
  FIELD ret-code LIKE fa-mast.ret-code VALIDATE ~
  FIELD ret-prd LIKE fa-mast.ret-prd VALIDATE ~
  FIELD Sale-date LIKE fa-mast.Sale-date VALIDATE ~
  FIELD salvage LIKE fa-mast.salvage VALIDATE ~
  FIELD sec-179 LIKE fa-mast.sec-179 VALIDATE ~
  FIELD serial# LIKE fa-mast.serial# VALIDATE ~
  FIELD Sl-conv-amt LIKE fa-mast.Sl-conv-amt VALIDATE ~
  FIELD sort-code1 LIKE fa-mast.sort-code1 VALIDATE ~
  FIELD sort-code2 LIKE fa-mast.sort-code2 VALIDATE ~
  FIELD start-prd LIKE fa-mast.start-prd VALIDATE ~
  FIELD tag-nof LIKE fa-mast.tag-nof VALIDATE ~
  FIELD tag-not LIKE fa-mast.tag-not VALIDATE ~
  FIELD tax1-period1 LIKE fa-mast.tax1-period[1] VALIDATE ~
  FIELD tax1-period2 LIKE fa-mast.tax1-period[2] VALIDATE ~
  FIELD tax1-period3 LIKE fa-mast.tax1-period[3] VALIDATE ~
  FIELD tax1-period4 LIKE fa-mast.tax1-period[4] VALIDATE ~
  FIELD tax1-period5 LIKE fa-mast.tax1-period[5] VALIDATE ~
  FIELD tax1-period6 LIKE fa-mast.tax1-period[6] VALIDATE ~
  FIELD tax1-period7 LIKE fa-mast.tax1-period[7] VALIDATE ~
  FIELD tax1-period8 LIKE fa-mast.tax1-period[8] VALIDATE ~
  FIELD tax1-period9 LIKE fa-mast.tax1-period[9] VALIDATE ~
  FIELD tax1-period10 LIKE fa-mast.tax1-period[10] VALIDATE ~
  FIELD tax1-period11 LIKE fa-mast.tax1-period[11] VALIDATE ~
  FIELD tax1-period12 LIKE fa-mast.tax1-period[12] VALIDATE ~
  FIELD tax1-period13 LIKE fa-mast.tax1-period[13] VALIDATE ~
  FIELD tax2-period1 LIKE fa-mast.tax2-period[1] VALIDATE ~
  FIELD tax2-period2 LIKE fa-mast.tax2-period[2] VALIDATE ~
  FIELD tax2-period3 LIKE fa-mast.tax2-period[3] VALIDATE ~
  FIELD tax2-period4 LIKE fa-mast.tax2-period[4] VALIDATE ~
  FIELD tax2-period5 LIKE fa-mast.tax2-period[5] VALIDATE ~
  FIELD tax2-period6 LIKE fa-mast.tax2-period[6] VALIDATE ~
  FIELD tax2-period7 LIKE fa-mast.tax2-period[7] VALIDATE ~
  FIELD tax2-period8 LIKE fa-mast.tax2-period[8] VALIDATE ~
  FIELD tax2-period9 LIKE fa-mast.tax2-period[9] VALIDATE ~
  FIELD tax2-period10 LIKE fa-mast.tax2-period[10] VALIDATE ~
  FIELD tax2-period11 LIKE fa-mast.tax2-period[11] VALIDATE ~
  FIELD tax2-period12 LIKE fa-mast.tax2-period[12] VALIDATE ~
  FIELD tax2-period13 LIKE fa-mast.tax2-period[13] VALIDATE ~
  FIELD yr-of-depr LIKE fa-mast.yr-of-depr VALIDATE 
