/* aoaStart.p */

DEFINE INPUT PARAMETER cStartup AS CHARACTER NO-UNDO .

DEFINE VARIABLE hProc AS HANDLE NO-UNDO .

IF CONNECTED(LDBNAME(1)) AND LDBNAME(1) EQ "ASI" THEN DO: 
    CREATE ALIAS nosweat  FOR DATABASE VALUE (LDBNAME (1)). 
    CREATE ALIAS emptrack FOR DATABASE VALUE (LDBNAME (1)). 
    CREATE ALIAS jobs     FOR DATABASE VALUE (LDBNAME (1)). 
    CREATE ALIAS rfq      FOR DATABASE VALUE (LDBNAME (1)). 
    CREATE ALIAS asihelp  FOR DATABASE VALUE (LDBNAME (1)). 
    CREATE ALIAS asihlp   FOR DATABASE VALUE (LDBNAME (1)). 
    CREATE ALIAS asinos   FOR DATABASE VALUE (LDBNAME (1)). 
END. 

RUN aoa\appServer\aoaBin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaAdmin.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaAP.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaAR.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaDC.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaEQ.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaFG.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaGL.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaHS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaJC.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaNS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaOE.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaPO.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaRM.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaSB.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

RUN aoa\appServer\aoaTS.p PERSISTENT SET hProc.
SESSION:ADD-SUPER-PROCEDURE (hProc).

OUTPUT TO 'aoaStart.log' APPEND.
PUT UNFORMATTED '[' REPLACE(STRING(NOW),' ','@') '] AdvantzwareOA' SKIP.
OUTPUT CLOSE.
