/* ar-invm.p - generated 12/09/2005 - 15:42:39 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_ar-invm1 NO-UNDO LIKE ar-invm.
DEFINE WORK-TABLE ttbl_ar-invm2 NO-UNDO LIKE ar-invm.

CREATE ttbl_ar-invm1.
IMPORT STREAM s_audit_file ttbl_ar-invm1.
CREATE ttbl_ar-invm2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_ar-invm2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_ar-invm1.actnum NE ttbl_ar-invm2.actnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_ar-invm1.actnum " (actnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.actnum NE ttbl_ar-invm2.actnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_ar-invm2.actnum.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.amt NE ttbl_ar-invm2.amt OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Amount: " AT 3 ttbl_ar-invm1.amt FORMAT "->>>,>>9.99" " (amt)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.amt NE ttbl_ar-invm2.amt THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Amount: " AT 3 ttbl_ar-invm2.amt FORMAT "->>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.ar-i-no NE ttbl_ar-invm2.ar-i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "AR Line Item: " AT 3 ttbl_ar-invm1.ar-i-no " (ar-i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.ar-i-no NE ttbl_ar-invm2.ar-i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "AR Line Item: " AT 3 ttbl_ar-invm2.ar-i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.ar-line NE ttbl_ar-invm2.ar-line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "AR Line: " AT 3 ttbl_ar-invm1.ar-line FORMAT ">9" " (ar-line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.ar-line NE ttbl_ar-invm2.ar-line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "AR Line: " AT 3 ttbl_ar-invm2.ar-line FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.bill NE ttbl_ar-invm2.bill OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bill: " AT 3 ttbl_ar-invm1.bill " (bill)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.bill NE ttbl_ar-invm2.bill THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bill: " AT 3 ttbl_ar-invm2.bill.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.charge NE ttbl_ar-invm2.charge OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Charge: " AT 3 ttbl_ar-invm1.charge " (charge)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.charge NE ttbl_ar-invm2.charge THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Charge: " AT 3 ttbl_ar-invm2.charge.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.company NE ttbl_ar-invm2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ar-invm1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.company NE ttbl_ar-invm2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ar-invm2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.cost NE ttbl_ar-invm2.cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cost: " AT 3 ttbl_ar-invm1.cost FORMAT "->>,>>>,>>9.99" " (cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.cost NE ttbl_ar-invm2.cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cost: " AT 3 ttbl_ar-invm2.cost FORMAT "->>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.deleted NE ttbl_ar-invm2.deleted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Deleted?: " AT 3 ttbl_ar-invm1.deleted FORMAT "Y/N" " (deleted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.deleted NE ttbl_ar-invm2.deleted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Deleted?: " AT 3 ttbl_ar-invm2.deleted FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.dscr NE ttbl_ar-invm2.dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Description: " AT 3 ttbl_ar-invm1.dscr " (dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.dscr NE ttbl_ar-invm2.dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Description: " AT 3 ttbl_ar-invm2.dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.est-no NE ttbl_ar-invm2.est-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 3 ttbl_ar-invm1.est-no " (est-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.est-no NE ttbl_ar-invm2.est-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 3 ttbl_ar-invm2.est-no.
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.line NE ttbl_ar-invm2.line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 3 ttbl_ar-invm1.line FORMAT "99" " (line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.line NE ttbl_ar-invm2.line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 3 ttbl_ar-invm2.line FORMAT "99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.ord-no NE ttbl_ar-invm2.ord-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Order#: " AT 3 ttbl_ar-invm1.ord-no FORMAT ">>>>>9" " (ord-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.ord-no NE ttbl_ar-invm2.ord-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Order#: " AT 3 ttbl_ar-invm2.ord-no FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.posted NE ttbl_ar-invm2.posted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_ar-invm1.posted FORMAT "y/n" " (posted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.posted NE ttbl_ar-invm2.posted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_ar-invm2.posted FORMAT "y/n".
  END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_ar-invm1.s-comm[i] NE ttbl_ar-invm2.s-comm[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Commission[" AT 3 i "]: " ttbl_ar-invm1.s-comm[i] FORMAT ">>9.99" " (s-comm[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.s-comm[i] NE ttbl_ar-invm2.s-comm[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Commission[" AT 3 i "]: " ttbl_ar-invm2.s-comm[i] FORMAT ">>9.99".
  END.
END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_ar-invm1.s-commbasis[i] NE ttbl_ar-invm2.s-commbasis[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Basis[" AT 3 i "]: " ttbl_ar-invm1.s-commbasis[i] " (s-commbasis[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.s-commbasis[i] NE ttbl_ar-invm2.s-commbasis[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Basis[" AT 3 i "]: " ttbl_ar-invm2.s-commbasis[i].
  END.
END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_ar-invm1.s-pct[i] NE ttbl_ar-invm2.s-pct[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Percentage[" AT 3 i "]: " ttbl_ar-invm1.s-pct[i] FORMAT ">>9.99" " (s-pct[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.s-pct[i] NE ttbl_ar-invm2.s-pct[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Percentage[" AT 3 i "]: " ttbl_ar-invm2.s-pct[i] FORMAT ">>9.99".
  END.
END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_ar-invm1.sman[i] NE ttbl_ar-invm2.sman[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Salesman Code[" AT 3 i "]: " ttbl_ar-invm1.sman[i] " (sman[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.sman[i] NE ttbl_ar-invm2.sman[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Salesman Code[" AT 3 i "]: " ttbl_ar-invm2.sman[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.t-freight NE ttbl_ar-invm2.t-freight OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Total Freight: " AT 3 ttbl_ar-invm1.t-freight FORMAT "->>,>>9.99" " (t-freight)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.t-freight NE ttbl_ar-invm2.t-freight THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Total Freight: " AT 3 ttbl_ar-invm2.t-freight FORMAT "->>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.t-freight-p NE ttbl_ar-invm2.t-freight-p OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-invm1.t-freight-p FORMAT "->>,>>>,>>9.99" " (t-freight-p)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.t-freight-p NE ttbl_ar-invm2.t-freight-p THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ar-invm2.t-freight-p FORMAT "->>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.tax NE ttbl_ar-invm2.tax OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Tax: " AT 3 ttbl_ar-invm1.tax FORMAT "Y/N" " (tax)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.tax NE ttbl_ar-invm2.tax THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Tax: " AT 3 ttbl_ar-invm2.tax FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.upd-date NE ttbl_ar-invm2.upd-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Updated Date: " AT 3 ttbl_ar-invm1.upd-date FORMAT "99/99/9999" " (upd-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.upd-date NE ttbl_ar-invm2.upd-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Updated Date: " AT 3 ttbl_ar-invm2.upd-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.upd-time NE ttbl_ar-invm2.upd-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Updated Time: " AT 3 ttbl_ar-invm1.upd-time FORMAT "->,>>>,>>9" " (upd-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.upd-time NE ttbl_ar-invm2.upd-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Updated Time: " AT 3 ttbl_ar-invm2.upd-time FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_ar-invm1.x-no NE ttbl_ar-invm2.x-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "inv#: " AT 3 ttbl_ar-invm1.x-no FORMAT ">>>>>>9" " (x-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ar-invm1.x-no NE ttbl_ar-invm2.x-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "inv#: " AT 3 ttbl_ar-invm2.x-no FORMAT ">>>>>>9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "inv#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-invm2.x-no FORMAT ">>>>>>9" " (x-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-invm1.x-no FORMAT ">>>>>>9" " (x-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Line: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-invm2.line FORMAT "99" " (line)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-invm1.line FORMAT "99" " (line)".
  PUT STREAM s-audit-rpt UNFORMATTED "Charge: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-invm2.charge " (charge)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ar-invm1.charge " (charge)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
