/* asinotes.p - generated 12/09/2005 - 15:42:39 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_asinotes1 NO-UNDO LIKE asinotes.
DEFINE WORK-TABLE ttbl_asinotes2 NO-UNDO LIKE asinotes.

CREATE ttbl_asinotes1.
IMPORT STREAM s_audit_file ttbl_asinotes1.
CREATE ttbl_asinotes2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_asinotes2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_asinotes1.company NE ttbl_asinotes2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_asinotes1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.company NE ttbl_asinotes2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_asinotes2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.contact NE ttbl_asinotes2.contact OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Contact: " AT 3 ttbl_asinotes1.contact " (contact)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.contact NE ttbl_asinotes2.contact THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Contact: " AT 3 ttbl_asinotes2.contact.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.e-mail NE ttbl_asinotes2.e-mail OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "E-Mail: " AT 3 ttbl_asinotes1.e-mail " (e-mail)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.e-mail NE ttbl_asinotes2.e-mail THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "E-Mail: " AT 3 ttbl_asinotes2.e-mail.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.fax NE ttbl_asinotes2.fax OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Fax: " AT 3 ttbl_asinotes1.fax " (fax)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.fax NE ttbl_asinotes2.fax THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Fax: " AT 3 ttbl_asinotes2.fax.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.key NE ttbl_asinotes2.key OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Key: " AT 3 ttbl_asinotes1.key " (key)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.key NE ttbl_asinotes2.key THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Key: " AT 3 ttbl_asinotes2.key.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.key-2 NE ttbl_asinotes2.key-2 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_asinotes1.key-2 " (key-2)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.key-2 NE ttbl_asinotes2.key-2 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_asinotes2.key-2.
  END.
END.
DO i = 1 TO 20:
IF NOT v_field_changed OR ttbl_asinotes1.notes[i] NE ttbl_asinotes2.notes[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_asinotes1.notes[i] " (notes[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.notes[i] NE ttbl_asinotes2.notes[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_asinotes2.notes[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.page# NE ttbl_asinotes2.page# OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Page Number: " AT 3 ttbl_asinotes1.page# FORMAT ">>9" " (page#)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.page# NE ttbl_asinotes2.page# THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Page Number: " AT 3 ttbl_asinotes2.page# FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.phone NE ttbl_asinotes2.phone OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Phone: " AT 3 ttbl_asinotes1.phone " (phone)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.phone NE ttbl_asinotes2.phone THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Phone: " AT 3 ttbl_asinotes2.phone.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.ti-tle NE ttbl_asinotes2.ti-tle OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Title: " AT 3 ttbl_asinotes1.ti-tle " (ti-tle)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.ti-tle NE ttbl_asinotes2.ti-tle THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Title: " AT 3 ttbl_asinotes2.ti-tle.
  END.
END.
IF NOT v_field_changed OR ttbl_asinotes1.type NE ttbl_asinotes2.type OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 3 ttbl_asinotes1.type " (type)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_asinotes1.type NE ttbl_asinotes2.type THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 3 ttbl_asinotes2.type.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Type: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes2.type " (type)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes1.type " (type)".
  PUT STREAM s-audit-rpt UNFORMATTED "Key: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes2.key " (key)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes1.key " (key)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes2.key-2 " (key-2)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes1.key-2 " (key-2)".
  PUT STREAM s-audit-rpt UNFORMATTED "Page Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes2.page# FORMAT ">>9" " (page#)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_asinotes1.page# FORMAT ">>9" " (page#)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
