/* bank.p - generated 12/09/2005 - 15:42:39 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_bank1 NO-UNDO LIKE bank.
DEFINE WORK-TABLE ttbl_bank2 NO-UNDO LIKE bank.

CREATE ttbl_bank1.
IMPORT STREAM s_audit_file ttbl_bank1.
CREATE ttbl_bank2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_bank2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_bank1.actnum NE ttbl_bank2.actnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_bank1.actnum " (actnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.actnum NE ttbl_bank2.actnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Account No: " AT 3 ttbl_bank2.actnum.
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_bank1.addr[i] NE ttbl_bank2.addr[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Address[" AT 3 i "]: " ttbl_bank1.addr[i] " (addr[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.addr[i] NE ttbl_bank2.addr[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Address[" AT 3 i "]: " ttbl_bank2.addr[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_bank1.bal NE ttbl_bank2.bal OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Balance: " AT 3 ttbl_bank1.bal FORMAT "->>>,>>>,>>9.99" " (bal)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.bal NE ttbl_bank2.bal THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Balance: " AT 3 ttbl_bank2.bal FORMAT "->>>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.bank-code NE ttbl_bank2.bank-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bank: " AT 3 ttbl_bank1.bank-code " (bank-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.bank-code NE ttbl_bank2.bank-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bank: " AT 3 ttbl_bank2.bank-code.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.bank-name NE ttbl_bank2.bank-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bank Name: " AT 3 ttbl_bank1.bank-name " (bank-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.bank-name NE ttbl_bank2.bank-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bank Name: " AT 3 ttbl_bank2.bank-name.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.bk-act NE ttbl_bank2.bk-act OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bank Account #: " AT 3 ttbl_bank1.bk-act " (bk-act)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.bk-act NE ttbl_bank2.bk-act THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bank Account #: " AT 3 ttbl_bank2.bk-act.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.bk-area NE ttbl_bank2.bk-area OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bank area code: " AT 3 ttbl_bank1.bk-area " (bk-area)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.bk-area NE ttbl_bank2.bk-area THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bank area code: " AT 3 ttbl_bank2.bk-area.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.city NE ttbl_bank2.city OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "City: " AT 3 ttbl_bank1.city " (city)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.city NE ttbl_bank2.city THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "City: " AT 3 ttbl_bank2.city.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.company NE ttbl_bank2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_bank1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.company NE ttbl_bank2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_bank2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.contact NE ttbl_bank2.contact OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Contact Name: " AT 3 ttbl_bank1.contact " (contact)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.contact NE ttbl_bank2.contact THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Contact Name: " AT 3 ttbl_bank2.contact.
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_bank1.curr-code[i] NE ttbl_bank2.curr-code[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Currency Code[" AT 3 i "]: " ttbl_bank1.curr-code[i] " (curr-code[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.curr-code[i] NE ttbl_bank2.curr-code[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Currency Code[" AT 3 i "]: " ttbl_bank2.curr-code[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_bank1.dep-tr NE ttbl_bank2.dep-tr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank1.dep-tr FORMAT "->>>,>>>,>>9.99" " (dep-tr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.dep-tr NE ttbl_bank2.dep-tr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank2.dep-tr FORMAT "->>>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.ex-rate NE ttbl_bank2.ex-rate OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank1.ex-rate FORMAT "->>,>>9.99<<<<<" " (ex-rate)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.ex-rate NE ttbl_bank2.ex-rate THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank2.ex-rate FORMAT "->>,>>9.99<<<<<".
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.last-chk NE ttbl_bank2.last-chk OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Last Check #: " AT 3 ttbl_bank1.last-chk FORMAT ">>>>>>>9" " (last-chk)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.last-chk NE ttbl_bank2.last-chk THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Last Check #: " AT 3 ttbl_bank2.last-chk FORMAT ">>>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.o-chk NE ttbl_bank2.o-chk OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank1.o-chk FORMAT "->>>,>>>,>>9.99" " (o-chk)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.o-chk NE ttbl_bank2.o-chk THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank2.o-chk FORMAT "->>>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.phone NE ttbl_bank2.phone OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Phone Number: " AT 3 ttbl_bank1.phone " (phone)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.phone NE ttbl_bank2.phone THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Phone Number: " AT 3 ttbl_bank2.phone.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.serv NE ttbl_bank2.serv OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank1.serv FORMAT "->>>,>>>,>>9.99" " (serv)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.serv NE ttbl_bank2.serv THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_bank2.serv FORMAT "->>>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.state NE ttbl_bank2.state OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "State: " AT 3 ttbl_bank1.state " (state)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.state NE ttbl_bank2.state THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "State: " AT 3 ttbl_bank2.state.
  END.
END.
IF NOT v_field_changed OR ttbl_bank1.zip NE ttbl_bank2.zip OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Postal Code: " AT 3 ttbl_bank1.zip " (zip)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_bank1.zip NE ttbl_bank2.zip THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Postal Code: " AT 3 ttbl_bank2.zip.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_bank2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_bank1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Bank: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_bank2.bank-code " (bank-code)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_bank1.bank-code " (bank-code)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
