/* lookups.p */

DEFINE VARIABLE file-name AS CHARACTER FORMAT "X(24)" NO-UNDO.
DEFINE VARIABLE attr-list AS CHARACTER FORMAT "X(4)" NO-UNDO.
DEFINE VARIABLE dir-name AS CHARACTER INITIAL "lookups/old" NO-UNDO.
DEFINE VARIABLE text-line AS CHARACTER NO-UNDO.
DEFINE VARIABLE i AS INTEGER NO-UNDO.

DEFINE STREAM s1.
DEFINE STREAM s2.

INPUT FROM OS-DIR(dir-name) NO-ECHO.
REPEAT:
  IMPORT DELIMITER " " file-name ^ attr-list.
  IF attr-list NE "F" THEN
  NEXT.
  DISPLAY file-name.
  PAUSE 0.
  i = 0.
  INPUT STREAM s1 FROM VALUE(dir-name + "/" + file-name) NO-ECHO.
  OUTPUT STREAM s2 TO VALUE("lookups/" + file-name).
  REPEAT:
    IMPORT STREAM s1 UNFORMATTED text-line.
    IF text-line NE "" THEN
    PUT STREAM s2 UNFORMATTED text-line SKIP.
    ELSE
    PUT STREAM s2 UNFORMATTED SKIP(1).
    i = i + 1.
    IF i = 6 THEN
    PUT STREAM s2 UNFORMATTED "~"4 ~" ~~" SKIP.
    ELSE
    IF i = 23 THEN
    PUT STREAM s2 UNFORMATTED "~&Scoped-define font 4" SKIP.
  END.
  OUTPUT STREAM s2 CLOSE.
  INPUT STREAM s1 CLOSE.
END.
INPUT CLOSE.
