/* spoolrun.p */

DEFINE NEW GLOBAL SHARED VARIABLE g_company AS CHARACTER NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE g_loc AS CHARACTER NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE g_period AS INTEGER NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE g_track_usage AS LOGICAL NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

OUTPUT TO 'spoolrpt/spooler.log' APPEND.
FOR EACH parmfile NO-LOCK:
  CONNECT -pf VALUE(parmfile.parmfile) NO-ERROR.
  IF ERROR-STATUS:ERROR THEN
  DO i = 1 TO ERROR-STATUS:NUM-MESSAGES:
    PUT UNFORMATTED 'Error: #'
      ERROR-STATUS:GET-NUMBER(i) ' - '
      ERROR-STATUS:GET-MESSAGE(i)
      SKIP.
  END. /* if error */
END. /* each parmfile */
OUTPUT CLOSE.

{methods/defines/globdefs.i &NEW="NEW GLOBAL"}
{methods/defines/hndldefs.i &NEW="NEW GLOBAL"}

RUN nosweat/spooler.w.

SESSION:SET-WAIT-STATE('').

QUIT.
