/* winReSize.i */

DEFINE VARIABLE rowDiff AS DECIMAL NO-UNDO.
DEFINE VARIABLE colDiff AS DECIMAL NO-UNDO.
DEFINE VARIABLE winReSize AS LOGICAL NO-UNDO.
DEFINE VARIABLE winObjects AS CHARACTER NO-UNDO.
