/* 05/08/97 FORM LIKE file EDIVTran */

FORM
  EDIVTran.Partner
  EDIVTran.Seq
  EDIVTran.Cust
  EDIVTran.Invoice-no
  EDIVTran.Cust-po
  EDIVTran.Cust-po-date
  EDIVTran.Vendor
  EDIVTran.Ship-date-code
  EDIVTran.Misc-date1-code
  EDIVTran.Misc-date1
  EDIVTran.Special-svc-code
  EDIVTran.Lines
  EDIVTran.Last-line
  EDIVTran.Contract
  EDIVTran.Release-no
  EDIVTran.Sales-div
  EDIVTran.Sales-region
  EDIVTran.Promo-code
  EDIVTran.Ref2-code
  EDIVTran.Ref2
  EDIVTran.Ref3-code
  EDIVTran.Ref3
  EDIVTran.Bt-code
  EDIVTran.St-code
  EDIVTran.By-code
  EDIVTran.Re-code
  EDIVTran.Sf-code
  EDIVTran.Sn-code
  EDIVTran.Vn-code
  EDIVTran.Invoice-date
  EDIVTran.FOB-Code
  EDIVTran.FOB-Qual
  EDIVTran.FOB-Text
  EDIVTran.Ship-Date
  EDIVTran.BOL-No
  EDIVTran.Carrier
  EDIVTran.Carrier-code
  EDIVTran.Pro-Number
  EDIVTran.Trailer-Number
  EDIVTran.Contact-funct-code
  EDIVTran.Contact-name
  EDIVTran.Contact-phone-qual
  EDIVTran.Contact-phone
  EDIVTran.Del-date-qual
  EDIVTran.Del-date
  EDIVTran.Order-stat
  EDIVTran.Terms
  EDIVTran.Terms-desc[1]
  EDIVTran.Terms-desc[2]
  EDIVTran.Terms-type
  EDIVTran.Terms-basis
  EDIVTran.Terms-disc-pct
  EDIVTran.Terms-disc-date
  EDIVTran.Terms-disc-days
  EDIVTran.Terms-net-date
  EDIVTran.Terms-net-days
  EDIVTran.Terms-disc-amt
  EDIVTran.Terms-day-of-month
  EDIVTran.Curr-buyer
  EDIVTran.Curr-rate-buyer
  EDIVTran.Curr-seller
  EDIVTran.Curr-rate-seller
  EDIVTran.Tot-Gross
  EDIVTran.Tot-disc
  EDIVTran.Tot-net
  EDIVTran.Tot-frt
  EDIVTran.Tot-wght
  EDIVTran.Tot-cartons
  EDIVTran.Carton-uom-code
  EDIVTran.Tot-volume
  EDIVTran.Volume-uom
  EDIVTran.Tot-qty
  EDIVTran.Wght-uom
  EDIVTran.EDShipto
  EDIVTran.Cust-dept
  EDIVTran.Cust-div
  EDIVTran.Routing[1]
  EDIVTran.Routing[2]
  EDIVTran.Routing[3]
  EDIVTran.Routing[4]
  EDIVTran.Company
  WITH FRAME edivtran NO-LABELS.
