/* 04/22/97 FORM LIKE file EDPOTran */

FORM
  EDPOTran.partner
  EDPOTran.seq
  EDPOTran.Cust
  EDPOTran.cust-dept
  EDPOTran.Cust-po
  EDPOTran.Order-date
  EDPOTran.Request-date
  EDPOTran.Cancel-date
  EDPOTran.Ship-name
  EDPOTran.Ship-address[1]
  EDPOTran.Ship-address[2]
  EDPOTran.Ship-address[3]
  EDPOTran.Ship-city
  EDPOTran.Ship-st
  EDPOTran.Ship-country
  EDPOTran.Ship-zip
  EDPOTran.purpose-code
  EDPOTran.purpose-code-desc
  EDPOTran.EDShipto
  EDPOTran.routing[1]
  EDPOTran.routing[2]
  EDPOTran.routing[3]
  EDPOTran.routing[4]
  EDPOTran.Order-code
  EDPOTran.region
  EDPOTran.Order-type
  EDPOTran.Catalog
  EDPOTran.ship-date-code
  EDPOTran.cancel-date-code
  EDPOTran.misc-date1-code
  EDPOTran.misc-date1
  EDPOTran.scheduled-code1
  EDPOTran.scheduled-code2
  EDPOTran.scheduled-code3
  EDPOTran.special-svc-code
  EDPOTran.ship-method-code
  EDPOTran.ship-pay-code
  EDPOTran.ship-loc-code
  EDPOTran.lines
  EDPOTran.last-line
  EDPOTran.ship-from-wh
  EDPOTran.bo-code
  EDPOTran.bo-handling-no
  EDPOTran.contract
  EDPOTran.release-no
  EDPOTran.ship-complete-code
  EDPOTran.sales-div
  EDPOTran.sales-region
  EDPOTran.promo-code
  EDPOTran.packaging-code
  EDPOTran.ref2-code
  EDPOTran.ref2
  EDPOTran.ref3-code
  EDPOTran.ref3
  EDPOTran.tin
  EDPOTran.tin-code
  EDPOTran.tin-loc
  EDPOTran.curr-buyer
  EDPOTran.curr-rate-buyer
  EDPOTran.curr-seller
  EDPOTran.curr-rate-seller
  EDPOTran.order-amount
  EDPOTran.terms
  EDPOTran.terms-desc[1]
  EDPOTran.terms-desc[2]
  EDPOTran.bt-code
  EDPOTran.st-code
  EDPOTran.by-code
  EDPOTran.re-code
  EDPOTran.sf-code
  EDPOTran.sn-code
  EDPOTran.vn-code
  WITH FRAME edpotran NO-LABELS.
