/* 04/22/97 FORM LIKE file EDSHTran */

FORM
  EDSHTran.partner
  EDSHTran.seq
  EDSHTran.error-count
  EDSHTran.misc-date1-code
  EDSHTran.Ship-name
  EDSHTran.Ship-address[1]
  EDSHTran.Ship-address[2]
  EDSHTran.Ship-address[3]
  EDSHTran.Ship-city
  EDSHTran.Ship-st
  EDSHTran.Ship-country
  EDSHTran.Ship-zip
  EDSHTran.purpose-code
  EDSHTran.routing[1]
  EDSHTran.routing[2]
  EDSHTran.routing[3]
  EDSHTran.routing[4]
  EDSHTran.ship-date-code
  EDSHTran.Ship-Date
  EDSHTran.BOL-No
  EDSHTran.carrier
  EDSHTran.carrier-code
  EDSHTran.ship-method-code
  EDSHTran.Pro-Number
  EDSHTran.ship-pay-code
  EDSHTran.Trailer-Number
  EDSHTran.ship-loc-code
  EDSHTran.lines
  EDSHTran.last-line
  EDSHTran.ship-from-wh
  EDSHTran.del-date-qual
  EDSHTran.del-date
  EDSHTran.tot-wght
  EDSHTran.tot-cartons
  EDSHTran.st-code
  EDSHTran.tot-volume
  EDSHTran.sf-code
  EDSHTran.vn-code
  EDSHTran.misc-date1
  EDSHTran.BOL-Adddate
  EDSHTran.BOL-Addtime
  EDSHTran.Package-Code
  EDSHTran.Ship-Stat
  EDSHTran.Transit-time-qual
  EDSHTran.Transit-time
  EDSHTran.Equipment-code
  EDSHTran.Equipment-initial
  EDSHTran.Ship-time
  EDSHTran.Ship-time-zone
  EDSHTran.ship-or-dest
  WITH FRAME edshtran NO-LABELS.
