/* initshow.i */

DEFINE OUTPUT PARAMETER notes-init AS LOGICAL NO-UNDO.
DEFINE OUTPUT PARAMETER miscflds-init AS LOGICAL NO-UNDO.
DEFINE OUTPUT PARAMETER addresses-init AS LOGICAL NO-UNDO.
DEFINE OUTPUT PARAMETER phones-init AS LOGICAL NO-UNDO.

ASSIGN
  notes-init = {&SHOWNOTES}
  miscflds-init = {&SHOWMISCFLDS}
  addresses-init = {&SHOWADDRESSES}
  phones-init = {&SHOWPHONES}.
