/* ap-ctrl.p - generated 01/10/2001 - 12:59:57 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_ap-ctrl1 NO-UNDO LIKE ap-ctrl.
DEFINE WORK-TABLE ttbl_ap-ctrl2 NO-UNDO LIKE ap-ctrl.

CREATE ttbl_ap-ctrl1.
IMPORT STREAM s_audit_file ttbl_ap-ctrl1.
CREATE ttbl_ap-ctrl2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_ap-ctrl2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_ap-ctrl1.accrued NE ttbl_ap-ctrl2.accrued OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Accrued Expenses: " AT 3 ttbl_ap-ctrl1.accrued " (accrued)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.accrued NE ttbl_ap-ctrl2.accrued THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Accrued Expenses: " AT 3 ttbl_ap-ctrl2.accrued.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.accrued-dscr NE ttbl_ap-ctrl2.accrued-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.accrued-dscr " (accrued-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.accrued-dscr NE ttbl_ap-ctrl2.accrued-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.accrued-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.cash-act NE ttbl_ap-ctrl2.cash-act OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cash Account: " AT 3 ttbl_ap-ctrl1.cash-act " (cash-act)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.cash-act NE ttbl_ap-ctrl2.cash-act THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cash Account: " AT 3 ttbl_ap-ctrl2.cash-act.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.cash-act-dscr NE ttbl_ap-ctrl2.cash-act-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.cash-act-dscr " (cash-act-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.cash-act-dscr NE ttbl_ap-ctrl2.cash-act-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.cash-act-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.company NE ttbl_ap-ctrl2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ap-ctrl1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.company NE ttbl_ap-ctrl2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ap-ctrl2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.discount NE ttbl_ap-ctrl2.discount OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Discount taken: " AT 3 ttbl_ap-ctrl1.discount " (discount)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.discount NE ttbl_ap-ctrl2.discount THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Discount taken: " AT 3 ttbl_ap-ctrl2.discount.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.discount-dscr NE ttbl_ap-ctrl2.discount-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.discount-dscr " (discount-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.discount-dscr NE ttbl_ap-ctrl2.discount-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.discount-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.freight NE ttbl_ap-ctrl2.freight OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Freight Account: " AT 3 ttbl_ap-ctrl1.freight " (freight)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.freight NE ttbl_ap-ctrl2.freight THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Freight Account: " AT 3 ttbl_ap-ctrl2.freight.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.freight-dscr NE ttbl_ap-ctrl2.freight-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.freight-dscr " (freight-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.freight-dscr NE ttbl_ap-ctrl2.freight-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.freight-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.payables NE ttbl_ap-ctrl2.payables OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Accounts Payable: " AT 3 ttbl_ap-ctrl1.payables " (payables)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.payables NE ttbl_ap-ctrl2.payables THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Accounts Payable: " AT 3 ttbl_ap-ctrl2.payables.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.payables-dscr NE ttbl_ap-ctrl2.payables-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.payables-dscr " (payables-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.payables-dscr NE ttbl_ap-ctrl2.payables-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.payables-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.purchases NE ttbl_ap-ctrl2.purchases OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Purchases Account: " AT 3 ttbl_ap-ctrl1.purchases " (purchases)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.purchases NE ttbl_ap-ctrl2.purchases THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Purchases Account: " AT 3 ttbl_ap-ctrl2.purchases.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.purchases-dscr NE ttbl_ap-ctrl2.purchases-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.purchases-dscr " (purchases-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.purchases-dscr NE ttbl_ap-ctrl2.purchases-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.purchases-dscr.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.stax NE ttbl_ap-ctrl2.stax OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Sales Tax: " AT 3 ttbl_ap-ctrl1.stax " (stax)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.stax NE ttbl_ap-ctrl2.stax THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Sales Tax: " AT 3 ttbl_ap-ctrl2.stax.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-ctrl1.stax-dscr NE ttbl_ap-ctrl2.stax-dscr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl1.stax-dscr " (stax-dscr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-ctrl1.stax-dscr NE ttbl_ap-ctrl2.stax-dscr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-ctrl2.stax-dscr.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-ctrl2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-ctrl1.company " (company)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
