/* ap-pay.p - generated 01/10/2001 - 12:59:57 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_ap-pay1 NO-UNDO LIKE ap-pay.
DEFINE WORK-TABLE ttbl_ap-pay2 NO-UNDO LIKE ap-pay.

CREATE ttbl_ap-pay1.
IMPORT STREAM s_audit_file ttbl_ap-pay1.
CREATE ttbl_ap-pay2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_ap-pay2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_ap-pay1.bank-code NE ttbl_ap-pay2.bank-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Bank Code: " AT 3 ttbl_ap-pay1.bank-code " (bank-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.bank-code NE ttbl_ap-pay2.bank-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Bank Code: " AT 3 ttbl_ap-pay2.bank-code.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.c-no NE ttbl_ap-pay2.c-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay1.c-no FORMAT ">>>>>>>>9" " (c-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.c-no NE ttbl_ap-pay2.c-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay2.c-no FORMAT ">>>>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.check-act NE ttbl_ap-pay2.check-act OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay1.check-act " (check-act)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.check-act NE ttbl_ap-pay2.check-act THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay2.check-act.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.check-amt NE ttbl_ap-pay2.check-amt OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Check Amount: " AT 3 ttbl_ap-pay1.check-amt FORMAT "->>,>>>,>>9.99" " (check-amt)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.check-amt NE ttbl_ap-pay2.check-amt THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Check Amount: " AT 3 ttbl_ap-pay2.check-amt FORMAT "->>,>>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.check-date NE ttbl_ap-pay2.check-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 3 ttbl_ap-pay1.check-date FORMAT "99/99/99" " (check-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.check-date NE ttbl_ap-pay2.check-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 3 ttbl_ap-pay2.check-date FORMAT "99/99/99".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.check-no NE ttbl_ap-pay2.check-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Check No: " AT 3 ttbl_ap-pay1.check-no FORMAT "99999999" " (check-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.check-no NE ttbl_ap-pay2.check-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Check No: " AT 3 ttbl_ap-pay2.check-no FORMAT "99999999".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.cleared NE ttbl_ap-pay2.cleared OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cleared Bank?: " AT 3 ttbl_ap-pay1.cleared FORMAT "Yes/No" " (cleared)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.cleared NE ttbl_ap-pay2.cleared THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cleared Bank?: " AT 3 ttbl_ap-pay2.cleared FORMAT "Yes/No".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.company NE ttbl_ap-pay2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ap-pay1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.company NE ttbl_ap-pay2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_ap-pay2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.d-no NE ttbl_ap-pay2.d-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay1.d-no FORMAT ">>>>>>9" " (d-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.d-no NE ttbl_ap-pay2.d-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay2.d-no FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.man-check NE ttbl_ap-pay2.man-check OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay1.man-check FORMAT "Yes/No" " (man-check)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.man-check NE ttbl_ap-pay2.man-check THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay2.man-check FORMAT "Yes/No".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.memo NE ttbl_ap-pay2.memo OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay1.memo FORMAT "yes/no" " (memo)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.memo NE ttbl_ap-pay2.memo THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay2.memo FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.period NE ttbl_ap-pay2.period OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay1.period FORMAT "99" " (period)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.period NE ttbl_ap-pay2.period THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_ap-pay2.period FORMAT "99".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.posted NE ttbl_ap-pay2.posted OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_ap-pay1.posted FORMAT "y/n" " (posted)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.posted NE ttbl_ap-pay2.posted THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Posted: " AT 3 ttbl_ap-pay2.posted FORMAT "y/n".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.reconciled NE ttbl_ap-pay2.reconciled OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Reconciled: " AT 3 ttbl_ap-pay1.reconciled FORMAT "yes/no" " (reconciled)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.reconciled NE ttbl_ap-pay2.reconciled THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Reconciled: " AT 3 ttbl_ap-pay2.reconciled FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_ap-pay1.vend-no NE ttbl_ap-pay2.vend-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Vendor: " AT 3 ttbl_ap-pay1.vend-no " (vend-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_ap-pay1.vend-no NE ttbl_ap-pay2.vend-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Vendor: " AT 3 ttbl_ap-pay2.vend-no.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-pay2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-pay1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-pay2.check-act " (check-act)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-pay1.check-act " (check-act)".
  PUT STREAM s-audit-rpt UNFORMATTED "Check No: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-pay2.check-no FORMAT "99999999" " (check-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_ap-pay1.check-no FORMAT "99999999" " (check-no)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
