/* job-mch.p - generated 01/10/2001 - 13:00:04 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_job-mch1 NO-UNDO LIKE job-mch.
DEFINE WORK-TABLE ttbl_job-mch2 NO-UNDO LIKE job-mch.

CREATE ttbl_job-mch1.
IMPORT STREAM s_audit_file ttbl_job-mch1.
CREATE ttbl_job-mch2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_job-mch2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_job-mch1.blank-no NE ttbl_job-mch2.blank-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "BLANK: " AT 3 ttbl_job-mch1.blank-no FORMAT ">9" " (blank-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.blank-no NE ttbl_job-mch2.blank-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "BLANK: " AT 3 ttbl_job-mch2.blank-no FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.company NE ttbl_job-mch2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_job-mch1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.company NE ttbl_job-mch2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_job-mch2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.dept NE ttbl_job-mch2.dept OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Department: " AT 3 ttbl_job-mch1.dept " (dept)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.dept NE ttbl_job-mch2.dept THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Department: " AT 3 ttbl_job-mch2.dept.
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.frm NE ttbl_job-mch2.frm OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Form: " AT 3 ttbl_job-mch1.frm FORMAT ">>9" " (frm)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.frm NE ttbl_job-mch2.frm THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Form: " AT 3 ttbl_job-mch2.frm FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.i-name NE ttbl_job-mch2.i-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Name: " AT 3 ttbl_job-mch1.i-name " (i-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.i-name NE ttbl_job-mch2.i-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Name: " AT 3 ttbl_job-mch2.i-name.
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.i-no NE ttbl_job-mch2.i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 3 ttbl_job-mch1.i-no " (i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.i-no NE ttbl_job-mch2.i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 3 ttbl_job-mch2.i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.j-no NE ttbl_job-mch2.j-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Internal Job#: " AT 3 ttbl_job-mch1.j-no FORMAT ">>>>>>9" " (j-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.j-no NE ttbl_job-mch2.j-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Internal Job#: " AT 3 ttbl_job-mch2.j-no FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.job NE ttbl_job-mch2.job OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 3 ttbl_job-mch1.job FORMAT ">>>>>>9" " (job)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.job NE ttbl_job-mch2.job THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 3 ttbl_job-mch2.job FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.job-no NE ttbl_job-mch2.job-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_job-mch1.job-no " (job-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.job-no NE ttbl_job-mch2.job-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_job-mch2.job-no.
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.job-no2 NE ttbl_job-mch2.job-no2 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Run #: " AT 3 ttbl_job-mch1.job-no2 FORMAT ">9" " (job-no2)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.job-no2 NE ttbl_job-mch2.job-no2 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Run #: " AT 3 ttbl_job-mch2.job-no2 FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.line NE ttbl_job-mch2.line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Line #: " AT 3 ttbl_job-mch1.line FORMAT ">9" " (line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.line NE ttbl_job-mch2.line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Line #: " AT 3 ttbl_job-mch2.line FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.m-code NE ttbl_job-mch2.m-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 3 ttbl_job-mch1.m-code " (m-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.m-code NE ttbl_job-mch2.m-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 3 ttbl_job-mch2.m-code.
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.mr-fixoh NE ttbl_job-mch2.mr-fixoh OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "MR Fixed OH: " AT 3 ttbl_job-mch1.mr-fixoh FORMAT ">>9.99" " (mr-fixoh)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.mr-fixoh NE ttbl_job-mch2.mr-fixoh THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "MR Fixed OH: " AT 3 ttbl_job-mch2.mr-fixoh FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.mr-hr NE ttbl_job-mch2.mr-hr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Make Ready Hours: " AT 3 ttbl_job-mch1.mr-hr FORMAT ">>9.99" " (mr-hr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.mr-hr NE ttbl_job-mch2.mr-hr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Make Ready Hours: " AT 3 ttbl_job-mch2.mr-hr FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.mr-rate NE ttbl_job-mch2.mr-rate OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "MR Rate: " AT 3 ttbl_job-mch1.mr-rate FORMAT ">>9.99" " (mr-rate)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.mr-rate NE ttbl_job-mch2.mr-rate THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "MR Rate: " AT 3 ttbl_job-mch2.mr-rate FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.mr-varoh NE ttbl_job-mch2.mr-varoh OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "MR Var OH: " AT 3 ttbl_job-mch1.mr-varoh FORMAT ">>9.99" " (mr-varoh)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.mr-varoh NE ttbl_job-mch2.mr-varoh THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "MR Var OH: " AT 3 ttbl_job-mch2.mr-varoh FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.mr-waste NE ttbl_job-mch2.mr-waste OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "MR Waste: " AT 3 ttbl_job-mch1.mr-waste FORMAT ">>>9" " (mr-waste)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.mr-waste NE ttbl_job-mch2.mr-waste THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "MR Waste: " AT 3 ttbl_job-mch2.mr-waste FORMAT ">>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.n-out NE ttbl_job-mch2.n-out OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job-mch1.n-out FORMAT "->,>>>,>>9" " (n-out)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.n-out NE ttbl_job-mch2.n-out THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job-mch2.n-out FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.pass NE ttbl_job-mch2.pass OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Pass: " AT 3 ttbl_job-mch1.pass FORMAT ">>9" " (pass)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.pass NE ttbl_job-mch2.pass THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Pass: " AT 3 ttbl_job-mch2.pass FORMAT ">>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.run-hr NE ttbl_job-mch2.run-hr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Run Hours: " AT 3 ttbl_job-mch1.run-hr FORMAT ">>9.99" " (run-hr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.run-hr NE ttbl_job-mch2.run-hr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Run Hours: " AT 3 ttbl_job-mch2.run-hr FORMAT ">>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.run-qty NE ttbl_job-mch2.run-qty OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Run Quantity: " AT 3 ttbl_job-mch1.run-qty FORMAT ">,>>>,>>9.9<<" " (run-qty)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.run-qty NE ttbl_job-mch2.run-qty THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Run Quantity: " AT 3 ttbl_job-mch2.run-qty FORMAT ">,>>>,>>9.9<<".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.speed NE ttbl_job-mch2.speed OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Speed: " AT 3 ttbl_job-mch1.speed FORMAT ">>>>9" " (speed)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.speed NE ttbl_job-mch2.speed THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Speed: " AT 3 ttbl_job-mch2.speed FORMAT ">>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.start-date NE ttbl_job-mch2.start-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job-mch1.start-date FORMAT "99/99/9999" " (start-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.start-date NE ttbl_job-mch2.start-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job-mch2.start-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.start-time NE ttbl_job-mch2.start-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job-mch1.start-time FORMAT "->,>>>,>>9" " (start-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.start-time NE ttbl_job-mch2.start-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job-mch2.start-time FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job-mch1.wst-prct NE ttbl_job-mch2.wst-prct OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Waste %: " AT 3 ttbl_job-mch1.wst-prct FORMAT ">>9.99" " (wst-prct)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job-mch1.wst-prct NE ttbl_job-mch2.wst-prct THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Waste %: " AT 3 ttbl_job-mch2.wst-prct FORMAT ">>9.99".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Internal Job#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch2.j-no FORMAT ">>>>>>9" " (j-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch1.j-no FORMAT ">>>>>>9" " (j-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch2.i-no " (i-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch1.i-no " (i-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Code: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch2.m-code " (m-code)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job-mch1.m-code " (m-code)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
