/* mat-act.p - generated 01/10/2001 - 13:00:05 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_mat-act1 NO-UNDO LIKE mat-act.
DEFINE WORK-TABLE ttbl_mat-act2 NO-UNDO LIKE mat-act.

CREATE ttbl_mat-act1.
IMPORT STREAM s_audit_file ttbl_mat-act1.
CREATE ttbl_mat-act2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_mat-act2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_mat-act1.b-num NE ttbl_mat-act2.b-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Blank: " AT 3 ttbl_mat-act1.b-num FORMAT ">9" " (b-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.b-num NE ttbl_mat-act2.b-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Blank: " AT 3 ttbl_mat-act2.b-num FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.company NE ttbl_mat-act2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_mat-act1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.company NE ttbl_mat-act2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_mat-act2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.complete NE ttbl_mat-act2.complete OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Complete: " AT 3 ttbl_mat-act1.complete FORMAT "Y/N" " (complete)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.complete NE ttbl_mat-act2.complete THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Complete: " AT 3 ttbl_mat-act2.complete FORMAT "Y/N".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.cost NE ttbl_mat-act2.cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cost: " AT 3 ttbl_mat-act1.cost FORMAT ">>>>9.99" " (cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.cost NE ttbl_mat-act2.cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cost: " AT 3 ttbl_mat-act2.cost FORMAT ">>>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.ext-cost NE ttbl_mat-act2.ext-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Ext.Cost: " AT 3 ttbl_mat-act1.ext-cost FORMAT ">>>,>>9.99" " (ext-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.ext-cost NE ttbl_mat-act2.ext-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Ext.Cost: " AT 3 ttbl_mat-act2.ext-cost FORMAT ">>>,>>9.99".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.i-name NE ttbl_mat-act2.i-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item Name: " AT 3 ttbl_mat-act1.i-name " (i-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.i-name NE ttbl_mat-act2.i-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item Name: " AT 3 ttbl_mat-act2.i-name.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.i-no NE ttbl_mat-act2.i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 3 ttbl_mat-act1.i-no " (i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.i-no NE ttbl_mat-act2.i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item No: " AT 3 ttbl_mat-act2.i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.j-no NE ttbl_mat-act2.j-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Internal Job#: " AT 3 ttbl_mat-act1.j-no FORMAT ">>>>>>9" " (j-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.j-no NE ttbl_mat-act2.j-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Internal Job#: " AT 3 ttbl_mat-act2.j-no FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.job NE ttbl_mat-act2.job OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 3 ttbl_mat-act1.job FORMAT ">>>>>>9" " (job)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.job NE ttbl_mat-act2.job THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 3 ttbl_mat-act2.job FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.job-no NE ttbl_mat-act2.job-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_mat-act1.job-no " (job-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.job-no NE ttbl_mat-act2.job-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_mat-act2.job-no.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.job-no2 NE ttbl_mat-act2.job-no2 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Run #: " AT 3 ttbl_mat-act1.job-no2 FORMAT ">9" " (job-no2)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.job-no2 NE ttbl_mat-act2.job-no2 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Run #: " AT 3 ttbl_mat-act2.job-no2 FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.loc NE ttbl_mat-act2.loc OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Location: " AT 3 ttbl_mat-act1.loc " (loc)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.loc NE ttbl_mat-act2.loc THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Location: " AT 3 ttbl_mat-act2.loc.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.loc-bin NE ttbl_mat-act2.loc-bin OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Primary Bin Loc.: " AT 3 ttbl_mat-act1.loc-bin " (loc-bin)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.loc-bin NE ttbl_mat-act2.loc-bin THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Primary Bin Loc.: " AT 3 ttbl_mat-act2.loc-bin.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.mat-date NE ttbl_mat-act2.mat-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Issue Date: " AT 3 ttbl_mat-act1.mat-date FORMAT "99/99/99" " (mat-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.mat-date NE ttbl_mat-act2.mat-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Issue Date: " AT 3 ttbl_mat-act2.mat-date FORMAT "99/99/99".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.mat-time NE ttbl_mat-act2.mat-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_mat-act1.mat-time FORMAT "->,>>>,>>9" " (mat-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.mat-time NE ttbl_mat-act2.mat-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_mat-act2.mat-time FORMAT "->,>>>,>>9".
  END.
END.
DO i = 1 TO 3:
IF NOT v_field_changed OR ttbl_mat-act1.notes[i] NE ttbl_mat-act2.notes[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_mat-act1.notes[i] " (notes[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.notes[i] NE ttbl_mat-act2.notes[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_mat-act2.notes[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.opn NE ttbl_mat-act2.opn OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Open Flg: " AT 3 ttbl_mat-act1.opn FORMAT "yes/no" " (opn)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.opn NE ttbl_mat-act2.opn THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Open Flg: " AT 3 ttbl_mat-act2.opn FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.pass NE ttbl_mat-act2.pass OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Pass#: " AT 3 ttbl_mat-act1.pass FORMAT "9" " (pass)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.pass NE ttbl_mat-act2.pass THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Pass#: " AT 3 ttbl_mat-act2.pass FORMAT "9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.qty NE ttbl_mat-act2.qty OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Quantity: " AT 3 ttbl_mat-act1.qty FORMAT ">>,>>>,>>9" " (qty)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.qty NE ttbl_mat-act2.qty THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Quantity: " AT 3 ttbl_mat-act2.qty FORMAT ">>,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.qty-uom NE ttbl_mat-act2.qty-uom OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "UOM: " AT 3 ttbl_mat-act1.qty-uom " (qty-uom)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.qty-uom NE ttbl_mat-act2.qty-uom THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "UOM: " AT 3 ttbl_mat-act2.qty-uom.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.rm-i-name NE ttbl_mat-act2.rm-i-name OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Item NAme: " AT 3 ttbl_mat-act1.rm-i-name " (rm-i-name)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.rm-i-name NE ttbl_mat-act2.rm-i-name THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Item NAme: " AT 3 ttbl_mat-act2.rm-i-name.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.rm-i-no NE ttbl_mat-act2.rm-i-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Std Material Code: " AT 3 ttbl_mat-act1.rm-i-no " (rm-i-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.rm-i-no NE ttbl_mat-act2.rm-i-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Std Material Code: " AT 3 ttbl_mat-act2.rm-i-no.
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.s-num NE ttbl_mat-act2.s-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Form#: " AT 3 ttbl_mat-act1.s-num FORMAT ">9" " (s-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.s-num NE ttbl_mat-act2.s-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Form#: " AT 3 ttbl_mat-act2.s-num FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_mat-act1.tag NE ttbl_mat-act2.tag OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_mat-act1.tag " (tag)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_mat-act1.tag NE ttbl_mat-act2.tag THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_mat-act2.tag.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mat-act2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mat-act1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Issue Date: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mat-act2.mat-date FORMAT "99/99/99" " (mat-date)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_mat-act1.mat-date FORMAT "99/99/99" " (mat-date)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
