/* pdh.p - generated 01/10/2001 - 13:00:07 by nosweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_pdh1 NO-UNDO LIKE pdh.
DEFINE WORK-TABLE ttbl_pdh2 NO-UNDO LIKE pdh.

CREATE ttbl_pdh1.
IMPORT STREAM s_audit_file ttbl_pdh1.
CREATE ttbl_pdh2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_pdh2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_pdh1.BY-Code NE ttbl_pdh2.BY-Code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh1.BY-Code " (BY-Code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pdh1.BY-Code NE ttbl_pdh2.BY-Code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh2.BY-Code.
  END.
END.
IF NOT v_field_changed OR ttbl_pdh1.Cust NE ttbl_pdh2.Cust OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh1.Cust " (Cust)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pdh1.Cust NE ttbl_pdh2.Cust THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh2.Cust.
  END.
END.
IF NOT v_field_changed OR ttbl_pdh1.Dept NE ttbl_pdh2.Dept OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh1.Dept " (Dept)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pdh1.Dept NE ttbl_pdh2.Dept THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh2.Dept.
  END.
END.
IF NOT v_field_changed OR ttbl_pdh1.Last-Line NE ttbl_pdh2.Last-Line OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh1.Last-Line FORMAT ">>>>>9" " (Last-Line)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pdh1.Last-Line NE ttbl_pdh2.Last-Line THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh2.Last-Line FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_pdh1.Mic-code NE ttbl_pdh2.Mic-code OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh1.Mic-code " (Mic-code)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pdh1.Mic-code NE ttbl_pdh2.Mic-code THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_pdh2.Mic-code.
  END.
END.
IF NOT v_field_changed OR ttbl_pdh1.Recnum NE ttbl_pdh2.Recnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Tran#: " AT 3 ttbl_pdh1.Recnum FORMAT ">>>>>>9" " (Recnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_pdh1.Recnum NE ttbl_pdh2.Recnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Tran#: " AT 3 ttbl_pdh2.Recnum FORMAT ">>>>>>9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Tran#: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pdh2.Recnum FORMAT ">>>>>>9" " (Recnum)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_pdh1.Recnum FORMAT ">>>>>>9" " (Recnum)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
