/* patchftp.p */

DEFINE VARIABLE dbList AS CHARACTER NO-UNDO INITIAL 'nosweat,asi'.
DEFINE VARIABLE i AS INTEGER NO-UNDO.
DEFINE VARIABLE j AS INTEGER NO-UNDO.
DEFINE VARIABLE k AS INTEGER NO-UNDO.

j = NUM-ENTRIES(dbList).
DO i = 1 TO j:
  CONNECT -pf VALUE(ENTRY(i,dbList) + '-1.pf') NO-ERROR.
  IF ERROR-STATUS:ERROR THEN
  DO k = 1 TO ERROR-STATUS:NUM-MESSAGES:
    MESSAGE ERROR-STATUS:GET-NUMBER(k) ERROR-STATUS:GET-MESSAGE(k)
        VIEW-AS ALERT-BOX ERROR.
  END.
END.
IF CONNECTED('asi') THEN
RUN system/patchftp.w.
QUIT.
