/* jobmach.i */

DEFINE {&NEW} SHARED VARIABLE s-machine AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-job_number AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-job_sub AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-form_number AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-blank_number AS CHARACTER NO-UNDO.
DEFINE {&NEW} SHARED VARIABLE s-pass_sequence AS CHARACTER NO-UNDO.
