/* primflds.p */

DEFINE INPUT  PARAMETER ipcFileName AS CHARACTER NO-UNDO.

DEFINE OUTPUT PARAMETER opcPrimFlds AS CHARACTER NO-UNDO.

opcPrimFlds = DYNAMIC-FUNCTION("sfGetPrimaryIndexFields", ipcFileName).

SESSION:SET-WAIT-STATE("").
