DEFINE TEMP-TABLE ttCEFormatConfig NO-UNDO
    FIELD outputFile                  AS CHARACTER LABEL "Output File" 
    FIELD previewFile                 AS LOGICAL INITIAL YES LABEL "Preview File?"
    FIELD printInPDF                  AS LOGICAL LABEL "Print PDF?"
    FIELD formatMaster                AS CHARACTER LABEL "Format Master"
    FIELD formatFont                  AS CHARACTER INITIAL "Calibri" LABEL "Font"
    FIELD formatFontSize              AS INTEGER INITIAL 11 LABEL "Font Size"
    FIELD xprintTags                  AS CHARACTER  LABEL "XPrint Tags"
    FIELD isClassic                   AS LOGICAL LABEL "Is Classic?"
    FIELD maxColumnsForQuantity       AS INTEGER INITIAL 99 LABEL "Max Columns For Quantity?"
    FIELD characterNumberError        AS CHARACTER INITIAL "#" LABEL "Error Character for Numbers"
    FIELD characterContinue           AS CHARACTER INITIAL ">>" LABEL "Continue Character"
    FIELD characterMasterQuantity     AS CHARACTER INITIAL "*" LABEL "Master Quantity Character"
    FIELD rowsPerPage                 AS INTEGER INITIAL 64 LABEL "Rows Per Page"
    FIELD showAllQuantities           AS LOGICAL INITIAL YES LABEL "Show All Quantities?"
    FIELD showProfitPercent           AS LOGICAL INITIAL YES LABEL "Show Profit Percent?"
    FIELD SIMONListInclude            AS CHARACTER INITIAL "I,M" LABEL "SIMON Include List"
    FIELD SIMONListSeparate           AS CHARACTER INITIAL "S,O,N" LABEL "SIMON Separate List"
    FIELD useReferenceQuantity        AS LOGICAL INITIAL NO LABEL "Use Reference Quantity?"
    FIELD printByForm                 AS LOGICAL INITIAL YES LABEL "Print By Form?"
    FIELD printForm0Separately        AS LOGICAL INITIAL NO
    FIELD printSummary                AS LOGICAL INITIAL YES LABEL "Print Summary?"
    FIELD printSummaryFirst           AS LOGICAL INITIAL YES LABEL "Print Summart First?"
    FIELD printAnalysis               AS LOGICAL INITIAL YES LABEL "Print Analysis?"
    FIELD printNotes                  AS LOGICAL INITIAL YES LABEL "Print Notes?"
    FIELD printSubAssemblyDetail      AS LOGICAL INITIAL NO
    FIELD printBoxDesigns             AS LOGICAL INITIAL NO LABEL "Print Box Designs?"
    FIELD showDimensionsIn16ths       AS LOGICAL INITIAL NO LABEL "Show Dimensions in 16ths?"
    FIELD operationTimeInHHMM         AS LOGICAL LABEL "Display Operation Time in HHMM"
    FIELD summColQuantityShow         AS LOGICAL INITIAL NO LABEL "Show Quantity in Summary?"
    FIELD summColQuantityLabel        AS CHARACTER INITIAL "Quantity" LABEL "Label"
    FIELD summColQuantityCol          AS DECIMAL INITIAL 36 LABEL "Column Position"
    FIELD summColQuantityWidth        AS INTEGER INITIAL 9 LABEL "Width"
    FIELD summColQuantityRequestShow  AS LOGICAL INITIAL YES LABEL "Show Quantity Requested in Summary"
    FIELD summColQuantityRequestLabel AS CHARACTER INITIAL "Requested" LABEL "Label"
    FIELD summColQuantityRequestCol   AS DECIMAL INITIAL 26 LABEL "Column Position"
    FIELD summColQuantityRequestWidth AS INTEGER INITIAL 9 LABEL "Width"
    FIELD summColQuantityYieldShow    AS LOGICAL INITIAL YES LABEL "Show Quantity Yielded in Summary"
    FIELD summColQuantityYieldLabel   AS CHARACTER INITIAL "Yielded" LABEL "Label"
    FIELD summColQuantityYieldCol     AS DECIMAL INITIAL 36 LABEL "Column Position"
    FIELD summColQuantityYieldWidth   AS INTEGER INITIAL 9 LABEL "Width"
    FIELD summColWeightShow           AS LOGICAL INITIAL YES LABEL "Show Weight in Summary"
    FIELD summColWeightLabel          AS CHARACTER INITIAL "Weight" LABEL "Label"
    FIELD summColWeightCol            AS DECIMAL INITIAL 46 LABEL "Column Position"
    FIELD summColWeightWidth          AS INTEGER INITIAL 9 LABEL "Width"
    FIELD summColItemNameShow         AS LOGICAL INITIAL YES LABEL "Show Item Name in Summary"
    FIELD summColItemNameLabel        AS CHARACTER INITIAL "Item Name" LABEL "Label"
    FIELD summColItemNameCol          AS DECIMAL INITIAL 2 LABEL "Column Position"
    FIELD summColItemNameWidth        AS INTEGER INITIAL 30 LABEL "Width"
    FIELD summColDirectCostShow       AS LOGICAL INITIAL NO LABEL "Show Direct Cost in Summary"
    FIELD summColDirectCostCol        AS DECIMAL INITIAL 46 LABEL "Column Position"
    FIELD summColDirectCostWidth      AS INTEGER INITIAL 6 LABEL "Width"
    FIELD summColFactoryCostShow      AS LOGICAL INITIAL YES LABEL "Show Factory Cost in Summary"
    FIELD summColFactoryCostCol       AS DECIMAL INITIAL 56 LABEL "Column Position"
    FIELD summColFactoryCostWidth     AS INTEGER INITIAL 6 LABEL "Width"
    FIELD summColFullCostShow         AS LOGICAL INITIAL YES LABEL "Show Full Cost in Summary"
    FIELD summColFullCostCol          AS DECIMAL INITIAL 66 LABEL "Column Position"
    FIELD summColFullCostWidth        AS INTEGER INITIAL 6 LABEL "Width"
    FIELD summColSellPriceShow        AS LOGICAL INITIAL YES LABEL "Show Sell Price in Summary"
    FIELD summColSellPriceCol         AS DECIMAL INITIAL 76 LABEL "Column Position"
    FIELD summColSellPriceWidth       AS INTEGER INITIAL 6 LABEL "Width"
    FIELD analysisColQuantityShow     AS LOGICAL INITIAL YES LABEL "Show Quantity in Analysis"
    FIELD analysisColQuantityLabel    AS CHARACTER INITIAL "Quantity" LABEL "Label"
    FIELD analysisColQuantityCol      AS DECIMAL INITIAL 2 LABEL "Column Position"
    FIELD analysisColQuantityWidth    AS INTEGER INITIAL 9 LABEL "Width"
    FIELD analysisColFactCostShow     AS LOGICAL INITIAL YES LABEL "Show Factory Cost in Analysis"
    FIELD analysisColFactCostLabel    AS CHARACTER INITIAL "FactCost" LABEL "Label"
    FIELD analysisColFactCostCol      AS DECIMAL INITIAL 10 LABEL "Column Position"
    FIELD analysisColFactCostWidth    AS INTEGER INITIAL 8 LABEL "Width"
    FIELD analysisColFullCostShow     AS LOGICAL INITIAL YES LABEL "Show Full Cost in Analysis"
    FIELD analysisColFullCostLabel    AS CHARACTER INITIAL "FullCost" LABEL "Label"
    FIELD analysisColFullCostCol      AS DECIMAL INITIAL 18 LABEL "Column Position"
    FIELD analysisColFullCostWidth    AS INTEGER INITIAL 8 LABEL "Width"
    FIELD analysisColGrossMarginShow  AS LOGICAL INITIAL YES LABEL "Show Gross Margin in Analysis"
    FIELD analysisColGrossMarginLabel AS CHARACTER INITIAL "GrossMargin%" LABEL "Label"
    FIELD analysisColGrossMarginCol   AS DECIMAL INITIAL 26 LABEL "Column Position"
    FIELD analysisColGrossMarginWidth AS INTEGER INITIAL 12 LABEL "Width"
    FIELD analysisColNetMarginShow    AS LOGICAL INITIAL YES LABEL "Show Net Margin in Analysis"
    FIELD analysisColNetMarginLabel   AS CHARACTER INITIAL "NetMargin%" LABEL "Label"
    FIELD analysisColNetMarginCol     AS DECIMAL INITIAL 34 LABEL "Column Position" 
    FIELD analysisColNetMarginWidth   AS INTEGER INITIAL 10 LABEL "Width"
    FIELD analysisColSellPriceShow    AS LOGICAL INITIAL YES LABEL "Show Sell Price in Analysis"
    FIELD analysisColSellPriceLabel   AS CHARACTER INITIAL "SellPrice" LABEL "Label"
    FIELD analysisColSellPriceCol     AS DECIMAL INITIAL 42 LABEL "Column Position"
    FIELD analysisColSellPriceWidth   AS INTEGER INITIAL 9 LABEL "Width"
    FIELD analysisColPriceMSFShow     AS LOGICAL INITIAL YES LABEL "Show MSF Price in Analysis"
    FIELD analysisColPriceMSFLabel    AS CHARACTER INITIAL "Price/MSF" LABEL "Label"
    FIELD analysisColPriceMSFCol      AS DECIMAL INITIAL 50 LABEL "Column Position"
    FIELD analysisColPriceMSFWidth    AS INTEGER INITIAL 9 LABEL "Width"
    FIELD analysisColSheetsShow       AS LOGICAL INITIAL YES LABEL "Show Sheets in Analysis"
    FIELD analysisColSheetsLabel      AS CHARACTER INITIAL "Sheets" LABEL "Label"
    FIELD analysisColSheetsCol        AS DECIMAL INITIAL 58 LABEL "Column Position"
    FIELD analysisColSheetsWidth      AS INTEGER INITIAL 6 LABEL "Width"
    FIELD analysisColTotalShtMSFShow  AS LOGICAL INITIAL YES LABEL "Show Total Sheets in MSF in Analysis"
    FIELD analysisColTotalShtMSFLabel AS CHARACTER INITIAL "TotalSht MSF" LABEL "Label"
    FIELD analysisColTotalShtMSFCol   AS DECIMAL INITIAL 66 LABEL "Column Position"
    FIELD analysisColTotalShtMSFWidth AS INTEGER INITIAL 12 LABEL "Width"
    FIELD analysisColBoard$MShow      AS LOGICAL INITIAL NO LABEL "Show Board#/M in Analysis"
    FIELD analysisColBoard$MLabel     AS CHARACTER INITIAL "Board$/M" LABEL "Label"
    FIELD analysisColBoard$MCol       AS DECIMAL INITIAL 16 LABEL "Column Position"
    FIELD analysisColBoard$MWidth     AS INTEGER INITIAL 6 LABEL "Width"
    FIELD analysisColBoard%Show       AS LOGICAL INITIAL NO LABEL "Show Board % in Analysis"
    FIELD analysisColBoard%Label      AS CHARACTER INITIAL "Board %" LABEL "Label"
    FIELD analysisColBoard%Col        AS DECIMAL INITIAL 26 LABEL "Column Position"
    FIELD analysisColBoard%Width      AS INTEGER INITIAL 7 LABEL "Width"
    FIELD analysisColTotalContbShow   AS LOGICAL INITIAL NO LABEL "Show Total Contribution in Analysis"
    FIELD analysisColTotalContbLabel  AS CHARACTER INITIAL "TotalContb" LABEL "Label"
    FIELD analysisColTotalContbCol    AS DECIMAL INITIAL 36 LABEL "Column Position"
    FIELD analysisColTotalContbWidth  AS INTEGER INITIAL 6 LABEL "Width"
    FIELD analysisColContbHrShow      AS LOGICAL INITIAL NO LABEL "Show Contribution/Hour in Analysis"
    FIELD analysisColContbHrLabel     AS CHARACTER INITIAL "Contb/Hr" LABEL "Label"
    FIELD analysisColContbHrCol       AS DECIMAL INITIAL 46 LABEL "Column Position"
    FIELD analysisColContbHrWidth     AS INTEGER INITIAL 6 LABEL "Width"
    FIELD showSetPartSummary          AS LOGICAL INITIAL YES LABEL "Show Part Summary"
    FIELD setPartSummPartIDShow       AS LOGICAL INITIAL YES LABEL "Show Part ID in Part Summary"
    FIELD setPartSummPartIDLabel      AS CHARACTER INITIAL "Individual Part #" LABEL "Label"
    FIELD setPartSummPartIDCol        AS DECIMAL INITIAL 2 LABEL "Column Position"
    FIELD setPartSummPartIDWidth      AS INTEGER INITIAL 30 LABEL "Width"
    FIELD setPartSummPartDescShow     AS LOGICAL INITIAL YES LABEL "Show Part Description in Part Summary"
    FIELD setPartSummPartDescLabel    AS CHARACTER INITIAL "Description" LABEL "Label"
    FIELD setPartSummPartDescCol      AS DECIMAL INITIAL 18 LABEL "Column Position"
    FIELD setPartSummPartDescWidth    AS INTEGER INITIAL 30 LABEL "Width"
    FIELD setPartSummQtyPerSetShow    AS LOGICAL INITIAL YES LABEL "Show Quantity Per Set in Part Summary"
    FIELD setPartSummQtyPerSetLabel   AS CHARACTER INITIAL "Qty/Set" LABEL "Label"
    FIELD setPartSummQtyPerSetCol     AS DECIMAL INITIAL 50 LABEL "Column Position"
    FIELD setPartSummQtyPerSetWidth   AS INTEGER INITIAL 10 LABEL "Width"
    FIELD setPartSummSellPriceShow    AS LOGICAL INITIAL YES LABEL "Show Sell Price in Part Summary"
    FIELD setPartSummSellPriceLabel   AS CHARACTER INITIAL "Sell Price" LABEL "Label"
    FIELD setPartSummSellPriceCol     AS DECIMAL INITIAL 58 LABEL "Column Position"
    FIELD setPartSummSellPriceWidth   AS INTEGER INITIAL 10 LABEL "Width"
    FIELD setPartSummPricePerEAShow   AS LOGICAL INITIAL YES LABEL "Show Price Per Each in Part Summary"
    FIELD setPartSummPricePerEALabel  AS CHARACTER INITIAL "Price/EA" LABEL "Label"
    FIELD setPartSummPricePerEACol    AS DECIMAL INITIAL 67 LABEL "Column Position"
    FIELD setPartSummPricePerEAWidth  AS INTEGER INITIAL 10 LABEL "Width"
    FIELD showBillablePrep            AS LOGICAL INITIAL YES LABEL "Show Billable Preps?"
    FIELD billablePrepItemIDShow      AS LOGICAL INITIAL YES LABEL "Show Item ID Billable Preps?"
    FIELD billablePrepItemIDLabel     AS CHARACTER INITIAL "Item" LABEL "Label"
    FIELD billablePrepItemIDCol       AS DECIMAL INITIAL 2 LABEL "Column Position"
    FIELD billablePrepItemIDWidth     AS INTEGER INITIAL 15 LABEL "Width"
    FIELD billablePrepItemNameShow    AS LOGICAL INITIAL YES LABEL "Show Item Name in Billable Preps?" 
    FIELD billablePrepItemNameLabel   AS CHARACTER INITIAL "Name" LABEL "Label"
    FIELD billablePrepItemNameCol     AS DECIMAL INITIAL 20 LABEL "Column Position"
    FIELD billablePrepItemNameWidth   AS INTEGER INITIAL 30 LABEL "Width"
    FIELD billablePrepItemCostShow    AS LOGICAL INITIAL YES LABEL "Show Item Cost in Billable Preps?"
    FIELD billablePrepItemCostLabel   AS CHARACTER INITIAL "Cost" LABEL "Label"
    FIELD billablePrepItemCostCol     AS DECIMAL INITIAL 50 LABEL "Column Position"
    FIELD billablePrepItemCostWidth   AS INTEGER INITIAL 10 LABEL "Width"    
    .
