/* cust-markup.p - generated 12/09/2005 - 15:42:40 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_cust-markup1 NO-UNDO LIKE cust-markup.
DEFINE WORK-TABLE ttbl_cust-markup2 NO-UNDO LIKE cust-markup.

CREATE ttbl_cust-markup1.
IMPORT STREAM s_audit_file ttbl_cust-markup1.
CREATE ttbl_cust-markup2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_cust-markup2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_cust-markup1.company NE ttbl_cust-markup2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_cust-markup1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.company NE ttbl_cust-markup2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_cust-markup2.company.
  END.
END.
DO i = 1 TO 2:
IF NOT v_field_changed OR ttbl_cust-markup1.curr-code[i] NE ttbl_cust-markup2.curr-code[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Currency Code[" AT 3 i "]: " ttbl_cust-markup1.curr-code[i] " (curr-code[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.curr-code[i] NE ttbl_cust-markup2.curr-code[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Currency Code[" AT 3 i "]: " ttbl_cust-markup2.curr-code[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_cust-markup1.cust-no NE ttbl_cust-markup2.cust-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 3 ttbl_cust-markup1.cust-no " (cust-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.cust-no NE ttbl_cust-markup2.cust-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 3 ttbl_cust-markup2.cust-no.
  END.
END.
IF NOT v_field_changed OR ttbl_cust-markup1.ex-rate NE ttbl_cust-markup2.ex-rate OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_cust-markup1.ex-rate FORMAT "->>,>>9.99<<<<<" " (ex-rate)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.ex-rate NE ttbl_cust-markup2.ex-rate THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_cust-markup2.ex-rate FORMAT "->>,>>9.99<<<<<".
  END.
END.
DO i = 1 TO 10:
IF NOT v_field_changed OR ttbl_cust-markup1.markup[i] NE ttbl_cust-markup2.markup[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Markup %[" AT 3 i "]: " ttbl_cust-markup1.markup[i] FORMAT "->>>9.99<<<" " (markup[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.markup[i] NE ttbl_cust-markup2.markup[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Markup %[" AT 3 i "]: " ttbl_cust-markup2.markup[i] FORMAT "->>>9.99<<<".
  END.
END.
END.
DO i = 1 TO 10:
IF NOT v_field_changed OR ttbl_cust-markup1.markup-on[i] NE ttbl_cust-markup2.markup-on[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Markup On?[" AT 3 i "]: " ttbl_cust-markup1.markup-on[i] " (markup-on[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.markup-on[i] NE ttbl_cust-markup2.markup-on[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Markup On?[" AT 3 i "]: " ttbl_cust-markup2.markup-on[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_cust-markup1.procat NE ttbl_cust-markup2.procat OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Category: " AT 3 ttbl_cust-markup1.procat " (procat)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.procat NE ttbl_cust-markup2.procat THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Category: " AT 3 ttbl_cust-markup2.procat.
  END.
END.
DO i = 1 TO 10:
IF NOT v_field_changed OR ttbl_cust-markup1.run-qty[i] NE ttbl_cust-markup2.run-qty[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "MSF To[" AT 3 i "]: " ttbl_cust-markup1.run-qty[i] FORMAT ">,>>>,>>9.9<<<<" " (run-qty[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.run-qty[i] NE ttbl_cust-markup2.run-qty[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "MSF To[" AT 3 i "]: " ttbl_cust-markup2.run-qty[i] FORMAT ">,>>>,>>9.9<<<<".
  END.
END.
END.
IF NOT v_field_changed OR ttbl_cust-markup1.style NE ttbl_cust-markup2.style OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Style Code: " AT 3 ttbl_cust-markup1.style " (style)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.style NE ttbl_cust-markup2.style THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Style Code: " AT 3 ttbl_cust-markup2.style.
  END.
END.
IF NOT v_field_changed OR ttbl_cust-markup1.upd-date NE ttbl_cust-markup2.upd-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Updated Date: " AT 3 ttbl_cust-markup1.upd-date FORMAT "99/99/9999" " (upd-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.upd-date NE ttbl_cust-markup2.upd-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Updated Date: " AT 3 ttbl_cust-markup2.upd-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_cust-markup1.upd-time NE ttbl_cust-markup2.upd-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Updated Time: " AT 3 ttbl_cust-markup1.upd-time FORMAT "->,>>>,>>9" " (upd-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_cust-markup1.upd-time NE ttbl_cust-markup2.upd-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Updated Time: " AT 3 ttbl_cust-markup2.upd-time FORMAT "->,>>>,>>9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Customer: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup2.cust-no " (cust-no)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup1.cust-no " (cust-no)".
  PUT STREAM s-audit-rpt UNFORMATTED "Category: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup2.procat " (procat)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup1.procat " (procat)".
  PUT STREAM s-audit-rpt UNFORMATTED "Style Code: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup2.style " (style)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_cust-markup1.style " (style)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
