/* job.p - generated 12/09/2005 - 15:42:47 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_job1 NO-UNDO LIKE job.
DEFINE WORK-TABLE ttbl_job2 NO-UNDO LIKE job.

CREATE ttbl_job1.
IMPORT STREAM s_audit_file ttbl_job1.
CREATE ttbl_job2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_job2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_job1.cancel-date NE ttbl_job2.cancel-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Cancel Date: " AT 3 ttbl_job1.cancel-date FORMAT "99/99/9999" " (cancel-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.cancel-date NE ttbl_job2.cancel-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Cancel Date: " AT 3 ttbl_job2.cancel-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.close-date NE ttbl_job2.close-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.close-date FORMAT "99/99/9999" " (close-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.close-date NE ttbl_job2.close-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.close-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.company NE ttbl_job2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_job1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.company NE ttbl_job2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_job2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_job1.complete-date NE ttbl_job2.complete-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Complete Date: " AT 3 ttbl_job1.complete-date FORMAT "99/99/9999" " (complete-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.complete-date NE ttbl_job2.complete-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Complete Date: " AT 3 ttbl_job2.complete-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.complete-time NE ttbl_job2.complete-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.complete-time FORMAT "->,>>>,>>9" " (complete-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.complete-time NE ttbl_job2.complete-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.complete-time FORMAT "->,>>>,>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.create-date NE ttbl_job2.create-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Create Date: " AT 3 ttbl_job1.create-date FORMAT "99/99/9999" " (create-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.create-date NE ttbl_job2.create-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Create Date: " AT 3 ttbl_job2.create-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.due-date NE ttbl_job2.due-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Due Date: " AT 3 ttbl_job1.due-date FORMAT "99/99/9999" " (due-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.due-date NE ttbl_job2.due-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Due Date: " AT 3 ttbl_job2.due-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.due-time NE ttbl_job2.due-time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Due Time: " AT 3 ttbl_job1.due-time FORMAT ">>>>9" " (due-time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.due-time NE ttbl_job2.due-time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Due Time: " AT 3 ttbl_job2.due-time FORMAT ">>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.e-num NE ttbl_job2.e-num OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate Number: " AT 3 ttbl_job1.e-num FORMAT ">>>>>9" " (e-num)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.e-num NE ttbl_job2.e-num THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Estimate Number: " AT 3 ttbl_job2.e-num FORMAT ">>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.est-no NE ttbl_job2.est-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 3 ttbl_job1.est-no " (est-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.est-no NE ttbl_job2.est-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Estimate #: " AT 3 ttbl_job2.est-no.
  END.
END.
IF NOT v_field_changed OR ttbl_job1.exported NE ttbl_job2.exported OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Exported: " AT 3 ttbl_job1.exported FORMAT "Yes/No" " (exported)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.exported NE ttbl_job2.exported THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Exported: " AT 3 ttbl_job2.exported FORMAT "Yes/No".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.job NE ttbl_job2.job OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 3 ttbl_job1.job FORMAT ">>>>>>9" " (job)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.job NE ttbl_job2.job THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 3 ttbl_job2.job FORMAT ">>>>>>9".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.job-no NE ttbl_job2.job-no OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_job1.job-no " (job-no)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.job-no NE ttbl_job2.job-no THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Job Number: " AT 3 ttbl_job2.job-no.
  END.
END.
IF NOT v_field_changed OR ttbl_job1.job-no2 NE ttbl_job2.job-no2 OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Run #: " AT 3 ttbl_job1.job-no2 FORMAT ">9" " (job-no2)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.job-no2 NE ttbl_job2.job-no2 THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Run #: " AT 3 ttbl_job2.job-no2 FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.loc NE ttbl_job2.loc OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Warehouse: " AT 3 ttbl_job1.loc " (loc)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.loc NE ttbl_job2.loc THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Warehouse: " AT 3 ttbl_job2.loc.
  END.
END.
IF NOT v_field_changed OR ttbl_job1.lock NE ttbl_job2.lock OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Locked: " AT 3 ttbl_job1.lock FORMAT "Y/N" " (lock)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.lock NE ttbl_job2.lock THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Locked: " AT 3 ttbl_job2.lock FORMAT "Y/N".
  END.
END.
DO i = 1 TO 6:
IF NOT v_field_changed OR ttbl_job1.notes[i] NE ttbl_job2.notes[i] OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_job1.notes[i] " (notes[" i "])".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.notes[i] NE ttbl_job2.notes[i] THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Notes[" AT 3 i "]: " ttbl_job2.notes[i].
  END.
END.
END.
IF NOT v_field_changed OR ttbl_job1.opened NE ttbl_job2.opened OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.opened FORMAT "Open/Closed" " (opened)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.opened NE ttbl_job2.opened THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.opened FORMAT "Open/Closed".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.start-date NE ttbl_job2.start-date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Start Date: " AT 3 ttbl_job1.start-date FORMAT "99/99/9999" " (start-date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.start-date NE ttbl_job2.start-date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Start Date: " AT 3 ttbl_job2.start-date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.stat NE ttbl_job2.stat OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Job Status: " AT 3 ttbl_job1.stat " (stat)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.stat NE ttbl_job2.stat THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Job Status: " AT 3 ttbl_job2.stat.
  END.
END.
IF NOT v_field_changed OR ttbl_job1.std-fix-cost NE ttbl_job2.std-fix-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.std-fix-cost FORMAT "->>>,>>9.99<<" " (std-fix-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.std-fix-cost NE ttbl_job2.std-fix-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.std-fix-cost FORMAT "->>>,>>9.99<<".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.std-lab-cost NE ttbl_job2.std-lab-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.std-lab-cost FORMAT "->>>,>>9.99<<" " (std-lab-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.std-lab-cost NE ttbl_job2.std-lab-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.std-lab-cost FORMAT "->>>,>>9.99<<".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.std-mat-cost NE ttbl_job2.std-mat-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.std-mat-cost FORMAT "->>>,>>9.99<<" " (std-mat-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.std-mat-cost NE ttbl_job2.std-mat-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.std-mat-cost FORMAT "->>>,>>9.99<<".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.std-tot-cost NE ttbl_job2.std-tot-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.std-tot-cost FORMAT "->>>,>>9.99<<" " (std-tot-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.std-tot-cost NE ttbl_job2.std-tot-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.std-tot-cost FORMAT "->>>,>>9.99<<".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.std-var-cost NE ttbl_job2.std-var-cost OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.std-var-cost FORMAT "->>>,>>9.99<<" " (std-var-cost)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.std-var-cost NE ttbl_job2.std-var-cost THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.std-var-cost FORMAT "->>>,>>9.99<<".
  END.
END.
IF NOT v_field_changed OR ttbl_job1.user-id NE ttbl_job2.user-id OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job1.user-id " (user-id)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_job1.user-id NE ttbl_job2.user-id THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "?: " AT 3 ttbl_job2.user-id.
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Unique Internial Job Number: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job2.job FORMAT ">>>>>>9" " (job)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_job1.job FORMAT ">>>>>>9" " (job)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
