/* period.p - generated 12/09/2005 - 15:42:51 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_period1 NO-UNDO LIKE period.
DEFINE WORK-TABLE ttbl_period2 NO-UNDO LIKE period.

CREATE ttbl_period1.
IMPORT STREAM s_audit_file ttbl_period1.
CREATE ttbl_period2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_period2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_period1.company NE ttbl_period2.company OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_period1.company " (company)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.company NE ttbl_period2.company THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 3 ttbl_period2.company.
  END.
END.
IF NOT v_field_changed OR ttbl_period1.pend NE ttbl_period2.pend OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Period End Date: " AT 3 ttbl_period1.pend FORMAT "99/99/9999" " (pend)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.pend NE ttbl_period2.pend THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Period End Date: " AT 3 ttbl_period2.pend FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_period1.pname NE ttbl_period2.pname OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Month: " AT 3 ttbl_period1.pname " (pname)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.pname NE ttbl_period2.pname THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Month: " AT 3 ttbl_period2.pname.
  END.
END.
IF NOT v_field_changed OR ttbl_period1.pnum NE ttbl_period2.pnum OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Period: " AT 3 ttbl_period1.pnum FORMAT ">9" " (pnum)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.pnum NE ttbl_period2.pnum THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Period: " AT 3 ttbl_period2.pnum FORMAT ">9".
  END.
END.
IF NOT v_field_changed OR ttbl_period1.pst NE ttbl_period2.pst OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Period Start Date: " AT 3 ttbl_period1.pst FORMAT "99/99/9999" " (pst)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.pst NE ttbl_period2.pst THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Period Start Date: " AT 3 ttbl_period2.pst FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_period1.pstat NE ttbl_period2.pstat OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Period Status: " AT 3 ttbl_period1.pstat FORMAT "Open/Closed" " (pstat)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.pstat NE ttbl_period2.pstat THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Period Status: " AT 3 ttbl_period2.pstat FORMAT "Open/Closed".
  END.
END.
IF NOT v_field_changed OR ttbl_period1.yr NE ttbl_period2.yr OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Year: " AT 3 ttbl_period1.yr FORMAT "9999" " (yr)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_period1.yr NE ttbl_period2.yr THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Year: " AT 3 ttbl_period2.yr FORMAT "9999".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Company: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period2.company " (company)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period1.company " (company)".
  PUT STREAM s-audit-rpt UNFORMATTED "Year: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period2.yr FORMAT "9999" " (yr)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period1.yr FORMAT "9999" " (yr)".
  PUT STREAM s-audit-rpt UNFORMATTED "Period Start Date: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period2.pst FORMAT "99/99/9999" " (pst)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period1.pst FORMAT "99/99/9999" " (pst)".
  PUT STREAM s-audit-rpt UNFORMATTED "Period: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period2.pnum FORMAT ">9" " (pnum)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_period1.pnum FORMAT ">9" " (pnum)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
