/* sbStatus.p - generated 12/09/2005 - 15:42:54 by NoSweat */

/* this program was generated by auditgn1.p and should not be modified */
/* modifications should be made to the auto generation program         */

DEFINE INPUT PARAMETER action AS CHARACTER NO-UNDO.

DEFINE VARIABLE i AS INTEGER NO-UNDO.

{methods/defines/audit.i}
FIND FIRST ttbl_header.

DEFINE WORK-TABLE ttbl_sbStatus1 NO-UNDO LIKE sbStatus.
DEFINE WORK-TABLE ttbl_sbStatus2 NO-UNDO LIKE sbStatus.

CREATE ttbl_sbStatus1.
IMPORT STREAM s_audit_file ttbl_sbStatus1.
CREATE ttbl_sbStatus2.
IF action = "UPDATE" THEN
IMPORT STREAM s_audit_file ttbl_sbStatus2.

PUT STREAM s-audit-rpt UNFORMATTED
  "Action    User ID/(User Name)            DB.Table/(Database)  Date       Time" SKIP
  "--------- ------------------------------ -------------------- ---------- --------" SKIP
  ttbl_header.v_action AT 1
  ttbl_header.v_userid AT 11
  ttbl_header.v_file AT 42
  ttbl_header.v_date FORMAT "99/99/9999" AT 63
  STRING(ttbl_header.v_time,"HH:MM:SS") AT 74.
FIND users WHERE users.user_id = v_userid NO-LOCK NO-ERROR.
IF AVAILABLE users THEN
PUT STREAM s-audit-rpt UNFORMATTED "(" AT 10 users.user_name ")".
ELSE
PUT STREAM s-audit-rpt UNFORMATTED "(user record does not exist)" AT 10.
PUT STREAM s-audit-rpt UNFORMATTED
  "(" AT 41 ttbl_header.v_db ")" SKIP(1)
  "Label: Value (database field-name)" AT 3.
IF action = "UPDATE" THEN
PUT STREAM s-audit-rpt UNFORMATTED " ( * - denotes field value change )".
PUT STREAM s-audit-rpt UNFORMATTED FILL("-",75) AT 3.
IF NOT v_field_changed OR ttbl_sbStatus1.completed NE ttbl_sbStatus2.completed OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Completed: " AT 3 ttbl_sbStatus1.completed FORMAT "yes/no" " (completed)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_sbStatus1.completed NE ttbl_sbStatus2.completed THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Completed: " AT 3 ttbl_sbStatus2.completed FORMAT "yes/no".
  END.
END.
IF NOT v_field_changed OR ttbl_sbStatus1.sbStatus NE ttbl_sbStatus2.sbStatus OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Status: " AT 3 ttbl_sbStatus1.sbStatus " (sbStatus)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_sbStatus1.sbStatus NE ttbl_sbStatus2.sbStatus THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Status: " AT 3 ttbl_sbStatus2.sbStatus.
  END.
END.
IF NOT v_field_changed OR ttbl_sbStatus1.user_date NE ttbl_sbStatus2.user_date OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 3 ttbl_sbStatus1.user_date FORMAT "99/99/9999" " (user_date)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_sbStatus1.user_date NE ttbl_sbStatus2.user_date THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Date: " AT 3 ttbl_sbStatus2.user_date FORMAT "99/99/9999".
  END.
END.
IF NOT v_field_changed OR ttbl_sbStatus1.user_id NE ttbl_sbStatus2.user_id OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 3 ttbl_sbStatus1.user_id " (user_id)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_sbStatus1.user_id NE ttbl_sbStatus2.user_id THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "User ID: " AT 3 ttbl_sbStatus2.user_id.
  END.
END.
IF NOT v_field_changed OR ttbl_sbStatus1.user_time NE ttbl_sbStatus2.user_time OR action NE "UPDATE" THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Time: " AT 3 ttbl_sbStatus1.user_time FORMAT ">>>>9" " (user_time)".
  IF action = "UPDATE" THEN
  DO:
    IF ttbl_sbStatus1.user_time NE ttbl_sbStatus2.user_time THEN
    PUT STREAM s-audit-rpt UNFORMATTED "*" AT 1.
    PUT STREAM s-audit-rpt UNFORMATTED "Time: " AT 3 ttbl_sbStatus2.user_time FORMAT ">>>>9".
  END.
END.
IF v_show_index THEN
DO:
  PUT STREAM s-audit-rpt UNFORMATTED "Index Fields - Label: Value (database field-name)" AT 5.
  PUT STREAM s-audit-rpt UNFORMATTED "Status: " AT 7.
  IF action = "UPDATE" THEN
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_sbStatus2.sbStatus " (sbStatus)".
  ELSE
  PUT STREAM s-audit-rpt UNFORMATTED ttbl_sbStatus1.sbStatus " (sbStatus)".
END.
PUT STREAM s-audit-rpt UNFORMATTED SKIP(1).
