DEF INPUT PARAMETER ipBinQty AS DEC NO-UNDO.
DEF INPUT-OUTPUT PARAMETER ipBinCost AS DEC NO-UNDO.
DEF INPUT PARAMETER ipTransQty AS DEC NO-UNDO.
DEF INPUT PARAMETER ipTransCost AS DEC NO-UNDO.

DEF VAR v-r-qty AS DEC DECIMALS 6 NO-UNDO.
DEF VAR v-i-qty AS DEC DECIMALS 6 NO-UNDO.
DEF VAR v-t-qty AS DEC DECIMALS 6 NO-UNDO.

{rm\rm-post.i ipBinQty ipBinCost ipTransQty ipTransCost}
